In [ ]:
upstream = None
product = None
mcleish24_tables2 = None

# Experimental data: Libraries and hosts

In [46]:
import pandas as pd
import requests
import json
import re
import random
import datetime

In [53]:
def timestamp_code():
    """
    This function generates a time stamp that goes
    to microsecond level, and it adds a random code
    just in case
    """
    now = datetime.datetime.now()
    timestamp = now.strftime("%Y%m%d%H%M%S%f")
    random.seed(timestamp[-4:])
    random_code = "{:03d}".format(random.randint(0, 100))
    return timestamp +  random_code

print(timestamp_code())
print(timestamp_code())
for i in range(1000):
    if timestamp_code() == timestamp_code():
        raise RuntimeError("the function did not work")

20251006110317675943068
20251006110317676105082

## Loading data

In [ ]:
libraries = pd.read_csv(mcleish24_tables2, sep=';')
libraries

    Library_code            Host_taxon Habitat Collection_code  No_extracts
0          PV001         Amaranthus sp    Crop             M1V            8
1          PV002  Convolvulus arvensis    Crop             M1V           11
2          PV003          Cucumis melo    Crop             M1V           13
3       PV003bgi          Cucumis melo    Crop             M1V           13
4       PV004bgi        Cyperus longus    Crop             M1V            7
..           ...                   ...     ...             ...          ...
318        PV586    Fumaria parviflora    Crop             H1P            8
319        PV587   Hirschfeldia incana    Crop             H1P            8
320        PV588       Hordeum vulgare    Crop             H1P            8
321        PV589       Hordeum vulgare    Crop             H1P            8
322        PV590              Zea mays    Crop             Z1V           11

[323 rows x 5 columns]

## Assign taxonomic categories

The following function should enable us to obtain the taxonomy codes by querying against the NCBI.

In [14]:
def search_taxonomy(host_name):
    url = "https://api.ncbi.nlm.nih.gov/datasets/v2"
    url = f'{url}/taxonomy/taxon/{host_name}'.replace(' ', '%20')

    r = requests.get(url)
    try: 
        r.raise_for_status()
    except requests.HTTPError:
        return pd.NA
    try:
        u = str(r.json()['taxonomy_nodes'][0]['taxonomy']['tax_id'])
    except KeyError:
        return pd.NA
    except IndexError:
        return pd.NA
    return u

search_taxonomy("Retama sphaerocarpa") # 49838

'49838'

Now a bit of simple editing to ease the search. We are discarding variety names, and we are replacing the sp symbols by sp. using regex (otherwise, some species with internals "sp" might get a "sp.")

In [13]:
hosts = libraries.drop_duplicates(subset=['Host_taxon'])[['Host_taxon']]
hosts['Host_curated'] = hosts['Host_taxon'].apply(lambda x: re.sub("sp$", "sp.", x))
hosts['Host_curated'] = hosts['Host_curated'].apply(lambda x: " ".join(x.split(" ")[:2]))
hosts

               Host_taxon          Host_curated
0           Amaranthus sp        Amaranthus sp.
1    Convolvulus arvensis  Convolvulus arvensis
2            Cucumis melo          Cucumis melo
4          Cyperus longus        Cyperus longus
5    Artemisia herba alba       Artemisia herba
..                    ...                   ...
309   Lithodora fruticosa   Lithodora fruticosa
310      Origanum vulgare      Origanum vulgare
311     Rhamnus lycioides     Rhamnus lycioides
315   Astragalus sesameus   Astragalus sesameus
317    Borago officinalis    Borago officinalis

[119 rows x 2 columns]

We convert the table into a deduplicated list of organisms names, and we search all of them against the NCBI.

In [55]:

species_taxid_map = []
for item in hosts['Host_curated'].unique().tolist():
    species_taxid_map.append(
        dict(species_name=item, taxid=search_taxonomy(item), code=timestamp_code())
    )
    print(species_taxid_map[-1])
hosts = pd.merge(hosts, pd.DataFrame.from_records(species_taxid_map), left_on='Host_curated', right_on='species_name')
hosts = hosts[['Host_taxon', 'taxid', 'code']]
hosts

{'species_name': 'Amaranthus sp.', 'taxid': '3076757', 'code': '20251006110439666773010'}
{'species_name': 'Convolvulus arvensis', 'taxid': '4123', 'code': '20251006110440201955043'}
{'species_name': 'Cucumis melo', 'taxid': '3656', 'code': '20251006110440754997052'}
{'species_name': 'Cyperus longus', 'taxid': '76433', 'code': '20251006110441254052093'}
{'species_name': 'Artemisia herba', 'taxid': <NA>, 'code': '20251006110441672270075'}
{'species_name': 'Teucrium pseudochamaepitys', 'taxid': '1209883', 'code': '20251006110442177792043'}
{'species_name': 'Jasminum fruticans', 'taxid': <NA>, 'code': '20251006110442545729047'}
{'species_name': 'Quercus coccifera', 'taxid': '58335', 'code': '20251006110443041873018'}
{'species_name': 'Quercus ilex', 'taxid': '58334', 'code': '20251006110443582725004'}
{'species_name': 'Portulaca oleraceae', 'taxid': <NA>, 'code': '20251006110443948438099'}
{'species_name': 'Chenopodium album', 'taxid': '3559', 'code': '20251006110444445883041'}
{'species_name': 'Solanum nigrum', 'taxid': '4112', 'code': '20251006110444947084078'}
{'species_name': 'Datura stramonium', 'taxid': '4076', 'code': '20251006110445458077095'}
{'species_name': 'Lithospermum arvense', 'taxid': '181181', 'code': '20251006110445955428019'}
{'species_name': 'Taraxacum officinale', 'taxid': '50225', 'code': '20251006110446481915055'}
{'species_name': 'Leontodon sp.', 'taxid': '3387808', 'code': '20251006110446996002023'}
{'species_name': 'Verbascum sinuatum', 'taxid': '1042526', 'code': '20251006110447510093027'}
{'species_name': 'Geranium sp.', 'taxid': '45161', 'code': '20251006110448009546051'}
{'species_name': 'Hieracium pilosella', 'taxid': '221204', 'code': '20251006110448506830096'}
{'species_name': 'Festuca sp.', 'taxid': '3110559', 'code': '20251006110449027777049'}
{'species_name': 'Rubia peregrina', 'taxid': '29801', 'code': '20251006110450227677064'}
{'species_name': 'Picris echioides', 'taxid': <NA>, 'code': '20251006110450587403001'}
{'species_name': 'Milium vernale', 'taxid': '368341', 'code': '20251006110451127962004'}
{'species_name': 'Brachypodium retusum', 'taxid': '52142', 'code': '20251006110451864110095'}
{'species_name': 'Asparagus acutifolius', 'taxid': '191654', 'code': '20251006110452407095018'}
{'species_name': 'Avenula bromoides', 'taxid': <NA>, 'code': '20251006110452786960045'}
{'species_name': 'Carduus bourgeanus', 'taxid': <NA>, 'code': '20251006110453154321006'}
{'species_name': 'Zea mays', 'taxid': '4577', 'code': '20251006110453694838062'}
{'species_name': 'Desconocida 4', 'taxid': <NA>, 'code': '20251006110454097988095'}
{'species_name': 'Xanthium strumarium', 'taxid': '318068', 'code': '20251006110454622715038'}
{'species_name': 'Lotus corniculatus', 'taxid': '47247', 'code': '20251006110455184662089'}
{'species_name': 'Astragalus incanus', 'taxid': '1532285', 'code': '20251006110455757031073'}
{'species_name': 'Thymus vulgaris', 'taxid': '49992', 'code': '20251006110456261636041'}
{'species_name': 'Melilotus sp.', 'taxid': '3237839', 'code': '20251006110456775660072'}
{'species_name': 'Medicago orbicularis', 'taxid': '70962', 'code': '20251006110457324128037'}
{'species_name': 'Vicia sp.', 'taxid': '3387867', 'code': '20251006110457839895014'}
{'species_name': 'Tragopogon sp.', 'taxid': '3122769', 'code': '20251006110458370851097'}
{'species_name': 'Reseda lutea', 'taxid': '202615', 'code': '20251006110458866158097'}
{'species_name': 'Diplotaxis erucoides', 'taxid': '3732', 'code': '20251006110459755442031'}
{'species_name': 'Plantago sp.', 'taxid': '3237854', 'code': '20251006110500317997052'}
{'species_name': 'Descurainia sophia', 'taxid': '89411', 'code': '20251006110500859490025'}
{'species_name': 'Salvia verbenaca', 'taxid': '268912', 'code': '20251006110501360223001'}
{'species_name': 'Bromus sp.', 'taxid': '3342977', 'code': '20251006110502014336081'}
{'species_name': 'Odontites luteus', 'taxid': '691781', 'code': '20251006110502525060046'}
{'species_name': 'Marrubium vulgare', 'taxid': '41230', 'code': '20251006110503050858029'}
{'species_name': 'Teucrium capitatum', 'taxid': '1117667', 'code': '20251006110503724455094'}
{'species_name': 'Avena sterilis', 'taxid': '83444', 'code': '20251006110504220677042'}
{'species_name': 'Echium vulgare', 'taxid': '34253', 'code': '20251006110504712267077'}
{'species_name': 'Andryala arenaria', 'taxid': '1571139', 'code': '20251006110505237278066'}
{'species_name': 'Dactylis glomerata', 'taxid': '4509', 'code': '20251006110505747758004'}
{'species_name': 'Galium verum', 'taxid': '462873', 'code': '20251006110506280389084'}
{'species_name': 'Anchusa undulata', 'taxid': '256482', 'code': '20251006110506796344069'}
{'species_name': 'Hypericum pubescens', 'taxid': '1137014', 'code': '20251006110507305375033'}
{'species_name': 'Diplotaxis virgata', 'taxid': '308285', 'code': '20251006110507815148001'}
{'species_name': 'Aphyllanthes monspeliensis', 'taxid': '59052', 'code': '20251006110508312702064'}
{'species_name': 'Asphodelus aestivus', 'taxid': '49698', 'code': '20251006110508868184063'}
{'species_name': 'Centaurea melitensis', 'taxid': '41536', 'code': '20251006110509410461037'}
{'species_name': 'Helichrysum stoechas', 'taxid': '261805', 'code': '20251006110509952853065'}
{'species_name': 'Teucrium botrys', 'taxid': '1209845', 'code': '20251006110510459140049'}
{'species_name': 'Centranthus calcitrapae', 'taxid': <NA>, 'code': '20251006110510824342008'}
{'species_name': 'Staehelina dubia', 'taxid': '313545', 'code': '20251006110511332646088'}
{'species_name': 'Daucus sp.', 'taxid': <NA>, 'code': '20251006110511696704080'}
{'species_name': 'Poaceae', 'taxid': '4479', 'code': '20251006110512217915033'}
{'species_name': 'Lactuca serriola', 'taxid': '75943', 'code': '20251006110512765568082'}
{'species_name': 'Lepidium draba', 'taxid': '153317', 'code': '20251006110513282788051'}
{'species_name': 'Rumex pulcher', 'taxid': '291098', 'code': '20251006110513987987068'}
{'species_name': 'Malva sylvestris', 'taxid': '145754', 'code': '20251006110514491548092'}
{'species_name': 'Senecio jacobaea', 'taxid': '98722', 'code': '20251006110514989151043'}
{'species_name': 'Silybum marianum', 'taxid': '92921', 'code': '20251006110515593783087'}
{'species_name': 'Torilis nodosa', 'taxid': '40891', 'code': '20251006110516101271098'}
{'species_name': 'Diplotaxis sp.', 'taxid': <NA>, 'code': '20251006110516461585018'}
{'species_name': 'Fumaria parviflora', 'taxid': '1464625', 'code': '20251006110517299675084'}
{'species_name': 'Lolium perenne', 'taxid': '4522', 'code': '20251006110517859634059'}
{'species_name': 'Potentilla sp.', 'taxid': '3237857', 'code': '20251006110518343641047'}
{'species_name': 'Papaver rhoeas', 'taxid': '33128', 'code': '20251006110518919163077'}
{'species_name': 'Scandix pecten', 'taxid': <NA>, 'code': '20251006110519302849037'}
{'species_name': 'Anthriscus caucalis', 'taxid': '54826', 'code': '20251006110519849752100'}
{'species_name': 'Aristolochia pistolochia', 'taxid': '212733', 'code': '20251006110520358356010'}
{'species_name': 'Brachypodium phoenicoides', 'taxid': '65973', 'code': '20251006110520864311042'}
{'species_name': 'Hirschfeldia incana', 'taxid': '71354', 'code': '20251006110521358599082'}
{'species_name': 'Conyza canadensis', 'taxid': '72917', 'code': '20251006110521889324005'}
{'species_name': 'Sonchus oleraceus', 'taxid': '50207', 'code': '20251006110522390436059'}
{'species_name': 'Anacyclus clavatus', 'taxid': '99026', 'code': '20251006110522958964033'}
{'species_name': 'Bassia scoparia', 'taxid': '83154', 'code': '20251006110523465899078'}
{'species_name': 'Cynodon dactylon', 'taxid': '28909', 'code': '20251006110523966861033'}
{'species_name': 'Allium sativum', 'taxid': '4682', 'code': '20251006110524472457035'}
{'species_name': 'Conyza bonariensis', 'taxid': '91242', 'code': '20251006110525117760041'}
{'species_name': 'Eruca vesicaria', 'taxid': '180536', 'code': '20251006110525651134081'}
{'species_name': 'Cirsium arvense', 'taxid': '41550', 'code': '20251006110526142831015'}
{'species_name': 'Phalaris minor', 'taxid': '222563', 'code': '20251006110526655583016'}
{'species_name': 'Trifolium campestre', 'taxid': '97015', 'code': '20251006110527192618016'}
{'species_name': 'Erodium cicutarium', 'taxid': '301481', 'code': '20251006110527748290092'}
{'species_name': 'Desconocida 5', 'taxid': <NA>, 'code': '20251006110528113195087'}
{'species_name': 'Sisymbrium runcinatum', 'taxid': '2790294', 'code': '20251006110528661168022'}
{'species_name': 'Teucrium chamaedrys', 'taxid': '53176', 'code': '20251006110529186725043'}
{'species_name': 'Stipa parviflora', 'taxid': <NA>, 'code': '20251006110529907138096'}
{'species_name': 'Asteriscus aquaticus', 'taxid': '73982', 'code': '20251006110530462718072'}
{'species_name': 'Phlomis lychnitis', 'taxid': '316266', 'code': '20251006110530959223067'}
{'species_name': 'Eryngium campestre', 'taxid': '82086', 'code': '20251006110531494894056'}
{'species_name': 'Hordeum matritense', 'taxid': <NA>, 'code': '20251006110531861947085'}
{'species_name': 'Medicago sp.', 'taxid': '3140762', 'code': '20251006110532372060063'}
{'species_name': 'Thapsia villosa', 'taxid': '512635', 'code': '20251006110532964321006'}
{'species_name': 'Klasea pinnatifida', 'taxid': '354316', 'code': '20251006110533574166067'}
{'species_name': 'Hordeum vulgare', 'taxid': '4513', 'code': '20251006110534079859014'}
{'species_name': 'Brassica oleracea', 'taxid': '3712', 'code': '20251006110534577115066'}
{'species_name': 'Dittrichia viscosa', 'taxid': '56525', 'code': '20251006110535166564066'}
{'species_name': 'Foeniculum vulgare', 'taxid': '2849586', 'code': '20251006110535702130069'}
{'species_name': 'Phlomis purpurea', 'taxid': '316258', 'code': '20251006110536266288082'}
{'species_name': 'Retama sphaerocarpa', 'taxid': '49838', 'code': '20251006110537776009019'}
{'species_name': 'Crataegus monogyna', 'taxid': '140997', 'code': '20251006110538277934018'}
{'species_name': 'Bupleurum rigidum', 'taxid': '199748', 'code': '20251006110538790594048'}
{'species_name': 'Trifolium tomentosum', 'taxid': '361564', 'code': '20251006110539308450067'}
{'species_name': 'Helianthemum cinereum', 'taxid': '1336677', 'code': '20251006110539822899019'}
{'species_name': 'Lavandula latifolia', 'taxid': '39331', 'code': '20251006110540324616099'}
{'species_name': 'Lithodora fruticosa', 'taxid': '475890', 'code': '20251006110540840025049'}
{'species_name': 'Origanum vulgare', 'taxid': '39352', 'code': '20251006110541477751038'}
{'species_name': 'Rhamnus lycioides', 'taxid': '72169', 'code': '20251006110541985242010'}
{'species_name': 'Astragalus sesameus', 'taxid': '2014722', 'code': '20251006110542533764051'}
{'species_name': 'Borago officinalis', 'taxid': '13363', 'code': '20251006110543024164022'}

               Host_taxon    taxid                     code
0           Amaranthus sp  3076757  20251006110439666773010
1    Convolvulus arvensis     4123  20251006110440201955043
2            Cucumis melo     3656  20251006110440754997052
3          Cyperus longus    76433  20251006110441254052093
4    Artemisia herba alba     <NA>  20251006110441672270075
..                    ...      ...                      ...
114   Lithodora fruticosa   475890  20251006110540840025049
115      Origanum vulgare    39352  20251006110541477751038
116     Rhamnus lycioides    72169  20251006110541985242010
117   Astragalus sesameus  2014722  20251006110542533764051
118    Borago officinalis    13363  20251006110543024164022

[119 rows x 3 columns]

In [56]:
hosts_library = pd.merge(hosts, libraries, on=['Host_taxon']).drop_duplicates(['code', 'Library_code'], keep='first')[['code', 'Library_code']].to_dict(orient='records')
hosts_library

[{'code': '20251006110439666773010', 'Library_code': 'PV001'},
 {'code': '20251006110439666773010', 'Library_code': 'PV033'},
 {'code': '20251006110439666773010', 'Library_code': 'PV175'},
 {'code': '20251006110439666773010', 'Library_code': 'PV196'},
 {'code': '20251006110439666773010', 'Library_code': 'PV212'},
 {'code': '20251006110440201955043', 'Library_code': 'PV002'},
 {'code': '20251006110440201955043', 'Library_code': 'PV031'},
 {'code': '20251006110440201955043', 'Library_code': 'PV079'},
 {'code': '20251006110440201955043', 'Library_code': 'PV097'},
 {'code': '20251006110440201955043', 'Library_code': 'PV132'},
 {'code': '20251006110440201955043', 'Library_code': 'PV142'},
 {'code': '20251006110440201955043', 'Library_code': 'PV154'},
 {'code': '20251006110440201955043', 'Library_code': 'PV161'},
 {'code': '20251006110440201955043', 'Library_code': 'PV188'},
 {'code': '20251006110440201955043', 'Library_code': 'PV201'},
 {'code': '20251006110440201955043', 'Library_code': 'PV214'},
 {'code': '20251006110440201955043', 'Library_code': 'PV226'},
 {'code': '20251006110440201955043', 'Library_code': 'PV496'},
 {'code': '20251006110440201955043', 'Library_code': 'PV527'},
 {'code': '20251006110440754997052', 'Library_code': 'PV003'},
 {'code': '20251006110440754997052', 'Library_code': 'PV003bgi'},
 {'code': '20251006110440754997052', 'Library_code': 'PV015bgi'},
 {'code': '20251006110440754997052', 'Library_code': 'PV016'},
 {'code': '20251006110440754997052', 'Library_code': 'PV018bgi'},
 {'code': '20251006110440754997052', 'Library_code': 'PV021bgi'},
 {'code': '20251006110440754997052', 'Library_code': 'PV061'},
 {'code': '20251006110440754997052', 'Library_code': 'PV062'},
 {'code': '20251006110440754997052', 'Library_code': 'PV063'},
 {'code': '20251006110441254052093', 'Library_code': 'PV004bgi'},
 {'code': '20251006110441672270075', 'Library_code': 'PV005bgi'},
 {'code': '20251006110441672270075', 'Library_code': 'PV006bgi'},
 {'code': '20251006110441672270075', 'Library_code': 'PV064'},
 {'code': '20251006110442177792043', 'Library_code': 'PV007bgi'},
 {'code': '20251006110442177792043', 'Library_code': 'PV083'},
 {'code': '20251006110442177792043', 'Library_code': 'PV111'},
 {'code': '20251006110442177792043', 'Library_code': 'PV369'},
 {'code': '20251006110442545729047', 'Library_code': 'PV008bgi'},
 {'code': '20251006110442545729047', 'Library_code': 'PV093'},
 {'code': '20251006110443041873018', 'Library_code': 'PV009'},
 {'code': '20251006110443041873018', 'Library_code': 'PV009bgi'},
 {'code': '20251006110443041873018', 'Library_code': 'PV035'},
 {'code': '20251006110443041873018', 'Library_code': 'PV042'},
 {'code': '20251006110443041873018', 'Library_code': 'PV107'},
 {'code': '20251006110443582725004', 'Library_code': 'PV010bgi'},
 {'code': '20251006110443582725004', 'Library_code': 'PV036'},
 {'code': '20251006110443582725004', 'Library_code': 'PV108'},
 {'code': '20251006110443948438099', 'Library_code': 'PV011'},
 {'code': '20251006110444445883041', 'Library_code': 'PV012bgi'},
 {'code': '20251006110444445883041', 'Library_code': 'PV131'},
 {'code': '20251006110444445883041', 'Library_code': 'PV160'},
 {'code': '20251006110444445883041', 'Library_code': 'PV167'},
 {'code': '20251006110444445883041', 'Library_code': 'PV178'},
 {'code': '20251006110444445883041', 'Library_code': 'PV200'},
 {'code': '20251006110444947084078', 'Library_code': 'PV013bgi'},
 {'code': '20251006110444947084078', 'Library_code': 'PV185'},
 {'code': '20251006110444947084078', 'Library_code': 'PV211'},
 {'code': '20251006110445458077095', 'Library_code': 'PV014'},
 {'code': '20251006110445458077095', 'Library_code': 'PV049'},
 {'code': '20251006110445458077095', 'Library_code': 'PV217'},
 {'code': '20251006110445955428019', 'Library_code': 'PV017bgi'},
 {'code': '20251006110445955428019', 'Library_code': 'PV020bgi'},
 {'code': '20251006110445955428019', 'Library_code': 'PV081'},
 {'code': '20251006110446481915055', 'Library_code': 'PV022'},
 {'code': '20251006110446481915055', 'Library_code': 'PV072'},
 {'code': '20251006110446481915055', 'Library_code': 'PV075'},
 {'code': '20251006110446996002023', 'Library_code': 'PV023'},
 {'code': '20251006110446996002023', 'Library_code': 'PV068'},
 {'code': '20251006110446996002023', 'Library_code': 'PV074'},
 {'code': '20251006110446996002023', 'Library_code': 'PV120'},
 {'code': '20251006110446996002023', 'Library_code': 'PV441'},
 {'code': '20251006110447510093027', 'Library_code': 'PV024'},
 {'code': '20251006110447510093027', 'Library_code': 'PV076'},
 {'code': '20251006110447510093027', 'Library_code': 'PV086'},
 {'code': '20251006110448009546051', 'Library_code': 'PV025'},
 {'code': '20251006110448009546051', 'Library_code': 'PV189'},
 {'code': '20251006110448009546051', 'Library_code': 'PV205'},
 {'code': '20251006110448009546051', 'Library_code': 'PV437'},
 {'code': '20251006110448506830096', 'Library_code': 'PV026'},
 {'code': '20251006110449027777049', 'Library_code': 'PV027'},
 {'code': '20251006110450227677064', 'Library_code': 'PV028'},
 {'code': '20251006110450227677064', 'Library_code': 'PV139'},
 {'code': '20251006110450227677064', 'Library_code': 'PV158'},
 {'code': '20251006110450227677064', 'Library_code': 'PV173'},
 {'code': '20251006110450227677064', 'Library_code': 'PV190'},
 {'code': '20251006110450227677064', 'Library_code': 'PV208'},
 {'code': '20251006110450227677064', 'Library_code': 'PV252'},
 {'code': '20251006110450227677064', 'Library_code': 'PV464'},
 {'code': '20251006110450227677064', 'Library_code': 'PV498'},
 {'code': '20251006110450587403001', 'Library_code': 'PV029'},
 {'code': '20251006110450587403001', 'Library_code': 'PV098'},
 {'code': '20251006110450587403001', 'Library_code': 'PV122'},
 {'code': '20251006110450587403001', 'Library_code': 'PV172'},
 {'code': '20251006110450587403001', 'Library_code': 'PV183'},
 {'code': '20251006110450587403001', 'Library_code': 'PV195'},
 {'code': '20251006110450587403001', 'Library_code': 'PV207'},
 {'code': '20251006110450587403001', 'Library_code': 'PV516'},
 {'code': '20251006110450587403001', 'Library_code': 'PV529'},
 {'code': '20251006110450587403001', 'Library_code': 'PV540'},
 {'code': '20251006110451127962004', 'Library_code': 'PV030'},
 {'code': '20251006110451127962004', 'Library_code': 'PV096'},
 {'code': '20251006110451864110095', 'Library_code': 'PV032'},
 {'code': '20251006110451864110095', 'Library_code': 'PV034'},
 {'code': '20251006110451864110095', 'Library_code': 'PV198'},
 {'code': '20251006110452407095018', 'Library_code': 'PV037'},
 {'code': '20251006110452407095018', 'Library_code': 'PV101'},
 {'code': '20251006110452407095018', 'Library_code': 'PV270'},
 {'code': '20251006110452786960045', 'Library_code': 'PV041'},
 {'code': '20251006110453154321006', 'Library_code': 'PV046'},
 {'code': '20251006110453154321006', 'Library_code': 'PV066'},
 {'code': '20251006110453154321006', 'Library_code': 'PV113'},
 {'code': '20251006110453154321006', 'Library_code': 'PV130'},
 {'code': '20251006110453154321006', 'Library_code': 'PV153'},
 {'code': '20251006110453154321006', 'Library_code': 'PV159'},
 {'code': '20251006110453154321006', 'Library_code': 'PV166'},
 {'code': '20251006110453154321006', 'Library_code': 'PV199'},
 {'code': '20251006110453154321006', 'Library_code': 'PV213'},
 {'code': '20251006110453694838062', 'Library_code': 'PV047'},
 {'code': '20251006110453694838062', 'Library_code': 'PV590'},
 {'code': '20251006110454097988095', 'Library_code': 'PV048'},
 {'code': '20251006110454097988095', 'Library_code': 'PV228'},
 {'code': '20251006110454097988095', 'Library_code': 'PV519'},
 {'code': '20251006110454622715038', 'Library_code': 'PV050'},
 {'code': '20251006110455184662089', 'Library_code': 'PV051'},
 {'code': '20251006110455757031073', 'Library_code': 'PV052'},
 {'code': '20251006110455757031073', 'Library_code': 'PV053'},
 {'code': '20251006110456261636041', 'Library_code': 'PV054'},
 {'code': '20251006110456261636041', 'Library_code': 'PV055'},
 {'code': '20251006110456775660072', 'Library_code': 'PV056'},
 {'code': '20251006110457324128037', 'Library_code': 'PV057'},
 {'code': '20251006110457839895014', 'Library_code': 'PV058'},
 {'code': '20251006110457839895014', 'Library_code': 'PV128'},
 {'code': '20251006110457839895014', 'Library_code': 'PV224'},
 {'code': '20251006110458370851097', 'Library_code': 'PV059'},
 {'code': '20251006110458866158097', 'Library_code': 'PV060'},
 {'code': '20251006110458866158097', 'Library_code': 'PV109'},
 {'code': '20251006110459755442031', 'Library_code': 'PV065'},
 {'code': '20251006110459755442031', 'Library_code': 'PV117'},
 {'code': '20251006110459755442031', 'Library_code': 'PV143'},
 {'code': '20251006110459755442031', 'Library_code': 'PV181'},
 {'code': '20251006110459755442031', 'Library_code': 'PV204'},
 {'code': '20251006110459755442031', 'Library_code': 'PV219'},
 {'code': '20251006110459755442031', 'Library_code': 'PV229'},
 {'code': '20251006110459755442031', 'Library_code': 'PV514'},
 {'code': '20251006110459755442031', 'Library_code': 'PV525'},
 {'code': '20251006110459755442031', 'Library_code': 'PV534'},
 {'code': '20251006110459755442031', 'Library_code': 'PV551'},
 {'code': '20251006110500317997052', 'Library_code': 'PV069'},
 {'code': '20251006110500859490025', 'Library_code': 'PV070'},
 {'code': '20251006110500859490025', 'Library_code': 'PV134'},
 {'code': '20251006110501360223001', 'Library_code': 'PV071'},
 {'code': '20251006110502014336081', 'Library_code': 'PV078'},
 {'code': '20251006110502014336081', 'Library_code': 'PV115'},
 {'code': '20251006110502014336081', 'Library_code': 'PV129'},
 {'code': '20251006110502014336081', 'Library_code': 'PV141'},
 {'code': '20251006110502014336081', 'Library_code': 'PV423'},
 {'code': '20251006110502014336081', 'Library_code': 'PV501'},
 {'code': '20251006110502525060046', 'Library_code': 'PV080'},
 {'code': '20251006110503050858029', 'Library_code': 'PV082'},
 {'code': '20251006110503050858029', 'Library_code': 'PV089'},
 {'code': '20251006110503724455094', 'Library_code': 'PV084'},
 {'code': '20251006110503724455094', 'Library_code': 'PV298'},
 {'code': '20251006110504220677042', 'Library_code': 'PV085'},
 {'code': '20251006110504712267077', 'Library_code': 'PV087'},
 {'code': '20251006110504712267077', 'Library_code': 'PV230'},
 {'code': '20251006110505237278066', 'Library_code': 'PV088'},
 {'code': '20251006110505747758004', 'Library_code': 'PV090'},
 {'code': '20251006110505747758004', 'Library_code': 'PV104'},
 {'code': '20251006110505747758004', 'Library_code': 'PV380'},
 {'code': '20251006110506280389084', 'Library_code': 'PV091'},
 {'code': '20251006110506280389084', 'Library_code': 'PV105'},
 {'code': '20251006110506280389084', 'Library_code': 'PV169'},
 {'code': '20251006110506280389084', 'Library_code': 'PV193'},
 {'code': '20251006110506280389084', 'Library_code': 'PV262'},
 {'code': '20251006110506796344069', 'Library_code': 'PV092'},
 {'code': '20251006110506796344069', 'Library_code': 'PV099'},
 {'code': '20251006110506796344069', 'Library_code': 'PV165'},
 {'code': '20251006110506796344069', 'Library_code': 'PV192'},
 {'code': '20251006110507305375033', 'Library_code': 'PV094'},
 {'code': '20251006110507815148001', 'Library_code': 'PV095'},
 {'code': '20251006110508312702064', 'Library_code': 'PV100'},
 {'code': '20251006110508868184063', 'Library_code': 'PV102'},
 {'code': '20251006110509410461037', 'Library_code': 'PV103'},
 {'code': '20251006110509410461037', 'Library_code': 'PV312'},
 {'code': '20251006110509952853065', 'Library_code': 'PV106'},
 {'code': '20251006110510459140049', 'Library_code': 'PV110'},
 {'code': '20251006110510824342008', 'Library_code': 'PV112'},
 {'code': '20251006110510824342008', 'Library_code': 'PV313'},
 {'code': '20251006110511332646088', 'Library_code': 'PV114'},
 {'code': '20251006110511696704080', 'Library_code': 'PV116'},
 {'code': '20251006110511696704080', 'Library_code': 'PV218'},
 {'code': '20251006110511696704080', 'Library_code': 'PV227'},
 {'code': '20251006110512217915033', 'Library_code': 'PV118'},
 {'code': '20251006110512765568082', 'Library_code': 'PV119'},
 {'code': '20251006110512765568082', 'Library_code': 'PV136'},
 {'code': '20251006110512765568082', 'Library_code': 'PV170'},
 {'code': '20251006110512765568082', 'Library_code': 'PV182'},
 {'code': '20251006110512765568082', 'Library_code': 'PV206'},
 {'code': '20251006110512765568082', 'Library_code': 'PV221'},
 {'code': '20251006110513282788051', 'Library_code': 'PV121'},
 {'code': '20251006110513282788051', 'Library_code': 'PV145'},
 {'code': '20251006110513282788051', 'Library_code': 'PV157'},
 {'code': '20251006110513282788051', 'Library_code': 'PV231'},
 {'code': '20251006110513987987068', 'Library_code': 'PV123'},
 {'code': '20251006110513987987068', 'Library_code': 'PV209'},
 {'code': '20251006110513987987068', 'Library_code': 'PV234'},
 {'code': '20251006110513987987068', 'Library_code': 'PV553'},
 {'code': '20251006110513987987068', 'Library_code': 'PV567'},
 {'code': '20251006110513987987068', 'Library_code': 'PV568'},
 {'code': '20251006110514491548092', 'Library_code': 'PV124'},
 {'code': '20251006110514491548092', 'Library_code': 'PV146'},
 {'code': '20251006110514491548092', 'Library_code': 'PV222'},
 {'code': '20251006110514989151043', 'Library_code': 'PV125'},
 {'code': '20251006110515593783087', 'Library_code': 'PV126'},
 {'code': '20251006110515593783087', 'Library_code': 'PV140'},
 {'code': '20251006110515593783087', 'Library_code': 'PV149'},
 {'code': '20251006110515593783087', 'Library_code': 'PV174'},
 {'code': '20251006110515593783087', 'Library_code': 'PV184'},
 {'code': '20251006110515593783087', 'Library_code': 'PV223'},
 {'code': '20251006110515593783087', 'Library_code': 'PV235'},
 {'code': '20251006110515593783087', 'Library_code': 'PV569'},
 {'code': '20251006110516101271098', 'Library_code': 'PV127'},
 {'code': '20251006110516461585018', 'Library_code': 'PV133'},
 {'code': '20251006110517299675084', 'Library_code': 'PV135'},
 {'code': '20251006110517299675084', 'Library_code': 'PV144'},
 {'code': '20251006110517299675084', 'Library_code': 'PV155'},
 {'code': '20251006110517299675084', 'Library_code': 'PV586'},
 {'code': '20251006110517859634059', 'Library_code': 'PV137'},
 {'code': '20251006110517859634059', 'Library_code': 'PV163'},
 {'code': '20251006110517859634059', 'Library_code': 'PV171'},
 {'code': '20251006110517859634059', 'Library_code': 'PV232'},
 {'code': '20251006110518343641047', 'Library_code': 'PV138'},
 {'code': '20251006110518919163077', 'Library_code': 'PV147'},
 {'code': '20251006110518919163077', 'Library_code': 'PV194'},
 {'code': '20251006110518919163077', 'Library_code': 'PV386'},
 {'code': '20251006110518919163077', 'Library_code': 'PV430'},
 {'code': '20251006110519302849037', 'Library_code': 'PV148'},
 {'code': '20251006110519849752100', 'Library_code': 'PV150'},
 {'code': '20251006110519849752100', 'Library_code': 'PV197'},
 {'code': '20251006110520358356010', 'Library_code': 'PV151'},
 {'code': '20251006110520358356010', 'Library_code': 'PV418'},
 {'code': '20251006110520864311042', 'Library_code': 'PV152'},
 {'code': '20251006110520864311042', 'Library_code': 'PV187'},
 {'code': '20251006110521358599082', 'Library_code': 'PV156'},
 {'code': '20251006110521358599082', 'Library_code': 'PV587'},
 {'code': '20251006110521889324005', 'Library_code': 'PV162'},
 {'code': '20251006110521889324005', 'Library_code': 'PV168'},
 {'code': '20251006110521889324005', 'Library_code': 'PV179'},
 {'code': '20251006110522390436059', 'Library_code': 'PV164'},
 {'code': '20251006110522390436059', 'Library_code': 'PV186'},
 {'code': '20251006110522958964033', 'Library_code': 'PV176'},
 {'code': '20251006110522958964033', 'Library_code': 'PV277'},
 {'code': '20251006110522958964033', 'Library_code': 'PV495'},
 {'code': '20251006110523465899078', 'Library_code': 'PV177'},
 {'code': '20251006110523966861033', 'Library_code': 'PV180'},
 {'code': '20251006110523966861033', 'Library_code': 'PV203'},
 {'code': '20251006110523966861033', 'Library_code': 'PV210'},
 {'code': '20251006110523966861033', 'Library_code': 'PV216'},
 {'code': '20251006110524472457035', 'Library_code': 'PV191'},
 {'code': '20251006110525117760041', 'Library_code': 'PV202'},
 {'code': '20251006110525117760041', 'Library_code': 'PV215'},
 {'code': '20251006110525651134081', 'Library_code': 'PV220'},
 {'code': '20251006110526142831015', 'Library_code': 'PV225'},
 {'code': '20251006110526655583016', 'Library_code': 'PV233'},
 {'code': '20251006110526655583016', 'Library_code': 'PV526'},
 {'code': '20251006110527192618016', 'Library_code': 'PV236'},
 {'code': '20251006110527748290092', 'Library_code': 'PV237'},
 {'code': '20251006110527748290092', 'Library_code': 'PV350'},
 {'code': '20251006110527748290092', 'Library_code': 'PV426'},
 {'code': '20251006110527748290092', 'Library_code': 'PV557'},
 {'code': '20251006110528113195087', 'Library_code': 'PV257'},
 {'code': '20251006110528113195087', 'Library_code': 'PV500'},
 {'code': '20251006110528661168022', 'Library_code': 'PV268'},
 {'code': '20251006110528661168022', 'Library_code': 'PV544'},
 {'code': '20251006110529186725043', 'Library_code': 'PV269'},
 {'code': '20251006110529186725043', 'Library_code': 'PV560'},
 {'code': '20251006110529907138096', 'Library_code': 'PV296'},
 {'code': '20251006110529907138096', 'Library_code': 'PV559'},
 {'code': '20251006110530462718072', 'Library_code': 'PV306'},
 {'code': '20251006110530462718072', 'Library_code': 'PV421'},
 {'code': '20251006110530959223067', 'Library_code': 'PV330'},
 {'code': '20251006110530959223067', 'Library_code': 'PV558'},
 {'code': '20251006110531494894056', 'Library_code': 'PV352'},
 {'code': '20251006110531494894056', 'Library_code': 'PV473'},
 {'code': '20251006110531861947085', 'Library_code': 'PV356'},
 {'code': '20251006110531861947085', 'Library_code': 'PV428'},
 {'code': '20251006110532372060063', 'Library_code': 'PV359'},
 {'code': '20251006110532372060063', 'Library_code': 'PV457'},
 {'code': '20251006110532964321006', 'Library_code': 'PV390'},
 {'code': '20251006110532964321006', 'Library_code': 'PV440'},
 {'code': '20251006110533574166067', 'Library_code': 'PV454'},
 {'code': '20251006110533574166067', 'Library_code': 'PV546'},
 {'code': '20251006110534079859014', 'Library_code': 'PV489'},
 {'code': '20251006110534079859014', 'Library_code': 'PV491'},
 {'code': '20251006110534079859014', 'Library_code': 'PV503'},
 {'code': '20251006110534079859014', 'Library_code': 'PV505'},
 {'code': '20251006110534079859014', 'Library_code': 'PV588'},
 {'code': '20251006110534079859014', 'Library_code': 'PV589'},
 {'code': '20251006110534577115066', 'Library_code': 'PV535'},
 {'code': '20251006110534577115066', 'Library_code': 'PV538'},
 {'code': '20251006110534577115066', 'Library_code': 'PV554'},
 {'code': '20251006110534577115066', 'Library_code': 'PV556'},
 {'code': '20251006110535166564066', 'Library_code': 'PV561'},
 {'code': '20251006110535702130069', 'Library_code': 'PV562'},
 {'code': '20251006110535702130069', 'Library_code': 'PV563'},
 {'code': '20251006110536266288082', 'Library_code': 'PV564'},
 {'code': '20251006110536266288082', 'Library_code': 'PV565'},
 {'code': '20251006110537776009019', 'Library_code': 'PV566'},
 {'code': '20251006110538277934018', 'Library_code': 'PV570'},
 {'code': '20251006110538790594048', 'Library_code': 'PV571'},
 {'code': '20251006110539308450067', 'Library_code': 'PV572'},
 {'code': '20251006110539308450067', 'Library_code': 'PV573'},
 {'code': '20251006110539822899019', 'Library_code': 'PV574'},
 {'code': '20251006110540324616099', 'Library_code': 'PV575'},
 {'code': '20251006110540324616099', 'Library_code': 'PV576'},
 {'code': '20251006110540840025049', 'Library_code': 'PV577'},
 {'code': '20251006110541477751038', 'Library_code': 'PV578'},

In [ ]:
host_library = dict(
    host=hosts.to_dict(orient='records'),
    host_library=hosts_library
)
with open(product['data'], "w") as f:
    json.dump(host_library, f, indent=4, sort_keys=True)