In [9]:
import rdflib
import pandas as pd

In [10]:
data = rdflib.Graph()
data.parse(open("output/mulvirisk.v4.ttl"), format='turtle')

In [11]:
def query_database(query):
    prefixes = """
    PREFIX mvrtaxon: <http://localhost:8000/taxon/>
    PREFIX mvrlib: <http://localhost:8000/library/>
    PREFIX mvront: <http://localhost:8000/ont/>
    PREFIX mvrcol: <http://localhost:8000/collection/>
    PREFIX mvrhost: <http://localhost:8000/host/>
    PREFIX mvrrun: <http://localhost:8000/run/>
    PREFIX mvrsite: <http://localhost:8000/site/>
    PREFIX mvrtaxon: <http://localhost:8000/taxon/>
    PREFIX mvrprt: <http://localhost:8000/protocol/>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    """
    full_query = prefixes + "\n" + query
    query_result = data.query(full_query)
    df = pd.DataFrame(
        [[value.toPython() for value in row] for row in query_result],
        columns=[str(var) for var in query_result.vars]
    )
    return df

In [12]:
query_database(
    """
    SELECT (COUNT(?hit) AS ?nhits)
    WHERE {
        ?hit a mvront:Hit
    }
    """
)

   nhits
0   3120

In [13]:
query_database(
    """
    SELECT ?run ?hit
    WHERE {
        
        ?run mvront:Predicts ?hit .
        ?run a mvront:DetectionRun .
        ?run mvront:Protocol 'MOTUSG1' .
    }
    """
)

,run,hit
0,http://localhost:8000/run/PV001_0001,http://localhost:8000/hit/20251006152613395628037
1,http://localhost:8000/run/PV002_0001,http://localhost:8000/hit/20251006152613398694024
2,http://localhost:8000/run/PV002_0001,http://localhost:8000/hit/20251006152613398841085
3,http://localhost:8000/run/PV002_0001,http://localhost:8000/hit/20251006152613399042058
4,http://localhost:8000/run/PV003_0001,http://localhost:8000/hit/20251006152613402520030
...,...,...
1494,http://localhost:8000/run/PV587_0001,http://localhost:8000/hit/20251006152614394735072
1495,http://localhost:8000/run/PV588_0001,http://localhost:8000/hit/20251006152614397024025
1496,http://localhost:8000/run/PV588_0001,http://localhost:8000/hit/20251006152614397207070
1497,http://localhost:8000/run/PV589_0001,http://localhost:8000/hit/20251006152614399508073
1498,http://localhost:8000/run/PV589_0001,http://localhost:8000/hit/20251006152614399646025

In [26]:
query_database(
    """
    SELECT (COUNT(DISTINCT(?taxa)) AS ?ntaxa)
    WHERE {
        
        ?run mvront:Predicts ?hit .
        ?run a mvront:DetectionRun .
        ?run mvront:Protocol 'MOTUSG1' .
        ?hit mvront:OTU ?taxa
    }
    """
)

   ntaxa
0    522

In [32]:
query_database(
    """
    SELECT ?hit ?name ?run
    WHERE {
        
        ?run mvront:Predicts ?hit .
        ?run a mvront:DetectionRun .
        ?run mvront:Protocol 'MOTUSG1' .
        ?hit mvront:OTU ?taxa .
        ?taxa rdfs:label ?name .
        ?taxa mvront:is_pab 'true'
    }
    """
)

,hit,name,run
0,http://localhost:8000/hit/20251006152613406009019,Bradyrhizobium elkanii,http://localhost:8000/run/PV003bgi_0001
1,http://localhost:8000/hit/20251006152613406206078,Stenotrophomonas maltophilia,http://localhost:8000/run/PV003bgi_0001
2,http://localhost:8000/hit/20251006152613409483058,Bradyrhizobium elkanii,http://localhost:8000/run/PV004bgi_0001
3,http://localhost:8000/hit/20251006152613412916032,Bradyrhizobium elkanii,http://localhost:8000/run/PV005bgi_0001
4,http://localhost:8000/hit/20251006152613419053046,Bradyrhizobium elkanii,http://localhost:8000/run/PV007bgi_0001
...,...,...,...
436,http://localhost:8000/hit/20251006152614358876053,Pseudomonas lutea,http://localhost:8000/run/PV572_0001
437,http://localhost:8000/hit/20251006152614368625008,Leuconostoc mesenteroides,http://localhost:8000/run/PV576_0001
438,http://localhost:8000/hit/20251006152614371068039,Methylobacterium sp. Leaf125,http://localhost:8000/run/PV577_0001
439,http://localhost:8000/hit/20251006152614384924018,Duffyella gerundensis,http://localhost:8000/run/PV583_0001
440,http://localhost:8000/hit/20251006152614394593026,Pseudomonas syringae,http://localhost:8000/run/PV587_0001

In [33]:
query_database(
    """
    SELECT (COUNT(DISTINCT(?taxa)) AS ?ntaxa)
    WHERE {
        
        ?run mvront:Predicts ?hit .
        ?run a mvront:DetectionRun .
        ?run mvront:Protocol 'MOTUSG1' .
        ?hit mvront:OTU ?taxa .
        ?taxa mvront:is_pab 'true'
    }
    """
)

   ntaxa
0    126

In [14]:
query_database(
    """
    SELECT ?run ?hit
    WHERE {
        
        ?run mvront:Predicts ?hit .
        ?run a mvront:DetectionRun .
        ?run mvront:Protocol 'BLAST01' .
    }
    """
)

,run,hit
0,http://localhost:8000/run/PV001_0000,http://localhost:8000/hit/20251006152610350676067
1,http://localhost:8000/run/PV001_0000,http://localhost:8000/hit/20251006152610351034000
2,http://localhost:8000/run/PV001_0000,http://localhost:8000/hit/20251006152610357222050
3,http://localhost:8000/run/PV001_0000,http://localhost:8000/hit/20251006152610368055045
4,http://localhost:8000/run/PV002_0000,http://localhost:8000/hit/20251006152610351059049
...,...,...
1611,http://localhost:8000/run/PV589_0000,http://localhost:8000/hit/20251006152610356682005
1612,http://localhost:8000/run/PV589_0000,http://localhost:8000/hit/20251006152610387454033
1613,http://localhost:8000/run/PV590_0000,http://localhost:8000/hit/20251006152610355990023
1614,http://localhost:8000/run/PV590_0000,http://localhost:8000/hit/20251006152610370895012
1615,http://localhost:8000/run/PV590_0000,http://localhost:8000/hit/20251006152610383401047

In [15]:
query_database(
    """
    SELECT (COUNT(DISTINCT(?taxa)) AS ?ntaxa)
    WHERE {
        ?run mvront:Protocol 'BLAST01' .
        ?run mvront:Predicts ?hit .
        ?run a mvront:DetectionRun .
        ?hit mvront:OTU ?taxa
    }
    """
)

   ntaxa
0    158

In [16]:
query_database(
    """
    SELECT (COUNT(DISTINCT(?taxa)) AS ?ntaxa)
    WHERE {
        ?run mvront:Protocol 'MOTUSG1' .
        ?run mvront:Predicts ?hit .
        ?run a mvront:DetectionRun .
        ?hit mvront:OTU ?taxa
    }
    """
)

   ntaxa
0    522

In [34]:
query_database(
    """
    SELECT (COUNT(DISTINCT(?scientific_name)) AS ?number_host_species)
    WHERE {
        ?lib a mvront:Library .
        ?lib mvront:Host ?host .
        ?host dwc:scientificName ?scientific_name
    }
    """
)

   number_host_species
0                  119

In [35]:
query_database(
    """
    SELECT (COUNT(DISTINCT(?lib)) AS ?nlib)
    WHERE {
        ?lib a mvront:Library .
        
    }
    """
)

   nlib
0   323

In [36]:
query_database(
    """
    SELECT ?lib_label  ?next ?site
    WHERE {
        ?lib a mvront:Library .
        ?lib rdfs:label ?lib_label .
        ?lib mvront:Host ?h .
        
        ?lib mvront:nextracts ?next .
        ?lib mvront:Sampled_from ?s .
        ?s rdfs:label ?site
        
    }
    """
)

    lib_label next site
0       PV001    8   M1
1       PV002   11   M1
2       PV003   13   M1
3    PV003bgi   13   M1
4    PV004bgi    7   M1
..        ...  ...  ...
321     PV586    8   H1
322     PV587    8   H1
323     PV588    8   H1
324     PV589    8   H1
325     PV590   11   Z1

[326 rows x 3 columns]

In [37]:
query_database(
    """
    SELECT ?lib_label ?scientific_name ?next ?site
    WHERE {
        ?lib a mvront:Library .
        ?lib rdfs:label ?lib_label .
        ?lib mvront:Host ?h .
        ?h rdfs:label ?scientific_name .
        ?lib mvront:nextracts ?next .
        ?lib mvront:Sampled_from ?s .
        ?s rdfs:label ?site
        
    }
    """
)

    lib_label       scientific_name next site
0       PV001         Amaranthus sp    8   M1
1       PV002  Convolvulus arvensis   11   M1
2       PV003          Cucumis melo   13   M1
3    PV003bgi          Cucumis melo   13   M1
4    PV004bgi        Cyperus longus    7   M1
..        ...                   ...  ...  ...
321     PV586    Fumaria parviflora    8   H1
322     PV587   Hirschfeldia incana    8   H1
323     PV588       Hordeum vulgare    8   H1
324     PV589       Hordeum vulgare    8   H1
325     PV590              Zea mays   11   Z1

[326 rows x 4 columns]

In [38]:
query_database(
    """
    SELECT ?lib_label ?scientific_name ?next ?site
    WHERE {
        ?lib a mvront:Library .
        ?lib rdfs:label ?lib_label .
        ?lib mvront:Host ?h .
        ?h rdfs:label ?scientific_name .
        ?lib mvront:nextracts ?next .
        ?lib mvront:Sampled_from ?s .
        ?s rdfs:label ?site
        
    }
    """
)

    lib_label       scientific_name next site
0       PV001         Amaranthus sp    8   M1
1       PV002  Convolvulus arvensis   11   M1
2       PV003          Cucumis melo   13   M1
3    PV003bgi          Cucumis melo   13   M1
4    PV004bgi        Cyperus longus    7   M1
..        ...                   ...  ...  ...
321     PV586    Fumaria parviflora    8   H1
322     PV587   Hirschfeldia incana    8   H1
323     PV588       Hordeum vulgare    8   H1
324     PV589       Hordeum vulgare    8   H1
325     PV590              Zea mays   11   Z1

[326 rows x 4 columns]

In [39]:
query_database(
    """
    SELECT ?lib_label ?scientific_name ?next ?site
    WHERE {
        ?lib a mvront:Library .
        ?lib rdfs:label ?lib_label .
        ?lib mvront:Host ?h .
        ?h rdfs:label ?scientific_name .
        ?lib mvront:nextracts ?next .
        ?lib mvront:Sampled_from ?s .
        ?s rdfs:label ?site
        
    }
    """
).value_counts('lib_label')

lib_label
PV578    3
PV570    2
PV001    1
PV222    1
PV229    1
        ..
PV115    1
PV114    1
PV113    1
PV112    1
PV590    1
Name: count, Length: 323, dtype: int64

In [40]:
query_database(
    """
    SELECT ?scientific_name ?next ?site
    WHERE {
        ?lib a mvront:Library .
        ?lib rdfs:label 'PV578' .
        ?lib mvront:Host ?h .
        ?h rdfs:label ?scientific_name .
        ?lib mvront:nextracts ?next .
        ?lib mvront:Sampled_from ?s .
        ?s rdfs:label ?site
        
    }
    """
)

    scientific_name next site
0  Origanum vulgare    4   Q1
1  Origanum vulgare    4   Q2
2  Origanum vulgare    4   Q3

In [41]:
query_database(
    """
    SELECT ?lib_label ?scientific_name ?next ?site
    WHERE {
        ?lib a mvront:Library .
        ?lib rdfs:label ?lib_label .
        ?lib mvront:Host ?h .
        ?h rdfs:label ?scientific_name .
        ?lib mvront:nextracts ?next .
        ?lib mvront:Sampled_from ?s .
        ?s rdfs:label ?site
        
    }
    """
)

    lib_label       scientific_name next site
0       PV001         Amaranthus sp    8   M1
1       PV002  Convolvulus arvensis   11   M1
2       PV003          Cucumis melo   13   M1
3    PV003bgi          Cucumis melo   13   M1
4    PV004bgi        Cyperus longus    7   M1
..        ...                   ...  ...  ...
321     PV586    Fumaria parviflora    8   H1
322     PV587   Hirschfeldia incana    8   H1
323     PV588       Hordeum vulgare    8   H1
324     PV589       Hordeum vulgare    8   H1
325     PV590              Zea mays   11   Z1

[326 rows x 4 columns]

In [42]:
query_database(
    """
    SELECT ?lib_label
    WHERE {
        ?lib a mvront:Library .
        ?lib rdfs:label ?lib_label .

        
    }
    """
)

    lib_label
0       PV001
1       PV002
2       PV003
3    PV003bgi
4    PV004bgi
..        ...
318     PV586
319     PV587
320     PV588
321     PV589
322     PV590

[323 rows x 1 columns]

In [ ]:
query_database(
    """
    SELECT ?hit ?lib_label ?scientific_name ?next ?site
    WHERE {
        ?hit a mvront:Hit .
        ?run a mvront:DetectionRun .
        ?lib mvront:Run ?run .
        ?lib a mvront:Library .
        ?lib rdfs:label ?lib_label .
        ?lib mvront:Host ?h .
        ?h rdfs:label ?scientific_name .
        ?lib mvront:nextracts ?next .
        ?lib mvront:Sampled_from ?s .
        ?s rdfs:label ?site
        
    }
    """
)