# 15/02/2025  - Preparing data

In [1]:
import pandas as pd

In [2]:
reference = pd.read_csv("../data/sanchis2021.sup_file_1.csv", sep=";")#[['Taxid', 'Biosample', 'Representative species', 'PAB-phyto', 'PAB-symb']]

In [3]:
reference

       TaxId     Biosample           Representative species patho symb
0     178901  SAMN02849420              Acetobacter malorum   NaN  NaN
1     441768  SAMN02603756    Acholeplasma laidlawii  PG-8A   NaN  NaN
2      32002  SAMN06198582      Achromobacter denitrificans   NaN  NaN
3     217204  SAMN06174288          Achromobacter insolitus   NaN  NaN
4      72556  SAMN03941583         Achromobacter piechaudii   NaN  NaN
..       ...           ...                              ...   ...  ...
955   698414  SAMN06765826  Xylella fastidiosa subsp. pauca     P  NaN
956  1444770  SAMN02570451              Xylella taiwanensis     P  NaN
957  1735686  SAMN04151686           Xylophilus sp. Leaf220   NaN  NaN
958  1288385  SAMEA1486427              Yersinia pekkanenii   NaN  NaN
959  1123510  SAMN02952986      Zymobacter palmae DSM 10491   NaN  NaN

[960 rows x 5 columns]

In [4]:
pathogens = reference.query('patho == "P"').drop_duplicates(subset='TaxId')
pathogens

       TaxId     Biosample                Representative species patho symb
11     80867  SAMN04009978                     Acidovorax avenae     P  NaN
12    397945  SAMN02598334           Acidovorax citrulli AAC00-1     P  NaN
40    176299  SAMN02603108         Agrobacterium fabrum str. C58     P  NaN
43       359  SAMN02787063              Agrobacterium rhizogenes     P  NaN
46     28099  SAMN04901300                    Agrobacterium rubi     P  NaN
..       ...           ...                                   ...   ...  ...
952   487909  SAMN02797519  Xanthomonas translucens pv. undulosa     P  NaN
953    56459  SAMN03140188                  Xanthomonas vasicola     P  NaN
954    56460  SAMN05823142               Xanthomonas vesicatoria     P  NaN
955   698414  SAMN06765826       Xylella fastidiosa subsp. pauca     P  NaN
956  1444770  SAMN02570451                   Xylella taiwanensis     P  NaN

[103 rows x 5 columns]

In [5]:
with open("../scratch/pathogen_taxid.txt", "w") as f:
    f.write('\n'.join(pathogens['TaxId'].astype(str).values.tolist()))

In [6]:
symbionts = reference.query('symb == "S"').drop_duplicates(subset='TaxId')
symbionts

       TaxId     Biosample                  Representative species patho symb
95    438753  SAMD00060925        Azorhizobium caulinodans ORS 571   NaN    S
96   1038858  SAMN02440776    Azorhizobium doebereinerae UFLA1-100   NaN    S
133   255045  SAMN05444158               Bradyrhizobium canariense   NaN    S
134  1497613  SAMN04448272              Bradyrhizobium centrolobii   NaN    S
135   224911  SAMN03573437  Bradyrhizobium diazoefficiens USDA 110   NaN    S
..       ...           ...                                     ...   ...  ...
837    36856  SAMN04274563                    Sinorhizobium saheli   NaN    S
838  1945861  SAMN06293010                   Sinorhizobium sp. A49   NaN    S
839   794846  SAMN02469491            Sinorhizobium sp. CCBAU 5631   NaN    S
840  1842534  SAMN04909707                 Sinorhizobium sp. RAC02   NaN    S
918   667632  SAMN02441378                    Trinickia symbiotica   NaN    S

[173 rows x 5 columns]

In [7]:
with open("../scratch/symbionts_taxid.txt", "w") as f:
    f.write('\n'.join(symbionts['TaxId'].astype(str).values.tolist()))

In [8]:
reference.query('symb == "S" or patho == "PATO"')

       TaxId     Biosample                  Representative species patho symb
95    438753  SAMD00060925        Azorhizobium caulinodans ORS 571   NaN    S
96   1038858  SAMN02440776    Azorhizobium doebereinerae UFLA1-100   NaN    S
133   255045  SAMN05444158               Bradyrhizobium canariense   NaN    S
134  1497613  SAMN04448272              Bradyrhizobium centrolobii   NaN    S
135   224911  SAMN03573437  Bradyrhizobium diazoefficiens USDA 110   NaN    S
..       ...           ...                                     ...   ...  ...
837    36856  SAMN04274563                    Sinorhizobium saheli   NaN    S
838  1945861  SAMN06293010                   Sinorhizobium sp. A49   NaN    S
839   794846  SAMN02469491            Sinorhizobium sp. CCBAU 5631   NaN    S
840  1842534  SAMN04909707                 Sinorhizobium sp. RAC02   NaN    S
918   667632  SAMN02441378                    Trinickia symbiotica   NaN    S

[192 rows x 5 columns]

In [9]:
with open("../scratch/reference-taxid.txt", "w") as f:
    f.write('\n'.join(reference['TaxId'].astype(str).values.tolist()))