# 2025/03/18 Fairdom seek upload

This notebook updates our previous notebook by uploading to CBGP seek instead of the Fairdom instance in Seek.

In [15]:
import requests
from typing import List, Dict, Any
import pandas as pd
import time

# Define API endpoint and authentication
# CBGP
api_url = "https://seek.admin.cbgp.upm.es"
api_key = "B7qUAvsSVPX2qrlZ11azFveVt-lLhET_sRqzNiNc"
headers = {"Authorization": f"Bearer {api_key}", "Accept": "application/vnd.api+json",
           "Accept-Charset": "ISO-8859-1"}

In [6]:
def add_samples(collection:List[dict], sample_id_field: str, verbose=True):
    """
    Add samples
    ===

    Adds samples from collection. It handles the 500 errors that arise 
    in Seek 1.16, and it provides a table with the latest added records, joining
    their original identifiers with their record id in the Seek server.

    arguments:
    ---

    collection: List
        List of dictionaries containing
    sample_id_field: str
        String to idifentify the sample
    verbose: bool


    """
    out = []
    for i, sample in enumerate(collection):
        sample_id = sample['data']['attributes']['attribute_map'][sample_id_field]
        for _ in range(5):
            r = requests.post(f"{api_url}/samples", headers=headers, json=sample)

            
            if r.status_code == 200:
                break
            elif r.status_code == 500:
                # Important to avoid 500 errors.
                time.sleep(0.5)
            else:
                break


        if r.status_code == 200:
            record = r.json()
            record_id = record['data']['id']
            out.append([sample_id, record_id])
            if verbose:    
                print("sample # {0}, record {1}, added".format(
                    sample_id, 
                    record_id)
                )
        else:
            print("sample # {0}, could not be added, ERROR {1}".format(sample_id, r.status_code))
    return out


def get_all_samples_from_type(sample_type_id:int, verbose:bool=True):
    """
    Get All Samples from Type
    ===

    Seek does not provide a search api for samples. Therefore, the best way to do searches is
    to use this function to fetch all the samples belonging to certain type, and then making data
    queries locally through pandas or similar.

    arguments:
    ---

    sample_type_id: int
        Record id corresponding to the sample type

    verbose: bool


    """
    try:
        samples = requests.get(f"{api_url}/sample_types/{sample_type_id}", headers=headers).json()['data']['relationships']['samples']['data']
    except KeyError:
        raise IOError(f"Is {sample_type_id} defined??")
    
    out_samples = []
    for sample in samples:
        for _ in range(5):
            r = requests.get(f"{api_url}/samples/{sample['id']}", headers=headers)
            if r.status_code == 200:
                break
            elif r.status_code == 500:
                # Important to avoid 500 errors.
                time.sleep(0.5)
            else:
                break
        if r.status_code == 200:
            out_samples.append(r.json())
            if verbose:
                print("sample with id {0}, retrieved ".format(sample['id']))
        elif r.status_code == 500 and verbose:
            print("sample with id {0} could not be retrieved, code{1} ".format(sample['id'], s.status_code))
    return out_samples

##

## Gathering data

To create a fair isa record for our experiment, first we need to have under good control all the experimental information that we will use. The following blocks attempt to process experimental data to get it in the right format.

Tasks:

1. Read RNA library and Field Sample data.
2. Create a Field Sample id for each Field Sample by connecting the site code and the date
3. Extract "Habitat info" from RNA library and add it to Field Sample data.
4. Create a table connecting Libraries with their field samples.

### Task 1. Reading RNA libaries and Field Sample data

No issues here. Just reading XLSX files containing the info. 

**We will use Upper case for the first letter of the field, and lower case for all the others**

In [20]:
field_samples = pd.read_excel("../data/fairdom-seek-mcleish2024/FieldSampling-2025-02-20.xlsx", sheet_name="Samples")
field_samples['Season'] = field_samples['Collection Codes'].apply(lambda x: {"F":"fall", "V":"summer", "P":"spring"}[x[-1]])
field_samples.columns = ["Collection_code", "Site_code", "Date", "Town", "Longitude", "Latitude", "Season"]
field_samples

,Collection_code,Site_code,Date,Town,Longitude,Latitude,Season
0,C1F,C1,2016-02-01,Aranjuez,-3.593308,40.051302,fall
1,C3F,C1,2017-01-30,Aranjuez,-3.593308,40.051302,fall
2,C2F,C2,2016-02-01,Aranjuez,-3.599064,40.043193,fall
3,C4F,C2,2017-01-30,Aranjuez,-3.599064,40.043193,fall
4,E1F,E1,2015-11-19,Aranjuez,-3.500323,40.059138,fall
...,...,...,...,...,...,...,...
73,Q4P,Q4,2017-05-03,Mondéjar,-3.137145,40.345348,spring
74,Z1V,Z1,2015-07-16,Villaconejos,-3.476076,40.050052,summer
75,Z3V,Z1,2016-07-20,Villaconejos,-3.476076,40.050052,summer
76,Z2V,Z2,2015-07-24,Villamanrique de Tajo,-3.131000,40.044720,summer
77,Z4V,Z2,2016-07-15,Villamanrique de Tajo,-3.131000,40.044720,summer

In [19]:
library_samples = pd.read_excel("../data/fairdom-seek-mcleish2024/RNAlibrary-2025-02-20.xlsx", sheet_name="Samples")
library_samples.columns = ["Library_code", "Collection_code", "Species_name", "Habitat", "Number_of_extracts"]
library_samples

,Library_code,Collection_code,Species_name,Habitat,Number_of_extracts
0,PV001,M1V,Amaranthus sp,Crop,8
1,PV002,M1V,Convolvulus arvensis,Crop,11
2,PV003,M1V,Cucumis melo,Crop,13
3,PV003bgi,M1V,Cucumis melo,Crop,13
4,PV004bgi,M1V,Cyperus longus,Crop,7
...,...,...,...,...,...
318,PV586,H1P,Fumaria parviflora,Crop,8
319,PV587,H1P,Hirschfeldia incana,Crop,8
320,PV588,H1P,Hordeum vulgare,Crop,8
321,PV589,H1P,Hordeum vulgare,Crop,8
322,PV590,Z1V,Zea mays,Crop,11

### Task 2. Extracting habitat info

In [26]:
habitat_type = library_samples[['Collection_code', 'Habitat']].drop_duplicates(keep='first').sort_values(by='Collection_code')
habitat_type = habitat_type.reset_index()[['Collection_code', 'Habitat']]
field_samples = pd.merge(field_samples, habitat_type, how='left', left_on=['Collection_code'], right_on=['Collection_code'])
field_samples['Habitat'] = field_samples['Habitat'].fillna("null")
field_samples

,Collection_code,Site_code,Date,Town,Longitude,Latitude,Season,Sample code,Habitat
0,C1F,C1,2016-02-01,Aranjuez,-3.593308,40.051302,fall,C1-01/02/2016,Crop
1,C3F,C1,2017-01-30,Aranjuez,-3.593308,40.051302,fall,C1-30/01/2017,null
2,C2F,C2,2016-02-01,Aranjuez,-3.599064,40.043193,fall,C2-01/02/2016,Crop
3,C4F,C2,2017-01-30,Aranjuez,-3.599064,40.043193,fall,C2-30/01/2017,null
4,E1F,E1,2015-11-19,Aranjuez,-3.500323,40.059138,fall,E1-19/11/2015,Wasteland
...,...,...,...,...,...,...,...,...,...
73,Q4P,Q4,2017-05-03,Mondéjar,-3.137145,40.345348,spring,Q4-03/05/2017,Oak
74,Z1V,Z1,2015-07-16,Villaconejos,-3.476076,40.050052,summer,Z1-16/07/2015,Crop
75,Z3V,Z1,2016-07-20,Villaconejos,-3.476076,40.050052,summer,Z1-20/07/2016,null
76,Z2V,Z2,2015-07-24,Villamanrique de Tajo,-3.131000,40.044720,summer,Z2-24/07/2015,Crop
77,Z4V,Z2,2016-07-15,Villamanrique de Tajo,-3.131000,40.044720,summer,Z2-15/07/2016,null

### Task 3. Creating an index for field samples

In [28]:
field_samples['Sample code'] = field_samples.apply(lambda x: x['Site_code'] + '-' + x['Date'].strftime('%d/%m/%Y'), axis=1)
field_samples[['Sample code', 'Site_code', 'Town', 'Longitude', 'Latitude', 'Habitat', 'Date', 'Season']]

,Sample code,Site_code,Town,Longitude,Latitude,Habitat,Date,Season
0,C1-01/02/2016,C1,Aranjuez,-3.593308,40.051302,Crop,2016-02-01,fall
1,C1-30/01/2017,C1,Aranjuez,-3.593308,40.051302,null,2017-01-30,fall
2,C2-01/02/2016,C2,Aranjuez,-3.599064,40.043193,Crop,2016-02-01,fall
3,C2-30/01/2017,C2,Aranjuez,-3.599064,40.043193,null,2017-01-30,fall
4,E1-19/11/2015,E1,Aranjuez,-3.500323,40.059138,Wasteland,2015-11-19,fall
...,...,...,...,...,...,...,...,...
73,Q4-03/05/2017,Q4,Mondéjar,-3.137145,40.345348,Oak,2017-05-03,spring
74,Z1-16/07/2015,Z1,Villaconejos,-3.476076,40.050052,Crop,2015-07-16,summer
75,Z1-20/07/2016,Z1,Villaconejos,-3.476076,40.050052,null,2016-07-20,summer
76,Z2-24/07/2015,Z2,Villamanrique de Tajo,-3.131000,40.044720,Crop,2015-07-24,summer
77,Z2-15/07/2016,Z2,Villamanrique de Tajo,-3.131000,40.044720,null,2016-07-15,summer

### Task 4. Connecting Field samples and habitats

In [ ]:
collection_code_column = pd.merge(
    library_samples[['Collection_code', 'Library_code']], 
    field_samples[['Collection_code', 'Sample_code']], on=['Collection_code']
).groupby('Library_code', as_index=True)['Sample_code'].apply(list).reset_index()# .rename(columns={'Sample code':'Field samples'})
library_samples = pd.merge(
    library_samples, collection_code_column, on=['Library_code']
)
library_samples

,Library_code,Collection_code,Species_name,Habitat,Number_of_extracts,Sample_code
0,PV001,M1V,Amaranthus sp,Crop,8,[M1-16/07/2015]
1,PV002,M1V,Convolvulus arvensis,Crop,11,[M1-16/07/2015]
2,PV003,M1V,Cucumis melo,Crop,13,[M1-16/07/2015]
3,PV003bgi,M1V,Cucumis melo,Crop,13,[M1-16/07/2015]
4,PV004bgi,M1V,Cyperus longus,Crop,7,[M1-16/07/2015]
...,...,...,...,...,...,...
308,PV586,H1P,Fumaria parviflora,Crop,8,[H1-21/04/2016]
309,PV587,H1P,Hirschfeldia incana,Crop,8,[H1-21/04/2016]
310,PV588,H1P,Hordeum vulgare,Crop,8,[H1-21/04/2016]
311,PV589,H1P,Hordeum vulgare,Crop,8,[H1-21/04/2016]
312,PV590,Z1V,Zea mays,Crop,11,[Z1-16/07/2015]

In [13]:
library_samples.query('Collection_code == "E1P"')

,Library_code,Collection_code,Species_name,Habitat,Number_of_extracts,Sample_code
235,PV277,E1P,Anacyclus clavatus,Wasteland,5,"[E1-23/05/2016, E1-03/05/2017]"
236,PV296,E1P,Stipa parviflora,Wasteland,6,"[E1-23/05/2016, E1-03/05/2017]"
237,PV298,E1P,Teucrium capitatum,Wasteland,15,"[E1-23/05/2016, E1-03/05/2017]"
297,PV572,E1P,Trifolium tomentosum,Wasteland,3,"[E1-23/05/2016, E1-03/05/2017]"
305,PV583,E1P,Astragalus sesameus,Wasteland,6,"[E1-23/05/2016, E1-03/05/2017]"

## Uploading samples

We will proceed iteratively to upload forward-linked samples. Ideally, we would like this process to take place in a single run. However, this is not usually the case, as the Seek interface is pretty slow. 

Therefore, we will always proceed as: post instances, fetch identifiers, use those identifiers in the next post.

Tasks:

1. Posting field sample records.
2. Posting library records.
3. Posting extracts.
4. Posting raw reads

### Useful code

We will create each of the sample records by composing a function that it's specific of each sample type, and a function that works with all sample types.

In [29]:
def create_record(attributes_dict: Dict[str, Any], project_id, people_id, sample_type_id, assay_id):
    data = {
        'data':{
            "type": "samples",
            "attributes": attributes_dict,
            "relationships": {
                "sample_type": {"data": {"id": sample_type_id,"type": "sample_types"}},
                "creators": {"data": [{"id": people_id, "type": "people"}]},
                "projects": {"data": [{"id": project_id, "type": "projects"}]},
                "assays": {"data": [{"id": assay_id, "type": "assays"}]}
            }
        }   
    }
    return data

### Task 1. Posting "Field sample" records

In [58]:
def create_field_attributes(entry: Dict[str, Any], project_id: str, people_id: str, sample_type_id: str, assay_id: str):
    attributes = {
        
        "attribute_map": {
            "Sample code": entry['Sample_code'],
            "Location code": entry['Site_code'],
            "Town": entry['Town'],
            "Longitude": entry['Longitude'],
            "Latitude": entry['Latitude'],
            "Habitat": entry['Habitat'],
            "Date": entry['Date'].strftime('%d/%m/%Y'),
            "Season": entry['Season']
        },
        "tags": [
            entry['Habitat'],
            entry['Season'], 
            "field sample"
        ]
    }    
    
    record = create_record(
        attributes_dict=attributes, project_id=project_id, people_id=people_id,
        sample_type_id=sample_type_id, assay_id=assay_id
    )
    return record

In [59]:
# IMPORTANT TO CHECK THESE ONES BEFORE UPLOAD
people_id = '1'
project_id = '2'
assay_id = '1' # Check these ones carefully
sample_type_id = '1'

create_field_attributes_ = lambda x: create_field_attributes(
    x, 
    project_id=project_id, people_id=people_id, 
    sample_type_id=sample_type_id, assay_id=assay_id
)
field_sample_records = list(map(
    create_field_attributes_, field_samples.to_dict(orient='records'))
)
field_sample_records[0]

{'data': {'type': 'samples',
  'attributes': {'attribute_map': {'Sample code': 'C1-01/02/2016',
    'Location code': 'C1',
    'Town': 'Aranjuez',
    'Longitude': -3.593308,
    'Latitude': 40.051302,
    'Habitat': 'Crop',
    'Date': '01/02/2016',
    'Season': 'fall'},
   'tags': ['Crop', 'fall', 'field sample']},
  'relationships': {'sample_type': {'data': {'id': '1',
     'type': 'sample_types'}},
   'creators': {'data': [{'id': '1', 'type': 'people'}]},
   'projects': {'data': [{'id': '2', 'type': 'projects'}]},
   'assays': {'data': [{'id': '1', 'type': 'assays'}]}}}}

In [62]:
field_sample_records = add_samples(field_sample_records, "Sample code")

sample # C1-01/02/2016, record 1, added
sample # C1-30/01/2017, record 2, added
sample # C2-01/02/2016, record 3, added
sample # C2-30/01/2017, record 4, added
sample # E1-19/11/2015, record 5, added
sample # E1-10/11/2016, record 6, added
sample # E1-23/05/2016, record 7, added
sample # E1-03/05/2017, record 8, added
sample # E2-19/11/2015, record 9, added
sample # E2-10/11/2016, record 10, added
sample # E2-23/05/2016, record 11, added
sample # E2-10/05/2017, record 12, added
sample # E3-01/02/2016, record 13, added
sample # E3-10/11/2016, record 14, added
sample # E3-31/05/2016, record 15, added
sample # E3-03/05/2017, record 16, added
sample # E4-04/11/2015, record 17, added
sample # E4-27/10/2016, record 18, added
sample # E4-31/05/2016, record 19, added
sample # E4-03/05/2017, record 20, added
sample # H1-21/04/2016, record 21, added
sample # H1-19/04/2017, record 22, added
sample # H2-21/04/2016, record 23, added
sample # H2-19/04/2017, record 24, added
sample # H3-21/04/2016, record 25, added
sample # H3-19/04/2017, record 26, added
sample # L1-19/11/2015, record 27, added
sample # L1-10/11/2016, record 28, added
sample # L1-31/03/2016, record 29, added
sample # L1-19/04/2017, record 30, added
sample # L1-16/07/2015, record 31, added
sample # L1-20/07/2016, record 32, added
sample # L2-19/11/2015, record 33, added
sample # L2-10/11/2016, record 34, added
sample # L2-31/03/2016, record 35, added
sample # L2-16/07/2015, record 36, added
sample # L2-20/07/2016, record 37, added
sample # L3-19/11/2015, record 38, added
sample # L3-10/11/2016, record 39, added
sample # L3-31/03/2016, record 40, added
sample # L3-19/04/2017, record 41, added
sample # L3-24/07/2015, record 42, added
sample # L3-15/07/2016, record 43, added
sample # L4-04/11/2015, record 44, added
sample # L4-27/10/2016, record 45, added
sample # L4-21/04/2016, record 46, added
sample # L4-16/04/2017, record 47, added
sample # L4-15/07/2016, record 48, added
sample # M1-16/07/2015, record 49, added
sample # M1-20/07/2016, record 50, added
sample # M1-28/06/2017, record 51, added
sample # M2-16/07/2015, record 52, added
sample # M3-28/06/2017, record 53, added
sample # M3-24/07/2015, record 54, added
sample # M3-15/07/2016, record 55, added
sample # M4-28/06/2017, record 56, added
sample # M4-24/07/2015, record 57, added
sample # M4-15/07/2016, record 58, added
sample # Q1-08/09/2015, record 59, added
sample # Q1-12/09/2016, record 60, added
sample # Q1-23/05/2016, record 61, added
sample # Q1-10/05/2017, record 62, added
sample # Q2-21/09/2015, record 63, added
sample # Q2-20/10/2016, record 64, added
sample # Q2-23/05/2016, record 65, added
sample # Q2-10/05/2017, record 66, added
sample # Q3-21/09/2015, record 67, added
sample # Q3-27/10/2016, record 68, added
sample # Q3-31/05/2016, record 69, added
sample # Q3-03/05/2017, record 70, added
sample # Q4-21/09/2015, record 71, added
sample # Q4-27/10/2016, record 72, added
sample # Q4-31/05/2016, record 73, added
sample # Q4-03/05/2017, record 74, added
sample # Z1-16/07/2015, record 75, added
sample # Z1-20/07/2016, record 76, added
sample # Z2-24/07/2015, record 77, added
sample # Z2-15/07/2016, record 78, added

In [30]:
field_sample_records = get_all_samples_from_type('1', verbose=False)
field_sample_records = [dict(record_id=item['data']['id'], sample_id=item['data']['attributes']['attribute_map']['Sample code']) for item in field_sample_records]

In [31]:
field_sample_records = pd.DataFrame.from_records(field_sample_records)
field_sample_records

   record_id      sample_id
0        507  C1-01/02/2016
1        508  C1-30/01/2017
2        509  C2-01/02/2016
3        510  C2-30/01/2017
4        511  E1-19/11/2015
..       ...            ...
73       580  Q4-03/05/2017
74       581  Z1-16/07/2015
75       582  Z1-20/07/2016
76       583  Z2-24/07/2015
77       584  Z2-15/07/2016

[78 rows x 2 columns]

## Task 2. Create RNA extracts

In [32]:
field_sample_records['Extract code'] = field_sample_records['sample_id'].apply(lambda x: f'RNA-{x}')
field_sample_records

   record_id      sample_id       Extract code
0        507  C1-01/02/2016  RNA-C1-01/02/2016
1        508  C1-30/01/2017  RNA-C1-30/01/2017
2        509  C2-01/02/2016  RNA-C2-01/02/2016
3        510  C2-30/01/2017  RNA-C2-30/01/2017
4        511  E1-19/11/2015  RNA-E1-19/11/2015
..       ...            ...                ...
73       580  Q4-03/05/2017  RNA-Q4-03/05/2017
74       581  Z1-16/07/2015  RNA-Z1-16/07/2015
75       582  Z1-20/07/2016  RNA-Z1-20/07/2016
76       583  Z2-24/07/2015  RNA-Z2-24/07/2015
77       584  Z2-15/07/2016  RNA-Z2-15/07/2016

[78 rows x 3 columns]

In [33]:
def create_rna_extract_record(entry: Dict[str, Any], project_id: str, people_id: str, sample_type_id: str, assay_id: str):
    attributes = {
        
        "attribute_map": {
            "RNA extract code": entry["Extract code"],
            "Field sample": entry["record_id"],
        },
        "tags": []
    }    
    
    record = create_record(
        attributes_dict=attributes, project_id=project_id, people_id=people_id,
        sample_type_id=sample_type_id, assay_id=assay_id
    )
    return record


# IMPORTANT TO CHECK THESE ONES BEFORE UPLOAD
people_id = '1'
project_id = '2'
assay_id = '2' # Check these ones carefully
sample_type_id = '5'

create_rna_extract_record_ = lambda x: create_rna_extract_record(
    x,people_id=people_id, project_id=project_id, assay_id=assay_id, sample_type_id=sample_type_id
)

In [34]:
extract_records = list(map(create_rna_extract_record_, field_sample_records.to_dict(orient='records')))
extract_records[24]

{'data': {'type': 'samples',
  'attributes': {'attribute_map': {'RNA extract code': 'RNA-H3-21/04/2016',
    'Field sample': '531'},
   'tags': []},
  'relationships': {'sample_type': {'data': {'id': '5',
     'type': 'sample_types'}},
   'creators': {'data': [{'id': '1', 'type': 'people'}]},
   'projects': {'data': [{'id': '2', 'type': 'projects'}]},
   'assays': {'data': [{'id': '2', 'type': 'assays'}]}}}}

In [ ]:
extract_records = add_samples(extract_records, "RNA extract code")

sample # RNA-C1-01/02/2016, record 585, added
sample # RNA-C1-30/01/2017, record 586, added
sample # RNA-C2-01/02/2016, record 587, added
sample # RNA-C2-30/01/2017, record 588, added
sample # RNA-E1-19/11/2015, record 589, added
sample # RNA-E1-10/11/2016, record 590, added
sample # RNA-E1-23/05/2016, record 591, added
sample # RNA-E1-03/05/2017, record 592, added
sample # RNA-E2-19/11/2015, record 593, added
sample # RNA-E2-10/11/2016, record 594, added
sample # RNA-E2-23/05/2016, record 595, added
sample # RNA-E2-10/05/2017, record 596, added
sample # RNA-E3-01/02/2016, record 597, added
sample # RNA-E3-10/11/2016, record 598, added
sample # RNA-E3-31/05/2016, record 599, added
sample # RNA-E3-03/05/2017, record 600, added
sample # RNA-E4-04/11/2015, record 601, added
sample # RNA-E4-27/10/2016, record 602, added
sample # RNA-E4-31/05/2016, record 603, added
sample # RNA-E4-03/05/2017, record 604, added
sample # RNA-H1-21/04/2016, record 605, added
sample # RNA-H1-19/04/2017, record 606, added
sample # RNA-H2-21/04/2016, record 607, added
sample # RNA-H2-19/04/2017, record 608, added
sample # RNA-H3-21/04/2016, record 609, added
sample # RNA-H3-19/04/2017, record 610, added
sample # RNA-L1-19/11/2015, record 611, added
sample # RNA-L1-10/11/2016, record 612, added
sample # RNA-L1-31/03/2016, record 613, added
sample # RNA-L1-19/04/2017, record 614, added
sample # RNA-L1-16/07/2015, record 615, added
sample # RNA-L1-20/07/2016, record 616, added
sample # RNA-L2-19/11/2015, record 617, added
sample # RNA-L2-10/11/2016, record 618, added
sample # RNA-L2-31/03/2016, record 619, added
sample # RNA-L2-16/07/2015, record 620, added
sample # RNA-L2-20/07/2016, record 621, added
sample # RNA-L3-19/11/2015, record 622, added
sample # RNA-L3-10/11/2016, record 623, added
sample # RNA-L3-31/03/2016, record 624, added
sample # RNA-L3-19/04/2017, record 625, added

### Task 2. Creating libraries


This task has two sub-tasks: 
1. Converting sample_ids in "Library_samples" to record id
2. Posting

#### Converting Sample ids to Record ids

In [73]:
field_sample_records_bysample_id = field_sample_records.set_index('sample_id')['record_id'].to_dict()
field_sample_records_bysample_id['M1-16/07/2015']

'49'

In [72]:
library_samples

,Library_code,Collection_code,Species_name,Habitat,Number_of_extracts,Sample_code
0,PV001,M1V,Amaranthus sp,Crop,8,[M1-16/07/2015]
1,PV002,M1V,Convolvulus arvensis,Crop,11,[M1-16/07/2015]
2,PV003,M1V,Cucumis melo,Crop,13,[M1-16/07/2015]
3,PV003bgi,M1V,Cucumis melo,Crop,13,[M1-16/07/2015]
4,PV004bgi,M1V,Cyperus longus,Crop,7,[M1-16/07/2015]
...,...,...,...,...,...,...
308,PV586,H1P,Fumaria parviflora,Crop,8,[H1-21/04/2016]
309,PV587,H1P,Hirschfeldia incana,Crop,8,[H1-21/04/2016]
310,PV588,H1P,Hordeum vulgare,Crop,8,[H1-21/04/2016]
311,PV589,H1P,Hordeum vulgare,Crop,8,[H1-21/04/2016]
312,PV590,Z1V,Zea mays,Crop,11,[Z1-16/07/2015]

In [75]:
library_samples['Sample_record'] = library_samples['Sample_code'].apply(lambda x: list(map(lambda x: str(field_sample_records_bysample_id[x]), x)))
library_samples[:10]

,Library_code,Collection_code,Species_name,Habitat,Number_of_extracts,Sample_code,Sample_record
0,PV001,M1V,Amaranthus sp,Crop,8,[M1-16/07/2015],[49]
1,PV002,M1V,Convolvulus arvensis,Crop,11,[M1-16/07/2015],[49]
2,PV003,M1V,Cucumis melo,Crop,13,[M1-16/07/2015],[49]
3,PV003bgi,M1V,Cucumis melo,Crop,13,[M1-16/07/2015],[49]
4,PV004bgi,M1V,Cyperus longus,Crop,7,[M1-16/07/2015],[49]
5,PV005bgi,Q1F,Artemisia herba alba,Oak,12,"[Q1-08/09/2015, Q1-12/09/2016]","[59, 60]"
6,PV006bgi,Q1F,Artemisia herba alba,Oak,19,"[Q1-08/09/2015, Q1-12/09/2016]","[59, 60]"
7,PV007bgi,Q1F,Teucrium pseudochamaepitys,Oak,17,"[Q1-08/09/2015, Q1-12/09/2016]","[59, 60]"
8,PV008bgi,Q1F,Jasminum fruticans,Oak,11,"[Q1-08/09/2015, Q1-12/09/2016]","[59, 60]"
9,PV009,Q1F,Quercus coccifera,Oak,13,"[Q1-08/09/2015, Q1-12/09/2016]","[59, 60]"

In [ ]:
def create_library_record(entry: Dict[str, Any], project_id: str, people_id: str, sample_type_id: str, assay_id: str):
    attributes = {
        
        "attribute_map": {
            "Library code": entry['Library_code'],
            "Number of extracts": entry['Number_of_extracts'],
            "Species name": entry['Species_name'],
            "RNA extract": entry['Sample_record']
        },
        "tags": [
            "library"
        ]
    }    
    
    record = create_record(
        attributes_dict=attributes, project_id=project_id, people_id=people_id,
        sample_type_id=sample_type_id, assay_id=assay_id
    )
    return record

In [86]:
# IMPORTANT TO CHECK THESE ONES BEFORE UPLOAD
people_id = '1'
project_id = '2'
assay_id = '2' # Check these ones carefully
sample_type_id = '2'

create_library_record_ = lambda x: create_library_record(
    x, 
    project_id=project_id, people_id=people_id, 
    sample_type_id=sample_type_id, assay_id=assay_id
)
library_records = list(map(
    create_library_record_, library_samples.to_dict(orient='records'))
)
library_records[24]

{'data': {'type': 'samples',
  'attributes': {'attribute_map': {'Library code': 'PV024',
    'Number of extracts': 15,
    'Species name': 'Verbascum sinuatum',
    'Field samples': ['17', '18']},
   'tags': ['library']},
  'relationships': {'sample_type': {'data': {'id': '2',
     'type': 'sample_types'}},
   'creators': {'data': [{'id': '1', 'type': 'people'}]},
   'projects': {'data': [{'id': '2', 'type': 'projects'}]},
   'assays': {'data': [{'id': '2', 'type': 'assays'}]}}}}

In [87]:
len(library_records)

313

In [88]:
library_records = add_samples(library_records, "Library code")

sample # PV001, record 79, added
sample # PV002, record 80, added
sample # PV003, record 81, added
sample # PV003bgi, record 82, added
sample # PV004bgi, record 83, added
sample # PV005bgi, record 84, added
sample # PV006bgi, record 85, added
sample # PV007bgi, record 86, added
sample # PV008bgi, record 87, added
sample # PV009, record 88, added
sample # PV009bgi, record 89, added
sample # PV010bgi, record 90, added
sample # PV011, record 91, added
sample # PV012bgi, record 92, added
sample # PV013bgi, record 93, added
sample # PV014, record 94, added
sample # PV015bgi, record 95, added
sample # PV016, record 96, added
sample # PV017bgi, record 97, added
sample # PV018bgi, record 98, added
sample # PV020bgi, record 99, added
sample # PV021bgi, record 100, added
sample # PV022, record 101, added
sample # PV023, record 102, added
sample # PV024, record 103, added
sample # PV025, record 104, added
sample # PV026, record 105, added
sample # PV027, record 106, added
sample # PV028, record 107, added
sample # PV029, record 108, added
sample # PV030, record 109, added
sample # PV031, record 110, added
sample # PV032, record 111, added
sample # PV033, record 112, added
sample # PV034, record 113, added
sample # PV035, record 114, added
sample # PV036, record 115, added
sample # PV037, record 116, added
sample # PV041, record 117, added
sample # PV042, record 118, added
sample # PV046, record 119, added
sample # PV047, record 120, added
sample # PV048, record 121, added
sample # PV049, record 122, added
sample # PV050, record 123, added
sample # PV051, record 124, added
sample # PV052, record 125, added
sample # PV053, record 126, added
sample # PV054, record 127, added
sample # PV055, record 128, added
sample # PV056, record 129, added
sample # PV057, record 130, added
sample # PV058, record 131, added
sample # PV059, record 132, added
sample # PV060, record 133, added
sample # PV061, record 134, added
sample # PV062, record 135, added
sample # PV063, record 136, added
sample # PV064, record 137, added
sample # PV065, record 138, added
sample # PV066, record 139, added
sample # PV068, record 140, added
sample # PV069, record 141, added
sample # PV070, record 142, added
sample # PV071, record 143, added
sample # PV072, record 144, added
sample # PV074, record 145, added
sample # PV075, record 146, added
sample # PV076, record 147, added
sample # PV078, record 148, added
sample # PV079, record 149, added
sample # PV080, record 150, added
sample # PV081, record 151, added
sample # PV082, record 152, added
sample # PV083, record 153, added
sample # PV084, record 154, added
sample # PV085, record 155, added
sample # PV086, record 156, added
sample # PV087, record 157, added
sample # PV088, record 158, added
sample # PV089, record 159, added
sample # PV090, record 160, added
sample # PV091, record 161, added
sample # PV092, record 162, added
sample # PV093, record 163, added
sample # PV094, record 164, added
sample # PV095, record 165, added
sample # PV096, record 166, added
sample # PV097, record 167, added
sample # PV098, record 168, added
sample # PV099, record 169, added
sample # PV100, record 170, added
sample # PV101, record 171, added
sample # PV102, record 172, added
sample # PV103, record 173, added
sample # PV104, record 174, added
sample # PV105, record 175, added
sample # PV106, record 176, added
sample # PV107, record 177, added
sample # PV108, record 178, added
sample # PV109, record 179, added
sample # PV110, record 180, added
sample # PV111, could not be added, ERROR 500
sample # PV112, record 181, added
sample # PV113, record 182, added
sample # PV114, record 183, added
sample # PV115, record 184, added
sample # PV116, record 185, added
sample # PV117, record 186, added
sample # PV118, record 187, added
sample # PV119, record 188, added
sample # PV120, record 189, added
sample # PV121, record 190, added
sample # PV122, record 191, added
sample # PV123, record 192, added
sample # PV124, record 193, added
sample # PV125, record 194, added
sample # PV126, record 195, added
sample # PV127, record 196, added
sample # PV128, record 197, added
sample # PV129, record 198, added
sample # PV130, record 199, added
sample # PV131, record 200, added
sample # PV132, record 201, added
sample # PV133, record 202, added
sample # PV134, record 203, added
sample # PV135, record 204, added
sample # PV136, record 205, added
sample # PV137, record 206, added
sample # PV138, record 207, added
sample # PV139, record 208, added
sample # PV140, record 209, added
sample # PV141, record 210, added
sample # PV142, record 211, added
sample # PV143, record 212, added
sample # PV144, record 213, added
sample # PV145, record 214, added
sample # PV146, record 215, added
sample # PV147, record 216, added
sample # PV148, record 217, added
sample # PV149, record 218, added
sample # PV150, record 219, added
sample # PV151, record 220, added
sample # PV152, record 221, added
sample # PV153, record 222, added
sample # PV154, record 223, added
sample # PV155, record 224, added
sample # PV156, record 225, added
sample # PV157, record 226, added
sample # PV158, record 227, added
sample # PV159, record 228, added
sample # PV160, record 229, added
sample # PV161, record 230, added
sample # PV162, record 231, added
sample # PV163, record 232, added
sample # PV164, record 233, added
sample # PV165, record 234, added
sample # PV166, record 235, added
sample # PV167, record 236, added
sample # PV168, record 237, added
sample # PV169, record 238, added
sample # PV170, record 239, added
sample # PV171, record 240, added
sample # PV172, record 241, added
sample # PV173, record 242, added
sample # PV174, record 243, added
sample # PV175, record 244, added
sample # PV176, record 245, added
sample # PV177, record 246, added
sample # PV178, record 247, added
sample # PV179, record 248, added
sample # PV180, record 249, added
sample # PV181, record 250, added
sample # PV182, record 251, added
sample # PV183, record 252, added
sample # PV184, record 253, added
sample # PV185, record 254, added
sample # PV186, record 255, added
sample # PV187, record 256, added
sample # PV188, record 257, added
sample # PV189, record 258, added
sample # PV190, record 259, added
sample # PV191, record 260, added
sample # PV192, record 261, added
sample # PV193, record 262, added
sample # PV194, record 263, added
sample # PV195, record 264, added
sample # PV196, record 265, added
sample # PV197, record 266, added
sample # PV198, record 267, added
sample # PV199, record 268, added
sample # PV200, record 269, added
sample # PV201, record 270, added
sample # PV202, record 271, added
sample # PV203, record 272, added
sample # PV204, record 273, added
sample # PV205, record 274, added
sample # PV206, record 275, added
sample # PV207, record 276, added
sample # PV208, record 277, added
sample # PV209, record 278, added
sample # PV210, record 279, added
sample # PV211, record 280, added
sample # PV212, record 281, added
sample # PV213, record 282, added
sample # PV214, record 283, added
sample # PV215, record 284, added
sample # PV216, record 285, added
sample # PV217, record 286, added
sample # PV218, record 287, added
sample # PV219, record 288, added
sample # PV220, record 289, added
sample # PV221, record 290, added
sample # PV222, record 291, added
sample # PV223, record 292, added
sample # PV224, record 293, added
sample # PV225, record 294, added
sample # PV226, record 295, added
sample # PV227, record 296, added
sample # PV228, record 297, added
sample # PV229, record 298, added
sample # PV230, record 299, added
sample # PV231, record 300, added
sample # PV232, record 301, added
sample # PV233, record 302, added
sample # PV234, record 303, added
sample # PV235, record 304, added
sample # PV236, record 305, added
sample # PV237, record 306, added
sample # PV252, record 307, added
sample # PV257, record 308, added
sample # PV262, record 309, added
sample # PV268, record 310, added
sample # PV269, record 311, added
sample # PV270, record 312, added
sample # PV277, record 313, added
sample # PV296, record 314, added
sample # PV298, record 315, added
sample # PV306, record 316, added
sample # PV312, record 317, added
sample # PV313, record 318, added
sample # PV330, record 319, added
sample # PV350, record 320, added
sample # PV352, record 321, added
sample # PV356, record 322, added
sample # PV359, record 323, added
sample # PV369, record 324, added
sample # PV380, record 325, added
sample # PV386, record 326, added
sample # PV390, record 327, added
sample # PV418, record 328, added
sample # PV421, record 329, added
sample # PV423, record 330, added
sample # PV426, record 331, added
sample # PV428, record 332, added
sample # PV430, record 333, added
sample # PV437, record 334, added
sample # PV440, record 335, added
sample # PV441, record 336, added
sample # PV454, record 337, added
sample # PV457, record 338, added
sample # PV464, record 339, added
sample # PV473, record 340, added
sample # PV489, record 341, added
sample # PV491, record 342, added
sample # PV495, record 343, added
sample # PV496, record 344, added
sample # PV498, record 345, added
sample # PV500, record 346, added
sample # PV501, record 347, added
sample # PV503, record 348, added
sample # PV505, record 349, added
sample # PV514, record 350, added
sample # PV516, record 351, added
sample # PV519, record 352, added
sample # PV525, record 353, added
sample # PV526, record 354, added
sample # PV527, record 355, added
sample # PV529, record 356, added
sample # PV534, record 357, added
sample # PV535, record 358, added
sample # PV538, record 359, added
sample # PV540, record 360, added
sample # PV544, record 361, added
sample # PV546, record 362, added
sample # PV551, record 363, added
sample # PV553, record 364, added
sample # PV554, record 365, added
sample # PV556, record 366, added
sample # PV557, record 367, added
sample # PV558, record 368, added
sample # PV559, record 369, added
sample # PV560, record 370, added
sample # PV563, record 371, added
sample # PV564, record 372, added
sample # PV565, record 373, added
sample # PV567, record 374, added
sample # PV572, record 375, added
sample # PV573, record 376, added
sample # PV574, record 377, added
sample # PV575, record 378, added
sample # PV576, record 379, added
sample # PV579, record 380, added
sample # PV580, record 381, added
sample # PV581, record 382, added
sample # PV583, record 383, added
sample # PV584, record 384, added
sample # PV585, record 385, added
sample # PV586, record 386, added
sample # PV587, record 387, added
sample # PV588, record 388, added
sample # PV589, record 389, added
sample # PV590, record 390, added

In [89]:
library_records = get_all_samples_from_type('2', verbose=False)
library_records = [dict(record_id=item['data']['id'], sample_id=item['data']['attributes']['attribute_map']['Library code']) for item in library_records]
library_records = pd.DataFrame.from_records(library_records)
library_records

    record_id sample_id
0          79     PV001
1          80     PV002
2          81     PV003
3          82  PV003bgi
4          83  PV004bgi
..        ...       ...
307       386     PV586
308       387     PV587
309       388     PV588
310       389     PV589
311       390     PV590

[312 rows x 2 columns]

### Task 3. Creating RNA extracts

    record_id sample_id  Extract code
0          79     PV001     RNA-PV001
1          80     PV002     RNA-PV002
2          81     PV003     RNA-PV003
3          82  PV003bgi  RNA-PV003bgi
4          83  PV004bgi  RNA-PV004bgi
..        ...       ...           ...
307       386     PV586     RNA-PV586
308       387     PV587     RNA-PV587
309       388     PV588     RNA-PV588
310       389     PV589     RNA-PV589
311       390     PV590     RNA-PV590

[312 rows x 3 columns]

{'data': {'type': 'samples',
  'attributes': {'attribute_map': {'RNA extract code': 'RNA-PV024',
    'Library': '103'},
   'tags': ['RNA extract']},
  'relationships': {'sample_type': {'data': {'id': '3',
     'type': 'sample_types'}},
   'creators': {'data': [{'id': '1', 'type': 'people'}]},
   'projects': {'data': [{'id': '2', 'type': 'projects'}]},
   'assays': {'data': [{'id': '3', 'type': 'assays'}]}}}}

sample # RNA-PV001, record 391, added
sample # RNA-PV002, record 392, added
sample # RNA-PV003, record 393, added
sample # RNA-PV003bgi, record 394, added
sample # RNA-PV004bgi, record 395, added
sample # RNA-PV005bgi, record 396, added
sample # RNA-PV006bgi, record 397, added
sample # RNA-PV007bgi, record 398, added
sample # RNA-PV008bgi, record 399, added
sample # RNA-PV009, record 400, added
sample # RNA-PV009bgi, record 401, added
sample # RNA-PV010bgi, record 402, added
sample # RNA-PV011, record 403, added
sample # RNA-PV012bgi, record 404, added
sample # RNA-PV013bgi, record 405, added
sample # RNA-PV014, record 406, added
sample # RNA-PV015bgi, record 407, added
sample # RNA-PV016, record 408, added
sample # RNA-PV017bgi, record 409, added
sample # RNA-PV018bgi, record 410, added
sample # RNA-PV020bgi, record 411, added
sample # RNA-PV021bgi, record 412, added
sample # RNA-PV022, record 413, added
sample # RNA-PV023, record 414, added
sample # RNA-PV024, record 415, added
sample # RNA-PV025, record 416, added
sample # RNA-PV026, record 417, added
sample # RNA-PV027, record 418, added
sample # RNA-PV028, record 419, added
sample # RNA-PV029, record 420, added
sample # RNA-PV030, record 421, added
sample # RNA-PV031, record 422, added
sample # RNA-PV032, record 423, added
sample # RNA-PV033, record 424, added
sample # RNA-PV034, record 425, added
sample # RNA-PV035, record 426, added
sample # RNA-PV036, record 427, added
sample # RNA-PV037, record 428, added
sample # RNA-PV041, record 429, added
sample # RNA-PV042, record 430, added
sample # RNA-PV046, record 431, added
sample # RNA-PV047, record 432, added
sample # RNA-PV048, record 433, added
sample # RNA-PV049, record 434, added
sample # RNA-PV050, record 435, added
sample # RNA-PV051, record 436, added
sample # RNA-PV052, record 437, added
sample # RNA-PV053, record 438, added
sample # RNA-PV054, record 439, added
sample # RNA-PV055, record 440, added
sample # RNA-PV056, record 441, added
sample # RNA-PV057, record 442, added
sample # RNA-PV058, record 443, added
sample # RNA-PV059, record 444, added
sample # RNA-PV060, record 445, added
sample # RNA-PV061, record 446, added
sample # RNA-PV062, record 447, added
sample # RNA-PV063, record 448, added
sample # RNA-PV064, record 449, added
sample # RNA-PV065, record 450, added
sample # RNA-PV066, record 451, added
sample # RNA-PV068, record 452, added
sample # RNA-PV069, record 453, added
sample # RNA-PV070, record 454, added
sample # RNA-PV071, record 455, added
sample # RNA-PV072, record 456, added
sample # RNA-PV074, record 457, added
sample # RNA-PV075, record 458, added
sample # RNA-PV076, record 459, added
sample # RNA-PV078, record 460, added
sample # RNA-PV079, record 461, added
sample # RNA-PV080, record 462, added
sample # RNA-PV081, record 463, added
sample # RNA-PV082, record 464, added
sample # RNA-PV083, record 465, added
sample # RNA-PV084, record 466, added
sample # RNA-PV085, record 467, added
sample # RNA-PV086, record 468, added
sample # RNA-PV087, record 469, added
sample # RNA-PV088, record 470, added
sample # RNA-PV089, record 471, added
sample # RNA-PV090, record 472, added
sample # RNA-PV091, record 473, added
sample # RNA-PV092, record 474, added
sample # RNA-PV093, record 475, added
sample # RNA-PV094, record 476, added
sample # RNA-PV095, record 477, added
sample # RNA-PV096, record 478, added
sample # RNA-PV097, record 479, added
sample # RNA-PV098, record 480, added
sample # RNA-PV099, record 481, added
sample # RNA-PV100, record 482, added
sample # RNA-PV101, record 483, added
sample # RNA-PV102, record 484, added
sample # RNA-PV103, record 485, added
sample # RNA-PV104, record 486, added
sample # RNA-PV105, record 487, added
sample # RNA-PV106, record 488, added
sample # RNA-PV107, record 489, added
sample # RNA-PV108, record 490, added
sample # RNA-PV109, record 491, added
sample # RNA-PV110, record 492, added
sample # RNA-PV112, record 493, added
sample # RNA-PV113, record 494, added
sample # RNA-PV114, record 495, added
sample # RNA-PV115, record 496, added
sample # RNA-PV116, record 497, added
sample # RNA-PV117, record 498, added
sample # RNA-PV118, record 499, added
sample # RNA-PV119, record 500, added
sample # RNA-PV120, record 501, added
sample # RNA-PV121, record 502, added
sample # RNA-PV122, record 503, added
sample # RNA-PV123, record 504, added
sample # RNA-PV124, record 505, added
sample # RNA-PV125, record 506, added
sample # RNA-PV126, record 507, added
sample # RNA-PV127, record 508, added
sample # RNA-PV128, record 509, added
sample # RNA-PV129, record 510, added
sample # RNA-PV130, record 511, added
sample # RNA-PV131, record 512, added
sample # RNA-PV132, record 513, added
sample # RNA-PV133, record 514, added
sample # RNA-PV134, record 515, added
sample # RNA-PV135, record 516, added
sample # RNA-PV136, record 517, added
sample # RNA-PV137, record 518, added
sample # RNA-PV138, record 519, added
sample # RNA-PV139, record 520, added
sample # RNA-PV140, record 521, added
sample # RNA-PV141, record 522, added
sample # RNA-PV142, record 523, added
sample # RNA-PV143, record 524, added
sample # RNA-PV144, record 525, added
sample # RNA-PV145, record 526, added
sample # RNA-PV146, record 527, added
sample # RNA-PV147, record 528, added
sample # RNA-PV148, record 529, added
sample # RNA-PV149, record 530, added
sample # RNA-PV150, record 531, added
sample # RNA-PV151, record 532, added
sample # RNA-PV152, record 533, added
sample # RNA-PV153, record 534, added
sample # RNA-PV154, record 535, added
sample # RNA-PV155, record 536, added
sample # RNA-PV156, record 537, added
sample # RNA-PV157, record 538, added
sample # RNA-PV158, record 539, added
sample # RNA-PV159, record 540, added
sample # RNA-PV160, record 541, added
sample # RNA-PV161, record 542, added
sample # RNA-PV162, record 543, added
sample # RNA-PV163, record 544, added
sample # RNA-PV164, record 545, added
sample # RNA-PV165, record 546, added
sample # RNA-PV166, record 547, added
sample # RNA-PV167, record 548, added
sample # RNA-PV168, record 549, added
sample # RNA-PV169, record 550, added
sample # RNA-PV170, record 551, added
sample # RNA-PV171, record 552, added
sample # RNA-PV172, record 553, added
sample # RNA-PV173, record 554, added
sample # RNA-PV174, record 555, added
sample # RNA-PV175, record 556, added
sample # RNA-PV176, record 557, added
sample # RNA-PV177, record 558, added
sample # RNA-PV178, record 559, added
sample # RNA-PV179, record 560, added
sample # RNA-PV180, record 561, added
sample # RNA-PV181, record 562, added
sample # RNA-PV182, record 563, added
sample # RNA-PV183, record 564, added
sample # RNA-PV184, record 565, added
sample # RNA-PV185, record 566, added
sample # RNA-PV186, record 567, added
sample # RNA-PV187, record 568, added
sample # RNA-PV188, record 569, added
sample # RNA-PV189, record 570, added
sample # RNA-PV190, record 571, added
sample # RNA-PV191, record 572, added
sample # RNA-PV192, record 573, added
sample # RNA-PV193, record 574, added
sample # RNA-PV194, record 575, added
sample # RNA-PV195, record 576, added
sample # RNA-PV196, record 577, added
sample # RNA-PV197, record 578, added
sample # RNA-PV198, record 579, added
sample # RNA-PV199, record 580, added
sample # RNA-PV200, record 581, added
sample # RNA-PV201, record 582, added
sample # RNA-PV202, record 583, added
sample # RNA-PV203, record 584, added
sample # RNA-PV204, record 585, added
sample # RNA-PV205, record 586, added
sample # RNA-PV206, record 587, added
sample # RNA-PV207, record 588, added
sample # RNA-PV208, record 589, added
sample # RNA-PV209, record 590, added
sample # RNA-PV210, record 591, added
sample # RNA-PV211, record 592, added
sample # RNA-PV212, record 593, added
sample # RNA-PV213, record 594, added
sample # RNA-PV214, record 595, added
sample # RNA-PV215, record 596, added
sample # RNA-PV216, record 597, added
sample # RNA-PV217, record 598, added
sample # RNA-PV218, record 599, added
sample # RNA-PV219, record 600, added
sample # RNA-PV220, record 601, added
sample # RNA-PV221, record 602, added
sample # RNA-PV222, record 603, added
sample # RNA-PV223, record 604, added
sample # RNA-PV224, record 605, added
sample # RNA-PV225, record 606, added
sample # RNA-PV226, record 607, added
sample # RNA-PV227, record 608, added
sample # RNA-PV228, record 609, added
sample # RNA-PV229, record 610, added
sample # RNA-PV230, record 611, added
sample # RNA-PV231, record 612, added
sample # RNA-PV232, record 613, added
sample # RNA-PV233, record 614, added
sample # RNA-PV234, record 615, added
sample # RNA-PV235, record 616, added
sample # RNA-PV236, record 617, added
sample # RNA-PV237, record 618, added
sample # RNA-PV252, record 619, added
sample # RNA-PV257, record 620, added
sample # RNA-PV262, record 621, added
sample # RNA-PV268, record 622, added
sample # RNA-PV269, record 623, added
sample # RNA-PV270, record 624, added
sample # RNA-PV277, record 625, added
sample # RNA-PV296, record 626, added
sample # RNA-PV298, record 627, added
sample # RNA-PV306, record 628, added
sample # RNA-PV312, record 629, added
sample # RNA-PV313, record 630, added
sample # RNA-PV330, record 631, added
sample # RNA-PV350, record 632, added
sample # RNA-PV352, record 633, added
sample # RNA-PV356, record 634, added
sample # RNA-PV359, record 635, added
sample # RNA-PV369, record 636, added
sample # RNA-PV380, record 637, added
sample # RNA-PV386, record 638, added
sample # RNA-PV390, record 639, added
sample # RNA-PV418, record 640, added
sample # RNA-PV421, record 641, added
sample # RNA-PV423, record 642, added
sample # RNA-PV426, record 643, added
sample # RNA-PV428, record 644, added
sample # RNA-PV430, record 645, added
sample # RNA-PV437, record 646, added
sample # RNA-PV440, record 647, added
sample # RNA-PV441, record 648, added
sample # RNA-PV454, record 649, added
sample # RNA-PV457, record 650, added
sample # RNA-PV464, record 651, added
sample # RNA-PV473, record 652, added
sample # RNA-PV489, record 653, added
sample # RNA-PV491, record 654, added
sample # RNA-PV495, record 655, added
sample # RNA-PV496, record 656, added
sample # RNA-PV498, record 657, added
sample # RNA-PV500, record 658, added
sample # RNA-PV501, record 659, added
sample # RNA-PV503, record 660, added
sample # RNA-PV505, record 661, added
sample # RNA-PV514, record 662, added
sample # RNA-PV516, record 663, added
sample # RNA-PV519, record 664, added
sample # RNA-PV525, record 665, added
sample # RNA-PV526, record 666, added
sample # RNA-PV527, record 667, added
sample # RNA-PV529, record 668, added
sample # RNA-PV534, record 669, added
sample # RNA-PV535, record 670, added
sample # RNA-PV538, record 671, added
sample # RNA-PV540, record 672, added
sample # RNA-PV544, record 673, added
sample # RNA-PV546, record 674, added
sample # RNA-PV551, record 675, added
sample # RNA-PV553, record 676, added
sample # RNA-PV554, record 677, added
sample # RNA-PV556, record 678, added
sample # RNA-PV557, record 679, added
sample # RNA-PV558, record 680, added
sample # RNA-PV559, record 681, added
sample # RNA-PV560, record 682, added
sample # RNA-PV563, record 683, added
sample # RNA-PV564, record 684, added
sample # RNA-PV565, record 685, added
sample # RNA-PV567, record 686, added
sample # RNA-PV572, record 687, added
sample # RNA-PV573, record 688, added
sample # RNA-PV574, record 689, added
sample # RNA-PV575, record 690, added
sample # RNA-PV576, record 691, added
sample # RNA-PV579, record 692, added
sample # RNA-PV580, record 693, added
sample # RNA-PV581, record 694, added
sample # RNA-PV583, record 695, added
sample # RNA-PV584, record 696, added
sample # RNA-PV585, record 697, added
sample # RNA-PV586, record 698, added
sample # RNA-PV587, record 699, added
sample # RNA-PV588, record 700, added
sample # RNA-PV589, record 701, added
sample # RNA-PV590, record 702, added

### Task 4. Creating Raw reads

Two step process: uploading the files, and then creating the records.

In [116]:
files

                                  files Library code strand
0    PV051_22518_ACTTGA_read1.sub.fastq        PV051  read1
1    PV051_22518_ACTTGA_read2.sub.fastq        PV051  read2
2    PV052_22519_AGTCAA_read1.sub.fastq        PV052  read1
3    PV052_22519_AGTCAA_read2.sub.fastq        PV052  read2
4    PV053_22520_AGTTCC_read1.sub.fastq        PV053  read1
..                                  ...          ...    ...
571   PV97_22531_GTTTCG_read2.sub.fastq         PV97  read2
572   PV98_22334_CGTACG_read1.sub.fastq         PV98  read1
573   PV98_22334_CGTACG_read2.sub.fastq         PV98  read2
574   PV99_22335_GAGTGG_read1.sub.fastq         PV99  read1
575   PV99_22335_GAGTGG_read2.sub.fastq         PV99  read2

[576 rows x 3 columns]

In [127]:
files = pd.read_csv("../samples/raw-seqs-index.csv", header=None, names=['files'])
files['Library code'] = files['files'].apply(lambda x: x.split('_')[0])
files['Primers'] = files['files'].apply(lambda x: x.split('_')[2])
files['strand'] = files['files'].apply(lambda x: x.split('_')[-1].replace('.sub.fastq', ''))
files_pvt = files.pivot(index=['Library code', 'Primers'], columns='strand', values='files')
files_pvt = files_pvt.reset_index()
files_pvt

strand,Library code,Primers,read1,read2
0,PV051,ACTTGA,PV051_22518_ACTTGA_read1.sub.fastq,PV051_22518_ACTTGA_read2.sub.fastq
1,PV052,AGTCAA,PV052_22519_AGTCAA_read1.sub.fastq,PV052_22519_AGTCAA_read2.sub.fastq
2,PV053,AGTTCC,PV053_22520_AGTTCC_read1.sub.fastq,PV053_22520_AGTTCC_read2.sub.fastq
3,PV054,ATGTCA,PV054_22521_ATGTCA_read1.sub.fastq,PV054_22521_ATGTCA_read2.sub.fastq
4,PV056,GTGGCC,PV056_22523_GTGGCC_read1.sub.fastq,PV056_22523_GTGGCC_read2.sub.fastq
...,...,...,...,...
283,PV95,GTGAAA,PV95_22331_GTGAAA_read1.sub.fastq,PV95_22331_GTGAAA_read2.sub.fastq
284,PV96,GTGGCC,PV96_22332_GTGGCC_read1.sub.fastq,PV96_22332_GTGGCC_read2.sub.fastq
285,PV97,GTTTCG,PV97_22531_GTTTCG_read1.sub.fastq,PV97_22531_GTTTCG_read2.sub.fastq
286,PV98,CGTACG,PV98_22334_CGTACG_read1.sub.fastq,PV98_22334_CGTACG_read2.sub.fastq
287,PV99,GAGTGG,PV99_22335_GAGTGG_read1.sub.fastq,PV99_22335_GAGTGG_read2.sub.fastq

In [128]:
files

                                  files Library code Primers strand
0    PV051_22518_ACTTGA_read1.sub.fastq        PV051  ACTTGA  read1
1    PV051_22518_ACTTGA_read2.sub.fastq        PV051  ACTTGA  read2
2    PV052_22519_AGTCAA_read1.sub.fastq        PV052  AGTCAA  read1
3    PV052_22519_AGTCAA_read2.sub.fastq        PV052  AGTCAA  read2
4    PV053_22520_AGTTCC_read1.sub.fastq        PV053  AGTTCC  read1
..                                  ...          ...     ...    ...
571   PV97_22531_GTTTCG_read2.sub.fastq         PV97  GTTTCG  read2
572   PV98_22334_CGTACG_read1.sub.fastq         PV98  CGTACG  read1
573   PV98_22334_CGTACG_read2.sub.fastq         PV98  CGTACG  read2
574   PV99_22335_GAGTGG_read1.sub.fastq         PV99  GAGTGG  read1
575   PV99_22335_GAGTGG_read2.sub.fastq         PV99  GAGTGG  read2

[576 rows x 4 columns]

In [133]:
def upload_data_file(filename, path, title, assay_id, study_id, investigation_id, people_id, project_id, data_type, data_type_uri, data_format, data_format_uri):
    local_blob = {
        'original_filename': filename, 'content_type':'text/plain'
    }
    data_file = {}
    data_file['data'] = {}
    data_file['data']['type'] = 'data_files'
    data_file['data']['attributes'] = {}
    data_file['data']['attributes']['title'] = title
    data_file['data']['attributes']['license'] = 'notspecified'
    data_file['data']['attributes']['policy'] = {
        'access': 'no_access',
        'permissions': [{'resource': {'id': project_id, 'type': 'projects'},
        'access': 'manage'}]
    }
    data_file['data']['attributes']['content_blobs'] = [local_blob]
    data_file['data']['attributes']['data_type_annotations'] = [
        {'label': data_type, 'identifier': data_type_uri}
    ]
    data_file['data']['attributes']['data_format_annotations']= [
        {'label': data_format, 'identifier': data_format_uri}
    ]
    data_file['data']['relationships'] = {}
    data_file['data']['relationships']['projects'] = {'data': [{'id': project_id, 'type': 'projects'}]}
    data_file['data']['relationships']['people'] = {'data': [{'id': people_id, 'type': 'people'}]}
    data_file['data']['relationships']['investigations'] = {'data': [{'id': investigation_id, 'type': 'investigations'}]}
    data_file['data']['relationships']['studies'] = {'data': [{'id': study_id, 'type': 'studies'}]}
    data_file['data']['relationships']['assays'] = {'data': [{'id': assay_id, 'type': 'assays'}]}

    # Registering data file
    for i in range(5):
        try:
            r = requests.post(f'{api_url}/data_files/', json=data_file, headers=headers)
            r.raise_for_status()
            break
        except requests.HTTPError:
            continue

    if r.status_code == 500:
        print(f"unable to upload {filename}")

    # Obtain BLOB URL
    blob_url = r.json()['data']['attributes']['content_blobs'][0]['link']
    blob_url = blob_url.replace('http://localhost:3000', api_url)
    # Upload file to Blob
    for i in range(5):
        
        try:
            with open(path + '/' + filename, 'r') as f:
                f.seek(0)
                upload = requests.put(blob_url, files={'file':f}, headers=headers)
                upload.raise_for_status()
            break
        except requests.HTTPError:
            continue

    if r.status_code == 500:
        print(f"unable to upload {filename}")

    
    return upload

In [134]:
for _, row in files.iterrows():
    print("processing ", row['files'])
    upload_data_file(
        filename=row['files'], path="../samples/all_libraries/",
        title=row['files'], assay_id='4', study_id='1',
        investigation_id='1', people_id='1',
        project_id='2', data_type='Sequence',
        data_type_uri='http://edamontology.org/data_2044',
        data_format='FASTQ-illumina',
        data_format_uri='http://edamontology.org/format_1931'
    )

processing  PV051_22518_ACTTGA_read1.sub.fastq
processing  PV051_22518_ACTTGA_read2.sub.fastq
processing  PV052_22519_AGTCAA_read1.sub.fastq
processing  PV052_22519_AGTCAA_read2.sub.fastq
processing  PV053_22520_AGTTCC_read1.sub.fastq
processing  PV053_22520_AGTTCC_read2.sub.fastq
processing  PV054_22521_ATGTCA_read1.sub.fastq
processing  PV054_22521_ATGTCA_read2.sub.fastq
processing  PV056_22523_GTGGCC_read1.sub.fastq
processing  PV056_22523_GTGGCC_read2.sub.fastq
processing  PV057_22524_GTTTCG_read1.sub.fastq
processing  PV057_22524_GTTTCG_read2.sub.fastq
processing  PV058_22525_GAGTGG_read1.sub.fastq
processing  PV058_22525_GAGTGG_read2.sub.fastq
processing  PV058_22526_ATCACG_read1.sub.fastq
processing  PV058_22526_ATCACG_read2.sub.fastq
processing  PV062_22529_GCCAAT_read1.sub.fastq
processing  PV062_22529_GCCAAT_read2.sub.fastq
processing  PV063_22530_GTCCGC_read1.sub.fastq
processing  PV063_22530_GTCCGC_read2.sub.fastq
processing  PV065_21352_TAGCTT_read1.sub.fastq
processing  PV065_21352_TAGCTT_read2.sub.fastq
processing  PV066_21353_GGCTAC_read1.sub.fastq
processing  PV066_21353_GGCTAC_read2.sub.fastq
processing  PV068_21355_TTAGGC_read1.sub.fastq
processing  PV068_21355_TTAGGC_read2.sub.fastq
processing  PV069_21356_GATCAG_read1.sub.fastq
processing  PV069_21356_GATCAG_read2.sub.fastq
processing  PV072_21359_GCCAAT_read1.sub.fastq
processing  PV072_21359_GCCAAT_read2.sub.fastq
processing  PV074_21360_ACTTGA_read1.sub.fastq
processing  PV074_21360_ACTTGA_read2.sub.fastq
processing  PV076_21362_CGTACG_read1.sub.fastq
processing  PV076_21362_CGTACG_read2.sub.fastq
processing  PV100_22336_ACTGAT_read1.sub.fastq
processing  PV100_22336_ACTGAT_read2.sub.fastq
processing  PV101_22756_ACAGTG_read1.sub.fastq
processing  PV101_22756_ACAGTG_read2.sub.fastq
processing  PV102_22757_GCCAAT_read1.sub.fastq
processing  PV102_22757_GCCAAT_read2.sub.fastq
processing  PV103_22758_CTTGTA_read1.sub.fastq
processing  PV103_22758_CTTGTA_read2.sub.fastq
processing  PV104_22759_GTGAAA_read1.sub.fastq
processing  PV104_22759_GTGAAA_read2.sub.fastq
processing  PV105_22760_CGATGT_read1.sub.fastq
processing  PV105_22760_CGATGT_read2.sub.fastq
processing  PV106_22761_TGACCA_read1.sub.fastq
processing  PV106_22761_TGACCA_read2.sub.fastq
processing  PV107_22762_CAGATC_read1.sub.fastq
processing  PV107_22762_CAGATC_read2.sub.fastq
processing  PV108_22763_CCGTCC_read1.sub.fastq
processing  PV108_22763_CCGTCC_read2.sub.fastq
processing  PV109_22764_ATCACG_read1.sub.fastq
processing  PV109_22764_ATCACG_read2.sub.fastq
processing  PV110_22765_ACTTGA_read1.sub.fastq
processing  PV110_22765_ACTTGA_read2.sub.fastq
processing  PV111_22766_TAGCTT_read1.sub.fastq
processing  PV111_22766_TAGCTT_read2.sub.fastq
processing  PV112_22767_GGCTAC_read1.sub.fastq
processing  PV112_22767_GGCTAC_read2.sub.fastq
processing  PV113_22768_GTCCGC_read1.sub.fastq
processing  PV113_22768_GTCCGC_read2.sub.fastq
processing  PV114_22769_ACTGAT_read1.sub.fastq
processing  PV114_22769_ACTGAT_read2.sub.fastq
processing  PV115_23905_CGTTGG_read1.sub.fastq
processing  PV115_23905_CGTTGG_read2.sub.fastq
processing  PV116_23906_TTCTGG_read1.sub.fastq
processing  PV116_23906_TTCTGG_read2.sub.fastq
processing  PV117_23907_GTTCGG_read1.sub.fastq
processing  PV117_23907_GTTCGG_read2.sub.fastq
processing  PV118_23908_TGGCGG_read1.sub.fastq
processing  PV118_23908_TGGCGG_read2.sub.fastq
processing  PV119_23909_AACCGG_read1.sub.fastq
processing  PV119_23909_AACCGG_read2.sub.fastq
processing  PV11_18809_CGATGT_read1.sub.fastq
processing  PV11_18809_CGATGT_read2.sub.fastq
processing  PV120_23910_CTGAGG_read1.sub.fastq
processing  PV120_23910_CTGAGG_read2.sub.fastq
processing  PV121_23911_ACTTCG_read1.sub.fastq
processing  PV121_23911_ACTTCG_read2.sub.fastq
processing  PV122_23912_TAGTCG_read1.sub.fastq
processing  PV122_23912_TAGTCG_read2.sub.fastq
processing  PV123_23913_TGGTTC_read1.sub.fastq
processing  PV123_23913_TGGTTC_read2.sub.fastq
processing  PV124_23914_GTCTTC_read1.sub.fastq
processing  PV124_23914_GTCTTC_read2.sub.fastq
processing  PV125_23915_ATTCTC_read1.sub.fastq
processing  PV125_23915_ATTCTC_read2.sub.fastq
processing  PV126_23916_CGGTTG_read1.sub.fastq
processing  PV126_23916_CGGTTG_read2.sub.fastq
processing  PV127_23917_ATCTTG_read1.sub.fastq
processing  PV127_23917_ATCTTG_read2.sub.fastq
processing  PV128_23918_TAATTG_read1.sub.fastq
processing  PV128_23918_TAATTG_read2.sub.fastq
processing  PV129_23919_CATTCG_read1.sub.fastq
processing  PV129_23919_CATTCG_read2.sub.fastq
processing  PV130_23920_GCTTAG_read1.sub.fastq
processing  PV130_23920_GCTTAG_read2.sub.fastq
processing  PV131_23921_GCTCCA_read1.sub.fastq
processing  PV131_23921_GCTCCA_read2.sub.fastq
processing  PV132_23922_CCGGTT_read1.sub.fastq
processing  PV132_23922_CCGGTT_read2.sub.fastq
processing  PV133_23923_TCGCAT_read1.sub.fastq
processing  PV133_23923_TCGCAT_read2.sub.fastq
processing  PV134_23924_CATAAC_read1.sub.fastq
processing  PV134_23924_CATAAC_read2.sub.fastq
processing  PV135_23925_AATCCG_read1.sub.fastq
processing  PV135_23925_AATCCG_read2.sub.fastq
processing  PV136_23926_GGCCTC_read1.sub.fastq
processing  PV136_23926_GGCCTC_read2.sub.fastq
processing  PV137_23927_GGAAGA_read1.sub.fastq
processing  PV137_23927_GGAAGA_read2.sub.fastq
processing  PV138_23928_TAAGAA_read1.sub.fastq
processing  PV138_23928_TAAGAA_read2.sub.fastq
processing  PV139_23929_GTCGAT_read1.sub.fastq
processing  PV139_23929_GTCGAT_read2.sub.fastq
processing  PV140_23930_AGAACC_read1.sub.fastq
processing  PV140_23930_AGAACC_read2.sub.fastq
processing  PV141_23931_GCTAAC_read1.sub.fastq
processing  PV141_23931_GCTAAC_read2.sub.fastq
processing  PV142_23932_TGACCA_read1.sub.fastq
processing  PV142_23932_TGACCA_read2.sub.fastq
processing  PV143_23933_GCAACG_read1.sub.fastq
processing  PV143_23933_GCAACG_read2.sub.fastq
processing  PV144_23934_TTCAAG_read1.sub.fastq
processing  PV144_23934_TTCAAG_read2.sub.fastq
processing  PV145_23935_CAACTA_read1.sub.fastq
processing  PV145_23935_CAACTA_read2.sub.fastq
processing  PV146_23936_GACTAA_read1.sub.fastq
processing  PV146_23936_GACTAA_read2.sub.fastq
processing  PV147_23937_ATAATT_read1.sub.fastq
processing  PV147_23937_ATAATT_read2.sub.fastq
processing  PV148_23938_TCGAGT_read1.sub.fastq
processing  PV148_23938_TCGAGT_read2.sub.fastq
processing  PV149_23939_TCAGAT_read1.sub.fastq
processing  PV149_23939_TCAGAT_read2.sub.fastq
processing  PV14_18810_ACTTGA_read1.sub.fastq
processing  PV14_18810_ACTTGA_read2.sub.fastq
processing  PV150_23940_GCCAAG_read1.sub.fastq
processing  PV150_23940_GCCAAG_read2.sub.fastq
processing  PV151_23941_AACTTA_read1.sub.fastq
processing  PV151_23941_AACTTA_read2.sub.fastq
processing  PV152_23942_GCCTGA_read1.sub.fastq
processing  PV152_23942_GCCTGA_read2.sub.fastq
processing  PV153_23943_CGTAGA_read1.sub.fastq
processing  PV153_23943_CGTAGA_read2.sub.fastq
processing  PV154_23944_GTTGCA_read1.sub.fastq
processing  PV154_23944_GTTGCA_read2.sub.fastq
processing  PV155_23945_CAGGCT_read1.sub.fastq
processing  PV155_23945_CAGGCT_read2.sub.fastq
processing  PV156_23946_AGGTCG_read1.sub.fastq
processing  PV156_23946_AGGTCG_read2.sub.fastq
processing  PV157_23947_ATTGAG_read1.sub.fastq
processing  PV157_23947_ATTGAG_read2.sub.fastq
processing  PV158_23948_GCCATT_read1.sub.fastq
processing  PV158_23948_GCCATT_read2.sub.fastq
processing  PV159_24630_CGTTGG_read1.sub.fastq
processing  PV159_24630_CGTTGG_read2.sub.fastq
processing  PV160_24631_GTTCGG_read1.sub.fastq
processing  PV160_24631_GTTCGG_read2.sub.fastq
processing  PV161_24632_TGGCGG_read1.sub.fastq
processing  PV161_24632_TGGCGG_read2.sub.fastq
processing  PV162_24633_AACCGG_read1.sub.fastq
processing  PV162_24633_AACCGG_read2.sub.fastq
processing  PV163_24634_CTGAGG_read1.sub.fastq
processing  PV163_24634_CTGAGG_read2.sub.fastq
processing  PV164_24635_ACTTCG_read1.sub.fastq
processing  PV164_24635_ACTTCG_read2.sub.fastq
processing  PV165_24636_TAGTCG_read1.sub.fastq
processing  PV165_24636_TAGTCG_read2.sub.fastq
processing  PV166_24637_TGGTTC_read1.sub.fastq
processing  PV166_24637_TGGTTC_read2.sub.fastq
processing  PV167_24862_GTCTTC_read1.sub.fastq
processing  PV167_24862_GTCTTC_read2.sub.fastq
processing  PV168_24639_ATTCTC_read1.sub.fastq
processing  PV168_24639_ATTCTC_read2.sub.fastq
processing  PV169_24640_CGGTTG_read1.sub.fastq
processing  PV169_24640_CGGTTG_read2.sub.fastq
processing  PV16_16718_ACTGAT_read1.sub.fastq
processing  PV16_16718_ACTGAT_read2.sub.fastq
processing  PV170_24641_ATCTTG_read1.sub.fastq
processing  PV170_24641_ATCTTG_read2.sub.fastq
processing  PV171_24642_TAATTG_read1.sub.fastq
processing  PV171_24642_TAATTG_read2.sub.fastq
processing  PV172_24643_CATTCG_read1.sub.fastq
processing  PV172_24643_CATTCG_read2.sub.fastq
processing  PV173_24644_GCTCCA_read1.sub.fastq
processing  PV173_24644_GCTCCA_read2.sub.fastq
processing  PV174_24645_CCGGTT_read1.sub.fastq
processing  PV174_24645_CCGGTT_read2.sub.fastq
processing  PV175_24646_TCGCAT_read1.sub.fastq
processing  PV175_24646_TCGCAT_read2.sub.fastq
processing  PV176_24647_CATAAC_read1.sub.fastq
processing  PV176_24647_CATAAC_read2.sub.fastq
processing  PV177_24648_ATCGAT_read1.sub.fastq
processing  PV177_24648_ATCGAT_read2.sub.fastq
processing  PV178_24649_AATCCG_read1.sub.fastq
processing  PV178_24649_AATCCG_read2.sub.fastq
processing  PV179_24650_GGCCTC_read1.sub.fastq
processing  PV179_24650_GGCCTC_read2.sub.fastq
processing  PV180_24651_GGAAGA_read1.sub.fastq
processing  PV180_24651_GGAAGA_read2.sub.fastq
processing  PV181_24652_TAAGAA_read1.sub.fastq
processing  PV181_24652_TAAGAA_read2.sub.fastq
processing  PV182_24653_GCTAAC_read1.sub.fastq
processing  PV182_24653_GCTAAC_read2.sub.fastq
processing  PV183_24654_TGACCA_read1.sub.fastq
processing  PV183_24654_TGACCA_read2.sub.fastq
processing  PV184_24655_GCAACG_read1.sub.fastq
processing  PV184_24655_GCAACG_read2.sub.fastq
processing  PV185_24656_TTCAAG_read1.sub.fastq
processing  PV185_24656_TTCAAG_read2.sub.fastq
processing  PV186_24657_CAACTA_read1.sub.fastq
processing  PV186_24657_CAACTA_read2.sub.fastq
processing  PV187_24658_GACTAA_read1.sub.fastq
processing  PV187_24658_GACTAA_read2.sub.fastq
processing  PV188_24659_ATAATT_read1.sub.fastq
processing  PV188_24659_ATAATT_read2.sub.fastq
processing  PV189_24660_TCGAGT_read1.sub.fastq
processing  PV189_24660_TCGAGT_read2.sub.fastq
processing  PV190_24661_TCAGAT_read1.sub.fastq
processing  PV190_24661_TCAGAT_read2.sub.fastq
processing  PV191_24662_GCCAAG_read1.sub.fastq
processing  PV191_24662_GCCAAG_read2.sub.fastq
processing  PV192_24663_AACTTA_read1.sub.fastq
processing  PV192_24663_AACTTA_read2.sub.fastq
processing  PV193_24664_GCCTGA_read1.sub.fastq
processing  PV193_24664_GCCTGA_read2.sub.fastq
processing  PV194_24665_CGTAGA_read1.sub.fastq
processing  PV194_24665_CGTAGA_read2.sub.fastq
processing  PV195_24666_GTTGCA_read1.sub.fastq
processing  PV195_24666_GTTGCA_read2.sub.fastq
processing  PV196_24820_ATTCTC_read1.sub.fastq
processing  PV196_24820_ATTCTC_read2.sub.fastq
processing  PV197_24821_CGGTTG_read1.sub.fastq
processing  PV197_24821_CGGTTG_read2.sub.fastq
processing  PV198_24822_ATCTTG_read1.sub.fastq
processing  PV198_24822_ATCTTG_read2.sub.fastq
processing  PV199_24823_TAATTG_read1.sub.fastq
processing  PV199_24823_TAATTG_read2.sub.fastq
processing  PV1_18807_ATCACG_read1.sub.fastq
processing  PV1_18807_ATCACG_read2.sub.fastq
processing  PV200_24824_CATTCG_read1.sub.fastq
processing  PV200_24824_CATTCG_read2.sub.fastq
processing  PV201_24825_GCTTAG_read1.sub.fastq
processing  PV201_24825_GCTTAG_read2.sub.fastq
processing  PV202_24826_CCGGTT_read1.sub.fastq
processing  PV202_24826_CCGGTT_read2.sub.fastq
processing  PV203_24827_GATGGT_read1.sub.fastq
processing  PV203_24827_GATGGT_read2.sub.fastq
processing  PV204_24828_AGAGGT_read1.sub.fastq
processing  PV204_24828_AGAGGT_read2.sub.fastq
processing  PV205_24829_AGTTGC_read1.sub.fastq
processing  PV205_24829_AGTTGC_read2.sub.fastq
processing  PV206_24830_CTTCCA_read1.sub.fastq
processing  PV206_24830_CTTCCA_read2.sub.fastq
processing  PV207_24831_TGACTT_read1.sub.fastq
processing  PV207_24831_TGACTT_read2.sub.fastq
processing  PV208_24832_TAAGAT_read1.sub.fastq
processing  PV208_24832_TAAGAT_read2.sub.fastq
processing  PV209_24833_AGGATC_read1.sub.fastq
processing  PV209_24833_AGGATC_read2.sub.fastq
processing  PV210_24834_ACTTAC_read1.sub.fastq
processing  PV210_24834_ACTTAC_read2.sub.fastq
processing  PV211_24835_TCGCTA_read1.sub.fastq
processing  PV211_24835_TCGCTA_read2.sub.fastq
processing  PV212_24836_CAAGGA_read1.sub.fastq
processing  PV212_24836_CAAGGA_read2.sub.fastq
processing  PV213_24837_ATGAGA_read1.sub.fastq
processing  PV213_24837_ATGAGA_read2.sub.fastq
processing  PV214_24838_TTGGCA_read1.sub.fastq
processing  PV214_24838_TTGGCA_read2.sub.fastq
processing  PV215_24839_TGGATT_read1.sub.fastq
processing  PV215_24839_TGGATT_read2.sub.fastq
processing  PV216_24840_GACCGT_read1.sub.fastq
processing  PV216_24840_GACCGT_read2.sub.fastq
processing  PV217_24841_CCGTTG_read1.sub.fastq
processing  PV217_24841_CCGTTG_read2.sub.fastq
processing  PV218_24842_TGCCTA_read1.sub.fastq
processing  PV218_24842_TGCCTA_read2.sub.fastq
processing  PV219_24843_TCGAAC_read1.sub.fastq
processing  PV219_24843_TCGAAC_read2.sub.fastq
processing  PV220_24844_CAGAGA_read1.sub.fastq
processing  PV220_24844_CAGAGA_read2.sub.fastq
processing  PV221_24845_GCCATT_read1.sub.fastq
processing  PV221_24845_GCCATT_read2.sub.fastq
processing  PV222_24846_TCCTCT_read1.sub.fastq
processing  PV222_24846_TCCTCT_read2.sub.fastq
processing  PV223_24847_CCTGCT_read1.sub.fastq
processing  PV223_24847_CCTGCT_read2.sub.fastq
processing  PV224_24848_AGGACT_read1.sub.fastq
processing  PV224_24848_AGGACT_read2.sub.fastq
processing  PV225_24849_CGCAGG_read1.sub.fastq
processing  PV225_24849_CGCAGG_read2.sub.fastq
processing  PV226_24850_ACCTTC_read1.sub.fastq
processing  PV226_24850_ACCTTC_read2.sub.fastq
processing  PV227_24851_TGCGTC_read1.sub.fastq
processing  PV227_24851_TGCGTC_read2.sub.fastq
processing  PV228_24852_CGTCGC_read1.sub.fastq
processing  PV228_24852_CGTCGC_read2.sub.fastq
processing  PV229_24853_TAACGC_read1.sub.fastq
processing  PV229_24853_TAACGC_read2.sub.fastq
processing  PV22_22501_TTAGGC_read1.sub.fastq
processing  PV22_22501_TTAGGC_read2.sub.fastq
processing  PV230_24854_TCATAC_read1.sub.fastq
processing  PV230_24854_TCATAC_read2.sub.fastq
processing  PV231_24855_CAGGAC_read1.sub.fastq
processing  PV231_24855_CAGGAC_read2.sub.fastq
processing  PV232_24856_GTCAAC_read1.sub.fastq
processing  PV232_24856_GTCAAC_read2.sub.fastq
processing  PV233_24857_TCATCG_read1.sub.fastq
processing  PV233_24857_TCATCG_read2.sub.fastq
processing  PV234_24858_GTCGCG_read1.sub.fastq
processing  PV234_24858_GTCGCG_read2.sub.fastq
processing  PV235_24859_GTTCAG_read1.sub.fastq
processing  PV235_24859_GTTCAG_read2.sub.fastq
processing  PV236_24860_AGCTCC_read1.sub.fastq
processing  PV236_24860_AGCTCC_read2.sub.fastq
processing  PV237_24861_GGAGCC_read1.sub.fastq
processing  PV237_24861_GGAGCC_read2.sub.fastq
processing  PV23_22502_TGACCA_read1.sub.fastq
processing  PV23_22502_TGACCA_read2.sub.fastq
processing  PV24_18194_ACAGTG_read1.sub.fastq
processing  PV24_18194_ACAGTG_read2.sub.fastq
processing  PV252_31210_TCCTCT_read1.sub.fastq
processing  PV252_31210_TCCTCT_read2.sub.fastq
processing  PV257_31192_CCTGCT_read1.sub.fastq
processing  PV257_31192_CCTGCT_read2.sub.fastq
processing  PV25_22503_ACAGTG_read1.sub.fastq
processing  PV25_22503_ACAGTG_read2.sub.fastq
processing  PV262_31175_TCGCTA_read1.sub.fastq
processing  PV262_31175_TCGCTA_read2.sub.fastq
processing  PV268_31215_CCGCAA_read1.sub.fastq
processing  PV268_31215_CCGCAA_read2.sub.fastq
processing  PV269_31186_ACCTTC_read1.sub.fastq
processing  PV269_31186_ACCTTC_read2.sub.fastq
processing  PV26_18196_CTTGTA_read1.sub.fastq
processing  PV26_18196_CTTGTA_read2.sub.fastq
processing  PV270_31184_TGGATT_read1.sub.fastq
processing  PV270_31184_TGGATT_read2.sub.fastq
processing  PV277_31188_TCATAC_read1.sub.fastq
processing  PV277_31188_TCATAC_read2.sub.fastq
processing  PV27_22504_GCCAAT_read1.sub.fastq
processing  PV27_22504_GCCAAT_read2.sub.fastq
processing  PV28_22505_CAGATC_read1.sub.fastq
processing  PV28_22505_CAGATC_read2.sub.fastq
processing  PV296_31200_CCGGTT_read1.sub.fastq
processing  PV296_31200_CCGGTT_read2.sub.fastq
processing  PV298_31217_TTAGTT_read1.sub.fastq
processing  PV298_31217_TTAGTT_read2.sub.fastq
processing  PV2_18808_TGACCA_read1.sub.fastq
processing  PV2_18808_TGACCA_read2.sub.fastq
processing  PV306_31190_CCGTTG_read1.sub.fastq
processing  PV306_31190_CCGTTG_read2.sub.fastq
processing  PV312_31189_CAGGAC_read1.sub.fastq
processing  PV312_31189_CAGGAC_read2.sub.fastq
processing  PV313_31183_GTCGCG_read1.sub.fastq
processing  PV313_31183_GTCGCG_read2.sub.fastq
processing  PV31_22508_CTTGTA_read1.sub.fastq
processing  PV31_22508_CTTGTA_read2.sub.fastq
processing  PV32_22509_CGTACG_read1.sub.fastq
processing  PV32_22509_CGTACG_read2.sub.fastq
processing  PV330_31216_ATAGGA_read1.sub.fastq
processing  PV330_31216_ATAGGA_read2.sub.fastq
processing  PV34_18815_GATCAG_read1.sub.fastq
processing  PV34_18815_GATCAG_read2.sub.fastq
processing  PV350_31174_CGCAGG_read1.sub.fastq
processing  PV350_31174_CGCAGG_read2.sub.fastq
processing  PV352_31179_TGACTT_read1.sub.fastq
processing  PV352_31179_TGACTT_read2.sub.fastq
processing  PV356_31211_TAAGAT_read1.sub.fastq
processing  PV356_31211_TAAGAT_read2.sub.fastq
processing  PV359_31218_GCTAAC_read1.sub.fastq
processing  PV359_31218_GCTAAC_read2.sub.fastq
processing  PV35_22510_ACTGAT_read1.sub.fastq
processing  PV35_22510_ACTGAT_read2.sub.fastq
processing  PV369_31176_GGAGCC_read1.sub.fastq
processing  PV369_31176_GGAGCC_read2.sub.fastq
processing  PV36_18197_AGTTCC_read1.sub.fastq
processing  PV36_18197_AGTTCC_read2.sub.fastq
processing  PV37_18195_GCCAAT_read1.sub.fastq
processing  PV37_18195_GCCAAT_read2.sub.fastq
processing  PV380_31214_TAGTCG_read1.sub.fastq
processing  PV380_31214_TAGTCG_read2.sub.fastq
processing  PV386_31177_ATCTTG_read1.sub.fastq
processing  PV386_31177_ATCTTG_read2.sub.fastq
processing  PV390_31196_CAGAGA_read1.sub.fastq
processing  PV390_31196_CAGAGA_read2.sub.fastq
processing  PV3_16716_GGCTAC_read1.sub.fastq
processing  PV3_16716_GGCTAC_read2.sub.fastq
processing  PV418_31181_ACTTAC_read1.sub.fastq
processing  PV418_31181_ACTTAC_read2.sub.fastq
processing  PV41_18199_GAGTGG_read1.sub.fastq
processing  PV41_18199_GAGTGG_read2.sub.fastq
processing  PV421_31185_AGTTGC_read1.sub.fastq
processing  PV421_31185_AGTTGC_read2.sub.fastq
processing  PV423_31205_TTCTGG_read1.sub.fastq
processing  PV423_31205_TTCTGG_read2.sub.fastq
processing  PV426_31195_AGGATC_read1.sub.fastq
processing  PV426_31195_AGGATC_read2.sub.fastq
processing  PV428_31201_CATTCG_read1.sub.fastq
processing  PV428_31201_CATTCG_read2.sub.fastq
processing  PV42_22511_ATTCCT_read1.sub.fastq
processing  PV42_22511_ATTCCT_read2.sub.fastq
processing  PV430_31197_TGCGTC_read1.sub.fastq
processing  PV430_31197_TGCGTC_read2.sub.fastq
processing  PV437_31173_GTTCAG_read1.sub.fastq
processing  PV437_31173_GTTCAG_read2.sub.fastq
processing  PV440_31193_GCCATT_read1.sub.fastq
processing  PV440_31193_GCCATT_read2.sub.fastq
processing  PV441_31206_TCATCG_read1.sub.fastq
processing  PV441_31206_TCATCG_read2.sub.fastq
processing  PV454_31191_GCTTAG_read1.sub.fastq
processing  PV454_31191_GCTTAG_read2.sub.fastq
processing  PV457_31198_AGCTCC_read1.sub.fastq
processing  PV457_31198_AGCTCC_read2.sub.fastq
processing  PV464_31209_GACCGT_read1.sub.fastq
processing  PV464_31209_GACCGT_read2.sub.fastq
processing  PV46_18814_GTGGCC_read1.sub.fastq
processing  PV46_18814_GTGGCC_read2.sub.fastq
processing  PV473_31182_CGTCGC_read1.sub.fastq
processing  PV473_31182_CGTCGC_read2.sub.fastq
processing  PV47_18811_GTCCGC_read1.sub.fastq
processing  PV47_18811_GTCCGC_read2.sub.fastq
processing  PV48_18198_GTGAAA_read1.sub.fastq
processing  PV48_18198_GTGAAA_read2.sub.fastq

In [156]:
extract_records = get_all_samples_from_type('3', verbose=False)
extract_records = [dict(record_id=item['data']['id'], sample_id=item['data']['attributes']['attribute_map']['RNA extract code']) for item in extract_records]
extract_records = pd.DataFrame.from_records(extract_records)
extract_records

    record_id     sample_id
0         391     RNA-PV001
1         392     RNA-PV002
2         393     RNA-PV003
3         394  RNA-PV003bgi
4         395  RNA-PV004bgi
..        ...           ...
307       698     RNA-PV586
308       699     RNA-PV587
309       700     RNA-PV588
310       701     RNA-PV589
311       702     RNA-PV590

[312 rows x 2 columns]

In [161]:
print('\n'.join(extract_records.sample_id.to_list()))

RNA-PV001
RNA-PV002
RNA-PV003
RNA-PV003bgi
RNA-PV004bgi
RNA-PV005bgi
RNA-PV006bgi
RNA-PV007bgi
RNA-PV008bgi
RNA-PV009
RNA-PV009bgi
RNA-PV010bgi
RNA-PV011
RNA-PV012bgi
RNA-PV013bgi
RNA-PV014
RNA-PV015bgi
RNA-PV016
RNA-PV017bgi
RNA-PV018bgi
RNA-PV020bgi
RNA-PV021bgi
RNA-PV022
RNA-PV023
RNA-PV024
RNA-PV025
RNA-PV026
RNA-PV027
RNA-PV028
RNA-PV029
RNA-PV030
RNA-PV031
RNA-PV032
RNA-PV033
RNA-PV034
RNA-PV035
RNA-PV036
RNA-PV037
RNA-PV041
RNA-PV042
RNA-PV046
RNA-PV047
RNA-PV048
RNA-PV049
RNA-PV050
RNA-PV051
RNA-PV052
RNA-PV053
RNA-PV054
RNA-PV055
RNA-PV056
RNA-PV057
RNA-PV058
RNA-PV059
RNA-PV060
RNA-PV061
RNA-PV062
RNA-PV063
RNA-PV064
RNA-PV065
RNA-PV066
RNA-PV068
RNA-PV069
RNA-PV070
RNA-PV071
RNA-PV072
RNA-PV074
RNA-PV075
RNA-PV076
RNA-PV078
RNA-PV079
RNA-PV080
RNA-PV081
RNA-PV082
RNA-PV083
RNA-PV084
RNA-PV085
RNA-PV086
RNA-PV087
RNA-PV088
RNA-PV089
RNA-PV090
RNA-PV091
RNA-PV092
RNA-PV093
RNA-PV094
RNA-PV095
RNA-PV096
RNA-PV097
RNA-PV098
RNA-PV099
RNA-PV100
RNA-PV101
RNA-PV102
RNA-PV103
RNA-PV104
RNA-PV105
RNA-PV106
RNA-PV107
RNA-PV108
RNA-PV109
RNA-PV110
RNA-PV112
RNA-PV113
RNA-PV114
RNA-PV115
RNA-PV116
RNA-PV117
RNA-PV118
RNA-PV119
RNA-PV120
RNA-PV121
RNA-PV122
RNA-PV123
RNA-PV124
RNA-PV125
RNA-PV126
RNA-PV127
RNA-PV128
RNA-PV129
RNA-PV130
RNA-PV131
RNA-PV132
RNA-PV133
RNA-PV134
RNA-PV135
RNA-PV136
RNA-PV137
RNA-PV138
RNA-PV139
RNA-PV140
RNA-PV141
RNA-PV142
RNA-PV143
RNA-PV144
RNA-PV145
RNA-PV146
RNA-PV147
RNA-PV148
RNA-PV149
RNA-PV150
RNA-PV151
RNA-PV152
RNA-PV153
RNA-PV154
RNA-PV155
RNA-PV156
RNA-PV157
RNA-PV158
RNA-PV159
RNA-PV160
RNA-PV161
RNA-PV162
RNA-PV163
RNA-PV164
RNA-PV165
RNA-PV166
RNA-PV167
RNA-PV168
RNA-PV169
RNA-PV170
RNA-PV171
RNA-PV172
RNA-PV173
RNA-PV174
RNA-PV175
RNA-PV176
RNA-PV177
RNA-PV178
RNA-PV179
RNA-PV180
RNA-PV181
RNA-PV182
RNA-PV183
RNA-PV184
RNA-PV185
RNA-PV186
RNA-PV187
RNA-PV188
RNA-PV189
RNA-PV190
RNA-PV191
RNA-PV192
RNA-PV193
RNA-PV194
RNA-PV195
RNA-PV196
RNA-PV197
RNA-PV198
RNA-PV199
RNA-PV200
RNA-PV201
RNA-PV202
RNA-PV203
RNA-PV204
RNA-PV205
RNA-PV206
RNA-PV207
RNA-PV208
RNA-PV209
RNA-PV210
RNA-PV211
RNA-PV212
RNA-PV213
RNA-PV214
RNA-PV215
RNA-PV216
RNA-PV217
RNA-PV218
RNA-PV219
RNA-PV220
RNA-PV221
RNA-PV222
RNA-PV223
RNA-PV224
RNA-PV225
RNA-PV226
RNA-PV227
RNA-PV228
RNA-PV229
RNA-PV230
RNA-PV231
RNA-PV232
RNA-PV233
RNA-PV234
RNA-PV235
RNA-PV236
RNA-PV237
RNA-PV252
RNA-PV257
RNA-PV262
RNA-PV268
RNA-PV269
RNA-PV270
RNA-PV277
RNA-PV296
RNA-PV298
RNA-PV306
RNA-PV312
RNA-PV313
RNA-PV330
RNA-PV350
RNA-PV352
RNA-PV356
RNA-PV359
RNA-PV369
RNA-PV380
RNA-PV386
RNA-PV390
RNA-PV418
RNA-PV421
RNA-PV423
RNA-PV426
RNA-PV428
RNA-PV430
RNA-PV437
RNA-PV440
RNA-PV441
RNA-PV454
RNA-PV457
RNA-PV464
RNA-PV473
RNA-PV489
RNA-PV491
RNA-PV495
RNA-PV496
RNA-PV498
RNA-PV500
RNA-PV501
RNA-PV503
RNA-PV505
RNA-PV514
RNA-PV516
RNA-PV519
RNA-PV525
RNA-PV526
RNA-PV527
RNA-PV529
RNA-PV534
RNA-PV535
RNA-PV538
RNA-PV540
RNA-PV544
RNA-PV546
RNA-PV551
RNA-PV553
RNA-PV554
RNA-PV556
RNA-PV557
RNA-PV558
RNA-PV559
RNA-PV560
RNA-PV563
RNA-PV564
RNA-PV565
RNA-PV567
RNA-PV572
RNA-PV573
RNA-PV574
RNA-PV575
RNA-PV576
RNA-PV579
RNA-PV580
RNA-PV581
RNA-PV583
RNA-PV584
RNA-PV585
RNA-PV586
RNA-PV587
RNA-PV588
RNA-PV589
RNA-PV590

In [140]:
def get_all_files(verbose:bool=True):
    
    try:
        files = requests.get(f"{api_url}/data_files/", headers=headers).json()['data']
    except KeyError:
        raise IOError(f"Is {sample_type_id} defined??")
    out = []    
    for file in files:
        out.append(
            dict(
                record_id=file['id'],
                title=file['attributes']['title']
            )
        )
    
    return out

all_file_records = get_all_files()
all_file_records = pd.DataFrame.from_records(all_file_records)
all_file_records

    record_id                               title
0         582   PV99_22335_GAGTGG_read2.sub.fastq
1         581   PV99_22335_GAGTGG_read1.sub.fastq
2         580   PV98_22334_CGTACG_read2.sub.fastq
3         579   PV98_22334_CGTACG_read1.sub.fastq
4         578   PV97_22531_GTTTCG_read2.sub.fastq
..        ...                                 ...
571        11  PV053_22520_AGTTCC_read1.sub.fastq
572        10  PV052_22519_AGTCAA_read2.sub.fastq
573         9  PV052_22519_AGTCAA_read1.sub.fastq
574         8  PV051_22518_ACTTGA_read2.sub.fastq
575         7  PV051_22518_ACTTGA_read1.sub.fastq

[576 rows x 2 columns]

In [142]:
all_file_records_index = all_file_records.set_index('title')['record_id'].to_dict()

In [144]:
files_pvt

strand,Library code,Primers,read1,read2
0,PV051,ACTTGA,PV051_22518_ACTTGA_read1.sub.fastq,PV051_22518_ACTTGA_read2.sub.fastq
1,PV052,AGTCAA,PV052_22519_AGTCAA_read1.sub.fastq,PV052_22519_AGTCAA_read2.sub.fastq
2,PV053,AGTTCC,PV053_22520_AGTTCC_read1.sub.fastq,PV053_22520_AGTTCC_read2.sub.fastq
3,PV054,ATGTCA,PV054_22521_ATGTCA_read1.sub.fastq,PV054_22521_ATGTCA_read2.sub.fastq
4,PV056,GTGGCC,PV056_22523_GTGGCC_read1.sub.fastq,PV056_22523_GTGGCC_read2.sub.fastq
...,...,...,...,...
283,PV95,GTGAAA,PV95_22331_GTGAAA_read1.sub.fastq,PV95_22331_GTGAAA_read2.sub.fastq
284,PV96,GTGGCC,PV96_22332_GTGGCC_read1.sub.fastq,PV96_22332_GTGGCC_read2.sub.fastq
285,PV97,GTTTCG,PV97_22531_GTTTCG_read1.sub.fastq,PV97_22531_GTTTCG_read2.sub.fastq
286,PV98,CGTACG,PV98_22334_CGTACG_read1.sub.fastq,PV98_22334_CGTACG_read2.sub.fastq
287,PV99,GAGTGG,PV99_22335_GAGTGG_read1.sub.fastq,PV99_22335_GAGTGG_read2.sub.fastq

In [157]:
# extract_records = pd.DataFrame(extract_records, columns=['sample_id', 'Extract record id'])
extract_records['Library code'] = extract_records['sample_id'].apply(lambda x: x.replace('RNA-', ''))
extract_records

    record_id     sample_id Library code
0         391     RNA-PV001        PV001
1         392     RNA-PV002        PV002
2         393     RNA-PV003        PV003
3         394  RNA-PV003bgi     PV003bgi
4         395  RNA-PV004bgi     PV004bgi
..        ...           ...          ...
307       698     RNA-PV586        PV586
308       699     RNA-PV587        PV587
309       700     RNA-PV588        PV588
310       701     RNA-PV589        PV589
311       702     RNA-PV590        PV590

[312 rows x 3 columns]

In [167]:
files_pvt['read1_id'] = files_pvt['read1'].apply(lambda x: all_file_records_index[x])
files_pvt['read2_id'] = files_pvt['read2'].apply(lambda x: all_file_records_index[x])
files_pvt['Library code'] = files_pvt['Library code'].apply(lambda x: 'PV{:03d}'.format(int(x.replace('PV', ''))))
files_pvt = pd.merge(files_pvt, extract_records, on='Library code', how='left')

In [174]:
extract_records

    record_id     sample_id Library code
0         391     RNA-PV001        PV001
1         392     RNA-PV002        PV002
2         393     RNA-PV003        PV003
3         394  RNA-PV003bgi     PV003bgi
4         395  RNA-PV004bgi     PV004bgi
..        ...           ...          ...
307       698     RNA-PV586        PV586
308       699     RNA-PV587        PV587
309       700     RNA-PV588        PV588
310       701     RNA-PV589        PV589
311       702     RNA-PV590        PV590

[312 rows x 3 columns]

In [ ]:
files_pvt[files_pvt['record_id'].isna()]

,Library code,Primers,read1,read2,read1_id,read2_id,record_id,sample_id
30,PV111,TAGCTT,PV111_22766_TAGCTT_read1.sub.fastq,PV111_22766_TAGCTT_read2.sub.fastq,63,64,NaN,NaN
229,PV561,ACTTCG,PV561_03636AAB_ACTTCG_read1.sub.fastq,PV561_03636AAB_ACTTCG_read2.sub.fastq,465,466,NaN,NaN
230,PV562,AATGCA,PV562_03637AAB_AATGCA_read1.sub.fastq,PV562_03637AAB_AATGCA_read2.sub.fastq,467,468,NaN,NaN
234,PV566,AACCGG,PV566_03641AAB_AACCGG_read1.sub.fastq,PV566_03641AAB_AACCGG_read2.sub.fastq,475,476,NaN,NaN
236,PV568,CCTAAC,PV568_03643AAB_CCTAAC_read1.sub.fastq,PV568_03643AAB_CCTAAC_read2.sub.fastq,479,480,NaN,NaN
237,PV569,CGTTGG,PV569_03644AAB_CGTTGG_read1.sub.fastq,PV569_03644AAB_CGTTGG_read2.sub.fastq,481,482,NaN,NaN
238,PV570,GTTCAG,PV570_03645AAB_GTTCAG_read1.sub.fastq,PV570_03645AAB_GTTCAG_read2.sub.fastq,483,484,NaN,NaN
239,PV571,CGCAGG,PV571_03646AAB_CGCAGG_read1.sub.fastq,PV571_03646AAB_CGCAGG_read2.sub.fastq,485,486,NaN,NaN
245,PV577,TGCCTA,PV577_03652AAB_TGCCTA_read1.sub.fastq,PV577_03652AAB_TGCCTA_read2.sub.fastq,497,498,NaN,NaN
246,PV578,GCAACG,PV578_03653AAB_GCAACG_read1.sub.fastq,PV578_03653AAB_GCAACG_read2.sub.fastq,499,500,NaN,NaN
250,PV582,CGTCGC,PV582_03657AAB_CGTCGC_read1.sub.fastq,PV582_03657AAB_CGTCGC_read2.sub.fastq,507,508,NaN,NaN
261,PV067,CTTGTA,PV67_21354_CTTGTA_read1.sub.fastq,PV67_21354_CTTGTA_read2.sub.fastq,529,530,NaN,NaN

In [176]:
files_pvt['Reads code'] = files_pvt['Library code'].apply(lambda x: f'reads-{x}')
files_pvt

,Library code,Primers,read1,read2,read1_id,read2_id,record_id,sample_id,Reads code
0,PV051,ACTTGA,PV051_22518_ACTTGA_read1.sub.fastq,PV051_22518_ACTTGA_read2.sub.fastq,7,8,436,RNA-PV051,reads-PV051
1,PV052,AGTCAA,PV052_22519_AGTCAA_read1.sub.fastq,PV052_22519_AGTCAA_read2.sub.fastq,9,10,437,RNA-PV052,reads-PV052
2,PV053,AGTTCC,PV053_22520_AGTTCC_read1.sub.fastq,PV053_22520_AGTTCC_read2.sub.fastq,11,12,438,RNA-PV053,reads-PV053
3,PV054,ATGTCA,PV054_22521_ATGTCA_read1.sub.fastq,PV054_22521_ATGTCA_read2.sub.fastq,13,14,439,RNA-PV054,reads-PV054
4,PV056,GTGGCC,PV056_22523_GTGGCC_read1.sub.fastq,PV056_22523_GTGGCC_read2.sub.fastq,15,16,441,RNA-PV056,reads-PV056
...,...,...,...,...,...,...,...,...,...
283,PV095,GTGAAA,PV95_22331_GTGAAA_read1.sub.fastq,PV95_22331_GTGAAA_read2.sub.fastq,571,572,477,RNA-PV095,reads-PV095
284,PV096,GTGGCC,PV96_22332_GTGGCC_read1.sub.fastq,PV96_22332_GTGGCC_read2.sub.fastq,575,576,478,RNA-PV096,reads-PV096
285,PV097,GTTTCG,PV97_22531_GTTTCG_read1.sub.fastq,PV97_22531_GTTTCG_read2.sub.fastq,577,578,479,RNA-PV097,reads-PV097
286,PV098,CGTACG,PV98_22334_CGTACG_read1.sub.fastq,PV98_22334_CGTACG_read2.sub.fastq,579,580,480,RNA-PV098,reads-PV098
287,PV099,GAGTGG,PV99_22335_GAGTGG_read1.sub.fastq,PV99_22335_GAGTGG_read2.sub.fastq,581,582,481,RNA-PV099,reads-PV099

In [230]:
def create_rawreads_record(entry: Dict[str, Any], project_id: str, people_id: str, sample_type_id: str, assay_id: str):
    attributes = {
        "attribute_map": {
            "Reads code": entry["Reads code"],
            "Extract": entry["record_id"],
            "Forward reads file": entry["read1_id"],
            "Backward reads file": entry["read2_id"],
            "Primers": entry['Primers']
        },
            "tags": [
                "raw read"
            ]
    }
    record = create_record(
        attributes_dict=attributes, project_id=project_id, people_id=people_id,
        sample_type_id=sample_type_id, assay_id=assay_id
    )
    return record

In [231]:
# IMPORTANT TO CHECK THESE ONES BEFORE UPLOAD
people_id = '1'
project_id = '2'
assay_id = '4' # Check these ones carefully
sample_type_id = '4'

create_rawreads_record_ = lambda x: create_rawreads_record(
    x,people_id=people_id, project_id=project_id, assay_id=assay_id, sample_type_id=sample_type_id
)
reads_collection = list(map(create_rawreads_record_, files_pvt.to_dict(orient='records')))
reads_collection[24]

{'data': {'type': 'samples',
  'attributes': {'attribute_map': {'Reads code': 'reads-PV106',
    'Extract': '488',
    'Forward reads file': '53',
    'Backward reads file': '54',
    'Primers': 'TGACCA'},
   'tags': ['raw read']},
  'relationships': {'sample_type': {'data': {'id': '4',
     'type': 'sample_types'}},
   'creators': {'data': [{'id': '1', 'type': 'people'}]},
   'projects': {'data': [{'id': '2', 'type': 'projects'}]},
   'assays': {'data': [{'id': '4', 'type': 'assays'}]}}}}

In [235]:
reads_record = add_samples(reads_collection, "Reads code")

sample # reads-PV051, record 999, added
sample # reads-PV052, record 1000, added
sample # reads-PV053, record 1001, added
sample # reads-PV054, record 1002, added
sample # reads-PV056, record 1003, added
sample # reads-PV057, record 1004, added
sample # reads-PV058, record 1005, added
sample # reads-PV058, record 1006, added
sample # reads-PV062, record 1007, added
sample # reads-PV063, record 1008, added
sample # reads-PV065, record 1009, added
sample # reads-PV066, record 1010, added
sample # reads-PV068, record 1011, added
sample # reads-PV069, record 1012, added
sample # reads-PV072, record 1013, added
sample # reads-PV074, record 1014, added
sample # reads-PV076, record 1015, added
sample # reads-PV001, record 1016, added
sample # reads-PV100, record 1017, added
sample # reads-PV101, record 1018, added
sample # reads-PV102, record 1019, added
sample # reads-PV103, record 1020, added
sample # reads-PV104, record 1021, added
sample # reads-PV105, record 1022, added
sample # reads-PV106, record 1023, added
sample # reads-PV107, record 1024, added
sample # reads-PV108, record 1025, added
sample # reads-PV109, record 1026, added
sample # reads-PV011, record 1027, added
sample # reads-PV110, record 1028, added
sample # reads-PV111, could not be added, ERROR 500
sample # reads-PV112, record 1029, added
sample # reads-PV113, record 1030, added
sample # reads-PV114, record 1031, added
sample # reads-PV115, record 1032, added
sample # reads-PV116, record 1033, added
sample # reads-PV117, record 1034, added
sample # reads-PV118, record 1035, added
sample # reads-PV119, record 1036, added
sample # reads-PV120, record 1037, added
sample # reads-PV121, record 1038, added
sample # reads-PV122, record 1039, added
sample # reads-PV123, record 1040, added
sample # reads-PV124, record 1041, added
sample # reads-PV125, record 1042, added
sample # reads-PV126, record 1043, added
sample # reads-PV127, record 1044, added
sample # reads-PV128, record 1045, added
sample # reads-PV129, record 1046, added
sample # reads-PV130, record 1047, added
sample # reads-PV131, record 1048, added
sample # reads-PV132, record 1049, added
sample # reads-PV133, record 1050, added
sample # reads-PV134, record 1051, added
sample # reads-PV135, record 1052, added
sample # reads-PV136, record 1053, added
sample # reads-PV137, record 1054, added
sample # reads-PV138, record 1055, added
sample # reads-PV139, record 1056, added
sample # reads-PV014, record 1057, added
sample # reads-PV140, record 1058, added
sample # reads-PV141, record 1059, added
sample # reads-PV142, record 1060, added
sample # reads-PV143, record 1061, added
sample # reads-PV144, record 1062, added
sample # reads-PV145, record 1063, added
sample # reads-PV146, record 1064, added
sample # reads-PV147, record 1065, added
sample # reads-PV148, record 1066, added
sample # reads-PV149, record 1067, added
sample # reads-PV150, record 1068, added
sample # reads-PV151, record 1069, added
sample # reads-PV152, record 1070, added
sample # reads-PV153, record 1071, added
sample # reads-PV154, record 1072, added
sample # reads-PV155, record 1073, added
sample # reads-PV156, record 1074, added
sample # reads-PV157, record 1075, added
sample # reads-PV158, record 1076, added
sample # reads-PV159, record 1077, added
sample # reads-PV016, record 1078, added
sample # reads-PV160, record 1079, added
sample # reads-PV161, record 1080, added
sample # reads-PV162, record 1081, added
sample # reads-PV163, record 1082, added
sample # reads-PV164, record 1083, added
sample # reads-PV165, record 1084, added
sample # reads-PV166, record 1085, added
sample # reads-PV167, record 1086, added
sample # reads-PV168, record 1087, added
sample # reads-PV169, record 1088, added
sample # reads-PV170, record 1089, added
sample # reads-PV171, record 1090, added
sample # reads-PV172, record 1091, added
sample # reads-PV173, record 1092, added
sample # reads-PV174, record 1093, added
sample # reads-PV175, record 1094, added
sample # reads-PV176, record 1095, added
sample # reads-PV177, record 1096, added
sample # reads-PV178, record 1097, added
sample # reads-PV179, record 1098, added
sample # reads-PV180, record 1099, added
sample # reads-PV181, record 1100, added
sample # reads-PV182, record 1101, added
sample # reads-PV183, record 1102, added
sample # reads-PV184, record 1103, added
sample # reads-PV185, record 1104, added
sample # reads-PV186, record 1105, added
sample # reads-PV187, record 1106, added
sample # reads-PV188, record 1107, added
sample # reads-PV189, record 1108, added
sample # reads-PV190, record 1109, added
sample # reads-PV191, record 1110, added
sample # reads-PV192, record 1111, added
sample # reads-PV193, record 1112, added
sample # reads-PV194, record 1113, added
sample # reads-PV195, record 1114, added
sample # reads-PV196, record 1115, added
sample # reads-PV197, record 1116, added
sample # reads-PV198, record 1117, added
sample # reads-PV199, record 1118, added
sample # reads-PV002, record 1119, added
sample # reads-PV200, record 1120, added
sample # reads-PV201, record 1121, added
sample # reads-PV202, record 1122, added
sample # reads-PV203, record 1123, added
sample # reads-PV204, record 1124, added
sample # reads-PV205, record 1125, added
sample # reads-PV206, record 1126, added
sample # reads-PV207, record 1127, added
sample # reads-PV208, record 1128, added
sample # reads-PV209, record 1129, added
sample # reads-PV210, record 1130, added
sample # reads-PV211, record 1131, added
sample # reads-PV212, record 1132, added
sample # reads-PV213, record 1133, added
sample # reads-PV214, record 1134, added
sample # reads-PV215, record 1135, added
sample # reads-PV216, record 1136, added
sample # reads-PV217, record 1137, added
sample # reads-PV218, record 1138, added
sample # reads-PV219, record 1139, added
sample # reads-PV022, record 1140, added
sample # reads-PV220, record 1141, added
sample # reads-PV221, record 1142, added
sample # reads-PV222, record 1143, added
sample # reads-PV223, record 1144, added
sample # reads-PV224, record 1145, added
sample # reads-PV225, record 1146, added
sample # reads-PV226, record 1147, added
sample # reads-PV227, record 1148, added
sample # reads-PV228, record 1149, added
sample # reads-PV229, record 1150, added
sample # reads-PV023, record 1151, added
sample # reads-PV230, record 1152, added
sample # reads-PV231, record 1153, added
sample # reads-PV232, record 1154, added
sample # reads-PV233, record 1155, added
sample # reads-PV234, record 1156, added
sample # reads-PV235, record 1157, added
sample # reads-PV236, record 1158, added
sample # reads-PV237, record 1159, added
sample # reads-PV024, record 1160, added
sample # reads-PV025, record 1161, added
sample # reads-PV252, record 1162, added
sample # reads-PV257, record 1163, added
sample # reads-PV026, record 1164, added
sample # reads-PV262, record 1165, added
sample # reads-PV268, record 1166, added
sample # reads-PV269, record 1167, added
sample # reads-PV027, record 1168, added
sample # reads-PV270, record 1169, added
sample # reads-PV277, record 1170, added
sample # reads-PV028, record 1171, added
sample # reads-PV296, record 1172, added
sample # reads-PV298, record 1173, added
sample # reads-PV003, record 1174, added
sample # reads-PV306, record 1175, added
sample # reads-PV031, record 1176, added
sample # reads-PV312, record 1177, added
sample # reads-PV313, record 1178, added
sample # reads-PV032, record 1179, added
sample # reads-PV330, record 1180, added
sample # reads-PV034, record 1181, added
sample # reads-PV035, record 1182, added
sample # reads-PV350, record 1183, added
sample # reads-PV352, record 1184, added
sample # reads-PV356, record 1185, added
sample # reads-PV359, record 1186, added
sample # reads-PV036, record 1187, added
sample # reads-PV369, record 1188, added
sample # reads-PV037, record 1189, added
sample # reads-PV380, record 1190, added
sample # reads-PV386, record 1191, added
sample # reads-PV390, record 1192, added
sample # reads-PV041, record 1193, added
sample # reads-PV418, record 1194, added
sample # reads-PV042, record 1195, added
sample # reads-PV421, record 1196, added
sample # reads-PV423, record 1197, added
sample # reads-PV426, record 1198, added
sample # reads-PV428, record 1199, added
sample # reads-PV430, record 1200, added
sample # reads-PV437, record 1201, added
sample # reads-PV440, record 1202, added
sample # reads-PV441, record 1203, added
sample # reads-PV454, record 1204, added
sample # reads-PV457, record 1205, added
sample # reads-PV046, record 1206, added
sample # reads-PV464, record 1207, added
sample # reads-PV047, record 1208, added
sample # reads-PV473, record 1209, added
sample # reads-PV048, record 1210, added
sample # reads-PV049, record 1211, added
sample # reads-PV495, record 1212, added
sample # reads-PV498, record 1213, added
sample # reads-PV050, record 1214, added
sample # reads-PV500, record 1215, added
sample # reads-PV501, record 1216, added
sample # reads-PV514, record 1217, added
sample # reads-PV516, record 1218, added
sample # reads-PV519, record 1219, added
sample # reads-PV544, record 1220, added
sample # reads-PV546, record 1221, added
sample # reads-PV055, record 1222, added
sample # reads-PV557, record 1223, added
sample # reads-PV558, record 1224, added
sample # reads-PV559, record 1225, added
sample # reads-PV560, record 1226, added
sample # reads-PV561, could not be added, ERROR 500
sample # reads-PV562, could not be added, ERROR 500
sample # reads-PV563, record 1227, added
sample # reads-PV564, record 1228, added
sample # reads-PV565, record 1229, added
sample # reads-PV566, could not be added, ERROR 500
sample # reads-PV567, record 1230, added
sample # reads-PV568, could not be added, ERROR 500
sample # reads-PV569, could not be added, ERROR 500
sample # reads-PV570, could not be added, ERROR 500
sample # reads-PV571, could not be added, ERROR 500
sample # reads-PV572, record 1231, added
sample # reads-PV573, record 1232, added
sample # reads-PV574, record 1233, added
sample # reads-PV575, record 1234, added
sample # reads-PV576, record 1235, added
sample # reads-PV577, could not be added, ERROR 500
sample # reads-PV578, could not be added, ERROR 500
sample # reads-PV579, record 1236, added
sample # reads-PV580, record 1237, added
sample # reads-PV581, record 1238, added
sample # reads-PV582, could not be added, ERROR 500
sample # reads-PV583, record 1239, added
sample # reads-PV584, record 1240, added
sample # reads-PV585, record 1241, added
sample # reads-PV586, record 1242, added
sample # reads-PV587, record 1243, added
sample # reads-PV588, record 1244, added
sample # reads-PV589, record 1245, added
sample # reads-PV060, record 1246, added
sample # reads-PV061, record 1247, added
sample # reads-PV064, record 1248, added
sample # reads-PV067, could not be added, ERROR 500
sample # reads-PV070, record 1249, added
sample # reads-PV071, record 1250, added
sample # reads-PV075, record 1251, added
sample # reads-PV078, record 1252, added
sample # reads-PV079, record 1253, added
sample # reads-PV080, record 1254, added
sample # reads-PV081, record 1255, added
sample # reads-PV082, record 1256, added
sample # reads-PV083, record 1257, added
sample # reads-PV084, record 1258, added
sample # reads-PV085, record 1259, added
sample # reads-PV086, record 1260, added
sample # reads-PV087, record 1261, added
sample # reads-PV088, record 1262, added
sample # reads-PV089, record 1263, added
sample # reads-PV090, record 1264, added
sample # reads-PV091, record 1265, added
sample # reads-PV092, record 1266, added
sample # reads-PV093, record 1267, added
sample # reads-PV094, record 1268, added
sample # reads-PV095, record 1269, added
sample # reads-PV095, record 1270, added
sample # reads-PV096, record 1271, added
sample # reads-PV097, record 1272, added
sample # reads-PV098, record 1273, added
sample # reads-PV099, record 1274, added

In [16]:
def remove_all_samples_from_type(sample_type_id:int, verbose:bool=True):
    try:
        samples_ids = requests.get(f"{api_url}/sample_types/{sample_type_id}", headers=headers).json()['data']['relationships']['samples']['data']
    except KeyError:
        raise IOError(f"Is {sample_type_id} defined??")
    u = []
    for sample in samples_ids:
        for _ in range(5):
            s = requests.delete(f"{api_url}/samples/{sample['id']}", headers=headers)
            time.sleep(0.5)
            if s.status_code == 200:
                break
            elif s.status_code == 500:
                continue
            else:
                break
        if s.status_code == 200 and verbose:
            print("sample with id {0}, removed ".format(sample['id']))
        elif s.status_code == 500 and verbose:
            print("sample with id {0} could not be removed, code{1} ".format(sample['id'], s.status_code))

In [17]:
remove_all_samples_from_type(1)

sample with id 2, removed
sample with id 3, removed
sample with id 4, removed
sample with id 5, removed
sample with id 6, removed
sample with id 7, removed
sample with id 8, removed
sample with id 9, removed
sample with id 10, removed
sample with id 11, removed
sample with id 12, removed
sample with id 13, removed
sample with id 14, removed
sample with id 15, removed
sample with id 16, removed
sample with id 17, removed
sample with id 18, removed
sample with id 19, removed
sample with id 20, removed
sample with id 21, removed
sample with id 22, removed
sample with id 23, removed
sample with id 24, removed
sample with id 25, removed
sample with id 26, removed
sample with id 27, removed
sample with id 28, removed
sample with id 29, removed
sample with id 31, removed
sample with id 32, removed
sample with id 33, removed
sample with id 34, removed
sample with id 35, removed
sample with id 36, removed
sample with id 37, removed
sample with id 38, removed
sample with id 39, removed
sample with id 40, removed
sample with id 41, removed
sample with id 42, removed
sample with id 43, removed
sample with id 44, removed
sample with id 45, removed
sample with id 46, removed
sample with id 47, removed
sample with id 48, removed
sample with id 49, removed
sample with id 50, removed
sample with id 51, removed
sample with id 52, removed
sample with id 53, removed
sample with id 54, removed
sample with id 55, removed
sample with id 56, removed
sample with id 57, removed
sample with id 58, removed
sample with id 59, removed
sample with id 60, removed
sample with id 61, removed
sample with id 62, removed
sample with id 63, removed
sample with id 64, removed
sample with id 65, removed
sample with id 66, removed
sample with id 67, removed
sample with id 68, removed