# MIRIPVIR25 - Draft 00 - Data processing

## Unique identifiers

We will use this extremely simple approach to create unique identifiers: creating a self-incrementing index based on different counters.

In [1]:
import pandas as pd
import requests
import json
import seaborn as sns

In [2]:
class Taxon:
    def __init__(self):
        self.id = 0
    def __call__(self):
        out = "{:012}".format(self.id)
        self.id +=1
        return out

In [3]:
taxonids = Taxon()
hitcodes = Taxon()
hostids = Taxon()

## Step 1 - Libraries and sampling sites

In [4]:
libraries = pd.read_csv("data/mcleish24-TableS2.csv", sep=';')
libraries

    Library_code            Host_taxon Habitat Collection_code  No_extracts
0          PV001         Amaranthus sp    Crop             M1V            8
1          PV002  Convolvulus arvensis    Crop             M1V           11
2          PV003          Cucumis melo    Crop             M1V           13
3       PV003bgi          Cucumis melo    Crop             M1V           13
4       PV004bgi        Cyperus longus    Crop             M1V            7
..           ...                   ...     ...             ...          ...
318        PV586    Fumaria parviflora    Crop             H1P            8
319        PV587   Hirschfeldia incana    Crop             H1P            8
320        PV588       Hordeum vulgare    Crop             H1P            8
321        PV589       Hordeum vulgare    Crop             H1P            8
322        PV590              Zea mays    Crop             Z1V           11

[323 rows x 5 columns]

In [5]:
sampling = pd.read_csv("data/mcleish24-TableS1.csv", sep=';')
sampling = sampling.groupby(['Site_code', 'Collection_code', 'Location', 'Longitude', 'Latitude'], as_index = False)['Date'].apply(list)
sampling

,Site_code,Collection_code,Location,Longitude,Latitude,Date
0,C1,C1F,Aranjuez,-3.593308,40.051302,[1/2/16]
1,C1,C3F,Aranjuez,-3.593308,40.051302,[30/1/17]
2,C2,C2F,Aranjuez,-3.599064,40.043193,[1/2/16]
3,C2,C4F,Aranjuez,-3.599064,40.043193,[30/1/17]
4,E1,E1F,Aranjuez,-3.500323,40.059138,"[19/11/15, 10/11/16]"
5,E1,E1P,Aranjuez,-3.500323,40.059138,"[23/5/16, 3/5/17]"
6,E2,E2F,San Martín de la Vega,-3.536191,40.234966,"[19/11/15, 10/11/16]"
7,E2,E2P,San Martín de la Vega,-3.536191,40.234966,"[23/5/16, 10/5/17]"
8,E3,E3F,Ambite,-3.196057,40.089637,"[1/2/16, 10/11/16]"
9,E3,E3P,Ambite,-3.196057,40.089637,"[31/5/16, 3/5/17]"
10,E4,E4F,Mondéjar,-3.131139,40.494167,"[4/11/15, 27/10/16]"
11,E4,E4P,Mondéjar,-3.131139,40.494167,"[31/5/16, 3/5/17]"
12,H1,H1P,Villaconejos,-3.477574,40.049330,[21/4/16]
13,H1,H4P,Villaconejos,-3.477574,40.049330,[19/4/17]
14,H2,H2P,Villamanrique de Tajo,-3.214026,40.085899,[21/4/16]
15,H2,H5P,Villamanrique de Tajo,-3.214026,40.085899,[19/4/17]
16,H3,H3P,Tielmes,-3.253943,40.245852,[21/4/16]
17,H3,H6P,Tielmes,-3.253943,40.245852,[19/4/17]
18,L1,L1F,Aranjuez,-3.345220,40.031840,"[19/11/15, 10/11/16]"
19,L1,L1P,Aranjuez,-3.345220,40.031840,"[31/3/16, 19/4/17]"
20,L1,L1V,Aranjuez,-3.345220,40.031840,"[16/7/15, 20/7/16]"
21,L2,L2F,Villaconejos,-3.476462,40.048758,"[19/11/15, 10/11/16]"
22,L2,L2P,Villaconejos,-3.476462,40.048758,[31/3/16]
23,L2,L2V,Villaconejos,-3.476462,40.048758,"[16/7/15, 20/7/16]"
24,L3,L3F,Villamanrique de Tajo,-3.125794,40.050352,"[19/11/15, 10/11/16]"
25,L3,L3P,Villamanrique de Tajo,-3.125794,40.050352,"[31/3/16, 19/4/17]"
26,L3,L3V,Villamanrique de Tajo,-3.125794,40.050352,"[24/7/15, 15/7/16]"
27,L4,L4F,Tielmes,-3.252617,40.245459,"[4/11/15, 27/10/16]"
28,L4,L4P,Tielmes,-3.252617,40.245459,"[21/4/16, 16/4/17]"
29,L4,L4V,Tielmes,-3.252617,40.245459,[15/7/16]
30,M1,M1V,Aranjuez,-3.345220,40.031840,[16/7/15]
31,M1,M5V,Aranjuez,-3.345220,40.031840,[20/7/16]
32,M1,M9V,Aranjuez,-3.345220,40.031840,[28/6/17]
33,M2,M2V,Villaconejos,-3.503040,40.050578,[16/7/15]
34,M3,M11V,Villamanrique de Tajo,-3.125000,40.045900,[28/6/17]
35,M3,M3V,Villamanrique de Tajo,-3.125000,40.045900,[24/7/15]
36,M3,M7V,Villamanrique de Tajo,-3.125000,40.045900,[15/7/16]
37,M4,M12V,Villamanrique de Tajo,-3.182801,40.032298,[28/6/17]
38,M4,M4V,Villamanrique de Tajo,-3.182801,40.032298,[24/7/15]
39,M4,M8V,Villamanrique de Tajo,-3.182801,40.032298,[15/7/16]
40,Q1,Q1F,Aranjuez,-3.391830,39.595520,"[8/9/15, 12/9/16]"
41,Q1,Q1P,Aranjuez,-3.391830,39.595520,"[23/5/16, 10/5/17]"
42,Q2,Q2F,San Martín de la Vega,-3.530613,40.225155,"[21/9/15, 20/10/16]"
43,Q2,Q2P,San Martín de la Vega,-3.530613,40.225155,"[23/5/16, 10/5/17]"
44,Q3,Q3F,Ambite,-3.205903,40.320294,"[21/9/15, 27/10/16]"
45,Q3,Q3P,Ambite,-3.205903,40.320294,"[31/5/16, 3/5/17]"
46,Q4,Q4F,Mondéjar,-3.137145,40.345348,"[21/9/15, 27/10/16]"
47,Q4,Q4P,Mondéjar,-3.137145,40.345348,"[31/5/16, 3/5/17]"
48,Z1,Z1V,Villaconejos,-3.476076,40.050052,[16/7/15]
49,Z1,Z3V,Villaconejos,-3.476076,40.050052,[20/7/16]
50,Z2,Z2V,Villamanrique de Tajo,-3.131000,40.044720,[24/7/15]
51,Z2,Z4V,Villamanrique de Tajo,-3.131000,40.044720,[15/7/16]

In [6]:
libraries['Collection_code'] = libraries['Collection_code'].apply(lambda x: x.split("_"))
libraries['Collection_code']

0      [M1V]
1      [M1V]
2      [M1V]
3      [M1V]
4      [M1V]
       ...
318    [H1P]
319    [H1P]
320    [H1P]
321    [H1P]
322    [Z1V]
Name: Collection_code, Length: 323, dtype: object

In [7]:
tmp = libraries.drop_duplicates(subset=['Library_code'])[['Library_code', 'Collection_code']].to_dict(orient='records')
library_collection_code = []
for item in tmp:
    for collection_code in item['Collection_code']:
        library_collection_code.append({"Library_code": item['Library_code'], "Collection_code": collection_code})
library_collection_code = pd.DataFrame.from_records(library_collection_code)
library_collection_code

    Library_code Collection_code
0          PV001             M1V
1          PV002             M1V
2          PV003             M1V
3       PV003bgi             M1V
4       PV004bgi             M1V
..           ...             ...
330        PV586             H1P
331        PV587             H1P
332        PV588             H1P
333        PV589             H1P
334        PV590             Z1V

[335 rows x 2 columns]

In [8]:
library_site = pd.merge(sampling[['Collection_code', 'Site_code']], library_collection_code, on='Collection_code')
library_site = library_site[['Site_code', 'Library_code']].to_dict(orient='records')

In [9]:
sampling

,Site_code,Collection_code,Location,Longitude,Latitude,Date
0,C1,C1F,Aranjuez,-3.593308,40.051302,[1/2/16]
1,C1,C3F,Aranjuez,-3.593308,40.051302,[30/1/17]
2,C2,C2F,Aranjuez,-3.599064,40.043193,[1/2/16]
3,C2,C4F,Aranjuez,-3.599064,40.043193,[30/1/17]
4,E1,E1F,Aranjuez,-3.500323,40.059138,"[19/11/15, 10/11/16]"
5,E1,E1P,Aranjuez,-3.500323,40.059138,"[23/5/16, 3/5/17]"
6,E2,E2F,San Martín de la Vega,-3.536191,40.234966,"[19/11/15, 10/11/16]"
7,E2,E2P,San Martín de la Vega,-3.536191,40.234966,"[23/5/16, 10/5/17]"
8,E3,E3F,Ambite,-3.196057,40.089637,"[1/2/16, 10/11/16]"
9,E3,E3P,Ambite,-3.196057,40.089637,"[31/5/16, 3/5/17]"
10,E4,E4F,Mondéjar,-3.131139,40.494167,"[4/11/15, 27/10/16]"
11,E4,E4P,Mondéjar,-3.131139,40.494167,"[31/5/16, 3/5/17]"
12,H1,H1P,Villaconejos,-3.477574,40.049330,[21/4/16]
13,H1,H4P,Villaconejos,-3.477574,40.049330,[19/4/17]
14,H2,H2P,Villamanrique de Tajo,-3.214026,40.085899,[21/4/16]
15,H2,H5P,Villamanrique de Tajo,-3.214026,40.085899,[19/4/17]
16,H3,H3P,Tielmes,-3.253943,40.245852,[21/4/16]
17,H3,H6P,Tielmes,-3.253943,40.245852,[19/4/17]
18,L1,L1F,Aranjuez,-3.345220,40.031840,"[19/11/15, 10/11/16]"
19,L1,L1P,Aranjuez,-3.345220,40.031840,"[31/3/16, 19/4/17]"
20,L1,L1V,Aranjuez,-3.345220,40.031840,"[16/7/15, 20/7/16]"
21,L2,L2F,Villaconejos,-3.476462,40.048758,"[19/11/15, 10/11/16]"
22,L2,L2P,Villaconejos,-3.476462,40.048758,[31/3/16]
23,L2,L2V,Villaconejos,-3.476462,40.048758,"[16/7/15, 20/7/16]"
24,L3,L3F,Villamanrique de Tajo,-3.125794,40.050352,"[19/11/15, 10/11/16]"
25,L3,L3P,Villamanrique de Tajo,-3.125794,40.050352,"[31/3/16, 19/4/17]"
26,L3,L3V,Villamanrique de Tajo,-3.125794,40.050352,"[24/7/15, 15/7/16]"
27,L4,L4F,Tielmes,-3.252617,40.245459,"[4/11/15, 27/10/16]"
28,L4,L4P,Tielmes,-3.252617,40.245459,"[21/4/16, 16/4/17]"
29,L4,L4V,Tielmes,-3.252617,40.245459,[15/7/16]
30,M1,M1V,Aranjuez,-3.345220,40.031840,[16/7/15]
31,M1,M5V,Aranjuez,-3.345220,40.031840,[20/7/16]
32,M1,M9V,Aranjuez,-3.345220,40.031840,[28/6/17]
33,M2,M2V,Villaconejos,-3.503040,40.050578,[16/7/15]
34,M3,M11V,Villamanrique de Tajo,-3.125000,40.045900,[28/6/17]
35,M3,M3V,Villamanrique de Tajo,-3.125000,40.045900,[24/7/15]
36,M3,M7V,Villamanrique de Tajo,-3.125000,40.045900,[15/7/16]
37,M4,M12V,Villamanrique de Tajo,-3.182801,40.032298,[28/6/17]
38,M4,M4V,Villamanrique de Tajo,-3.182801,40.032298,[24/7/15]
39,M4,M8V,Villamanrique de Tajo,-3.182801,40.032298,[15/7/16]
40,Q1,Q1F,Aranjuez,-3.391830,39.595520,"[8/9/15, 12/9/16]"
41,Q1,Q1P,Aranjuez,-3.391830,39.595520,"[23/5/16, 10/5/17]"
42,Q2,Q2F,San Martín de la Vega,-3.530613,40.225155,"[21/9/15, 20/10/16]"
43,Q2,Q2P,San Martín de la Vega,-3.530613,40.225155,"[23/5/16, 10/5/17]"
44,Q3,Q3F,Ambite,-3.205903,40.320294,"[21/9/15, 27/10/16]"
45,Q3,Q3P,Ambite,-3.205903,40.320294,"[31/5/16, 3/5/17]"
46,Q4,Q4F,Mondéjar,-3.137145,40.345348,"[21/9/15, 27/10/16]"
47,Q4,Q4P,Mondéjar,-3.137145,40.345348,"[31/5/16, 3/5/17]"
48,Z1,Z1V,Villaconejos,-3.476076,40.050052,[16/7/15]
49,Z1,Z3V,Villaconejos,-3.476076,40.050052,[20/7/16]
50,Z2,Z2V,Villamanrique de Tajo,-3.131000,40.044720,[24/7/15]
51,Z2,Z4V,Villamanrique de Tajo,-3.131000,40.044720,[15/7/16]

In [10]:
tmp = pd.merge(sampling, library_collection_code, on='Collection_code')
tmp = tmp.drop_duplicates(subset=['Library_code'])[['Library_code', 'Date']].to_dict(orient='records')
dates = []
for item in tmp:
    for date in item['Date']:
        dates.append({"Library_code": item['Library_code'], "Date": date})
dates

[{'Library_code': 'PV534', 'Date': '1/2/16'},
 {'Library_code': 'PV535', 'Date': '1/2/16'},
 {'Library_code': 'PV538', 'Date': '1/2/16'},
 {'Library_code': 'PV540', 'Date': '1/2/16'},
 {'Library_code': 'PV544', 'Date': '1/2/16'},
 {'Library_code': 'PV546', 'Date': '1/2/16'},
 {'Library_code': 'PV551', 'Date': '1/2/16'},
 {'Library_code': 'PV553', 'Date': '1/2/16'},
 {'Library_code': 'PV554', 'Date': '1/2/16'},
 {'Library_code': 'PV556', 'Date': '1/2/16'},
 {'Library_code': 'PV557', 'Date': '1/2/16'},
 {'Library_code': 'PV064', 'Date': '19/11/15'},
 {'Library_code': 'PV064', 'Date': '10/11/16'},
 {'Library_code': 'PV065', 'Date': '19/11/15'},
 {'Library_code': 'PV065', 'Date': '10/11/16'},
 {'Library_code': 'PV066', 'Date': '19/11/15'},
 {'Library_code': 'PV066', 'Date': '10/11/16'},
 {'Library_code': 'PV068', 'Date': '19/11/15'},
 {'Library_code': 'PV068', 'Date': '10/11/16'},
 {'Library_code': 'PV069', 'Date': '19/11/15'},
 {'Library_code': 'PV069', 'Date': '10/11/16'},
 {'Library_code': 'PV070', 'Date': '19/11/15'},
 {'Library_code': 'PV070', 'Date': '10/11/16'},
 {'Library_code': 'PV071', 'Date': '19/11/15'},
 {'Library_code': 'PV071', 'Date': '10/11/16'},
 {'Library_code': 'PV072', 'Date': '19/11/15'},
 {'Library_code': 'PV072', 'Date': '10/11/16'},
 {'Library_code': 'PV092', 'Date': '19/11/15'},
 {'Library_code': 'PV092', 'Date': '10/11/16'},
 {'Library_code': 'PV277', 'Date': '23/5/16'},
 {'Library_code': 'PV277', 'Date': '3/5/17'},
 {'Library_code': 'PV296', 'Date': '23/5/16'},
 {'Library_code': 'PV296', 'Date': '3/5/17'},
 {'Library_code': 'PV298', 'Date': '23/5/16'},
 {'Library_code': 'PV298', 'Date': '3/5/17'},
 {'Library_code': 'PV572', 'Date': '23/5/16'},
 {'Library_code': 'PV572', 'Date': '3/5/17'},
 {'Library_code': 'PV583', 'Date': '23/5/16'},
 {'Library_code': 'PV583', 'Date': '3/5/17'},
 {'Library_code': 'PV074', 'Date': '19/11/15'},
 {'Library_code': 'PV074', 'Date': '10/11/16'},
 {'Library_code': 'PV075', 'Date': '19/11/15'},
 {'Library_code': 'PV075', 'Date': '10/11/16'},
 {'Library_code': 'PV076', 'Date': '19/11/15'},
 {'Library_code': 'PV076', 'Date': '10/11/16'},
 {'Library_code': 'PV098', 'Date': '19/11/15'},
 {'Library_code': 'PV098', 'Date': '10/11/16'},
 {'Library_code': 'PV099', 'Date': '19/11/15'},
 {'Library_code': 'PV099', 'Date': '10/11/16'},
 {'Library_code': 'PV252', 'Date': '19/11/15'},
 {'Library_code': 'PV252', 'Date': '10/11/16'},
 {'Library_code': 'PV561', 'Date': '19/11/15'},
 {'Library_code': 'PV561', 'Date': '10/11/16'},
 {'Library_code': 'PV566', 'Date': '19/11/15'},
 {'Library_code': 'PV566', 'Date': '10/11/16'},
 {'Library_code': 'PV569', 'Date': '19/11/15'},
 {'Library_code': 'PV569', 'Date': '10/11/16'},
 {'Library_code': 'PV306', 'Date': '23/5/16'},
 {'Library_code': 'PV306', 'Date': '10/5/17'},
 {'Library_code': 'PV312', 'Date': '23/5/16'},
 {'Library_code': 'PV312', 'Date': '10/5/17'},
 {'Library_code': 'PV313', 'Date': '23/5/16'},
 {'Library_code': 'PV313', 'Date': '10/5/17'},
 {'Library_code': 'PV330', 'Date': '23/5/16'},
 {'Library_code': 'PV330', 'Date': '10/5/17'},
 {'Library_code': 'PV563', 'Date': '23/5/16'},
 {'Library_code': 'PV563', 'Date': '10/5/17'},
 {'Library_code': 'PV564', 'Date': '23/5/16'},
 {'Library_code': 'PV564', 'Date': '10/5/17'},
 {'Library_code': 'PV567', 'Date': '23/5/16'},
 {'Library_code': 'PV567', 'Date': '10/5/17'},
 {'Library_code': 'PV573', 'Date': '23/5/16'},
 {'Library_code': 'PV573', 'Date': '10/5/17'},
 {'Library_code': 'PV585', 'Date': '23/5/16'},
 {'Library_code': 'PV585', 'Date': '10/5/17'},
 {'Library_code': 'PV257', 'Date': '1/2/16'},
 {'Library_code': 'PV257', 'Date': '10/11/16'},
 {'Library_code': 'PV262', 'Date': '1/2/16'},
 {'Library_code': 'PV262', 'Date': '10/11/16'},
 {'Library_code': 'PV268', 'Date': '1/2/16'},
 {'Library_code': 'PV268', 'Date': '10/11/16'},
 {'Library_code': 'PV269', 'Date': '1/2/16'},
 {'Library_code': 'PV269', 'Date': '10/11/16'},
 {'Library_code': 'PV562', 'Date': '1/2/16'},
 {'Library_code': 'PV562', 'Date': '10/11/16'},
 {'Library_code': 'PV568', 'Date': '1/2/16'},
 {'Library_code': 'PV568', 'Date': '10/11/16'},
 {'Library_code': 'PV350', 'Date': '31/5/16'},
 {'Library_code': 'PV350', 'Date': '3/5/17'},
 {'Library_code': 'PV352', 'Date': '31/5/16'},
 {'Library_code': 'PV352', 'Date': '3/5/17'},
 {'Library_code': 'PV356', 'Date': '31/5/16'},
 {'Library_code': 'PV356', 'Date': '3/5/17'},
 {'Library_code': 'PV359', 'Date': '31/5/16'},
 {'Library_code': 'PV359', 'Date': '3/5/17'},
 {'Library_code': 'PV369', 'Date': '31/5/16'},
 {'Library_code': 'PV369', 'Date': '3/5/17'},
 {'Library_code': 'PV565', 'Date': '31/5/16'},
 {'Library_code': 'PV565', 'Date': '3/5/17'},
 {'Library_code': 'PV584', 'Date': '31/5/16'},
 {'Library_code': 'PV584', 'Date': '3/5/17'},
 {'Library_code': 'PV022', 'Date': '4/11/15'},
 {'Library_code': 'PV022', 'Date': '27/10/16'},
 {'Library_code': 'PV023', 'Date': '4/11/15'},
 {'Library_code': 'PV023', 'Date': '27/10/16'},
 {'Library_code': 'PV024', 'Date': '4/11/15'},
 {'Library_code': 'PV024', 'Date': '27/10/16'},
 {'Library_code': 'PV025', 'Date': '4/11/15'},
 {'Library_code': 'PV025', 'Date': '27/10/16'},
 {'Library_code': 'PV026', 'Date': '4/11/15'},
 {'Library_code': 'PV026', 'Date': '27/10/16'},
 {'Library_code': 'PV027', 'Date': '4/11/15'},
 {'Library_code': 'PV027', 'Date': '27/10/16'},
 {'Library_code': 'PV078', 'Date': '4/11/15'},
 {'Library_code': 'PV078', 'Date': '27/10/16'},
 {'Library_code': 'PV079', 'Date': '4/11/15'},
 {'Library_code': 'PV079', 'Date': '27/10/16'},
 {'Library_code': 'PV270', 'Date': '4/11/15'},
 {'Library_code': 'PV270', 'Date': '27/10/16'},
 {'Library_code': 'PV057', 'Date': '31/5/16'},
 {'Library_code': 'PV057', 'Date': '3/5/17'},
 {'Library_code': 'PV058', 'Date': '31/5/16'},
 {'Library_code': 'PV058', 'Date': '3/5/17'},
 {'Library_code': 'PV059', 'Date': '31/5/16'},
 {'Library_code': 'PV059', 'Date': '3/5/17'},
 {'Library_code': 'PV060', 'Date': '31/5/16'},
 {'Library_code': 'PV060', 'Date': '3/5/17'},
 {'Library_code': 'PV085', 'Date': '31/5/16'},
 {'Library_code': 'PV085', 'Date': '3/5/17'},
 {'Library_code': 'PV086', 'Date': '31/5/16'},
 {'Library_code': 'PV086', 'Date': '3/5/17'},
 {'Library_code': 'PV087', 'Date': '31/5/16'},
 {'Library_code': 'PV087', 'Date': '3/5/17'},
 {'Library_code': 'PV380', 'Date': '31/5/16'},
 {'Library_code': 'PV380', 'Date': '3/5/17'},
 {'Library_code': 'PV386', 'Date': '31/5/16'},
 {'Library_code': 'PV386', 'Date': '3/5/17'},
 {'Library_code': 'PV390', 'Date': '31/5/16'},
 {'Library_code': 'PV390', 'Date': '3/5/17'},
 {'Library_code': 'PV586', 'Date': '21/4/16'},
 {'Library_code': 'PV587', 'Date': '21/4/16'},
 {'Library_code': 'PV588', 'Date': '21/4/16'},
 {'Library_code': 'PV589', 'Date': '21/4/16'},
 {'Library_code': 'PV489', 'Date': '21/4/16'},
 {'Library_code': 'PV491', 'Date': '21/4/16'},
 {'Library_code': 'PV495', 'Date': '21/4/16'},
 {'Library_code': 'PV496', 'Date': '21/4/16'},
 {'Library_code': 'PV498', 'Date': '21/4/16'},
 {'Library_code': 'PV500', 'Date': '21/4/16'},
 {'Library_code': 'PV501', 'Date': '21/4/16'},
 {'Library_code': 'PV503', 'Date': '21/4/16'},
 {'Library_code': 'PV505', 'Date': '21/4/16'},
 {'Library_code': 'PV196', 'Date': '19/11/15'},
 {'Library_code': 'PV196', 'Date': '10/11/16'},
 {'Library_code': 'PV197', 'Date': '19/11/15'},
 {'Library_code': 'PV197', 'Date': '10/11/16'},
 {'Library_code': 'PV198', 'Date': '19/11/15'},
 {'Library_code': 'PV198', 'Date': '10/11/16'},
 {'Library_code': 'PV199', 'Date': '19/11/15'},
 {'Library_code': 'PV199', 'Date': '10/11/16'},
 {'Library_code': 'PV200', 'Date': '19/11/15'},
 {'Library_code': 'PV200', 'Date': '10/11/16'},
 {'Library_code': 'PV201', 'Date': '19/11/15'},
 {'Library_code': 'PV201', 'Date': '10/11/16'},
 {'Library_code': 'PV202', 'Date': '19/11/15'},
 {'Library_code': 'PV202', 'Date': '10/11/16'},
 {'Library_code': 'PV203', 'Date': '19/11/15'},
 {'Library_code': 'PV203', 'Date': '10/11/16'},
 {'Library_code': 'PV204', 'Date': '19/11/15'},
 {'Library_code': 'PV204', 'Date': '10/11/16'},
 {'Library_code': 'PV205', 'Date': '19/11/15'},
 {'Library_code': 'PV205', 'Date': '10/11/16'},
 {'Library_code': 'PV206', 'Date': '19/11/15'},
 {'Library_code': 'PV206', 'Date': '10/11/16'},
 {'Library_code': 'PV207', 'Date': '19/11/15'},
 {'Library_code': 'PV207', 'Date': '10/11/16'},
 {'Library_code': 'PV208', 'Date': '19/11/15'},
 {'Library_code': 'PV208', 'Date': '10/11/16'},
 {'Library_code': 'PV209', 'Date': '19/11/15'},
 {'Library_code': 'PV209', 'Date': '10/11/16'},
 {'Library_code': 'PV222', 'Date': '19/11/15'},
 {'Library_code': 'PV222', 'Date': '10/11/16'},
 {'Library_code': 'PV115', 'Date': '31/3/16'},
 {'Library_code': 'PV115', 'Date': '19/4/17'},
 {'Library_code': 'PV116', 'Date': '31/3/16'},
 {'Library_code': 'PV116', 'Date': '19/4/17'},
 {'Library_code': 'PV117', 'Date': '31/3/16'},
 {'Library_code': 'PV117', 'Date': '19/4/17'},
 {'Library_code': 'PV118', 'Date': '31/3/16'},
 {'Library_code': 'PV118', 'Date': '19/4/17'},
 {'Library_code': 'PV119', 'Date': '31/3/16'},
 {'Library_code': 'PV119', 'Date': '19/4/17'},
 {'Library_code': 'PV120', 'Date': '31/3/16'},
 {'Library_code': 'PV120', 'Date': '19/4/17'},
 {'Library_code': 'PV121', 'Date': '31/3/16'},
 {'Library_code': 'PV121', 'Date': '19/4/17'},
 {'Library_code': 'PV122', 'Date': '31/3/16'},
 {'Library_code': 'PV122', 'Date': '19/4/17'},
 {'Library_code': 'PV123', 'Date': '31/3/16'},
 {'Library_code': 'PV123', 'Date': '19/4/17'},
 {'Library_code': 'PV124', 'Date': '31/3/16'},
 {'Library_code': 'PV124', 'Date': '19/4/17'},
 {'Library_code': 'PV125', 'Date': '31/3/16'},
 {'Library_code': 'PV125', 'Date': '19/4/17'},
 {'Library_code': 'PV126', 'Date': '31/3/16'},
 {'Library_code': 'PV126', 'Date': '19/4/17'},
 {'Library_code': 'PV127', 'Date': '31/3/16'},
 {'Library_code': 'PV127', 'Date': '19/4/17'},
 {'Library_code': 'PV128', 'Date': '31/3/16'},
 {'Library_code': 'PV128', 'Date': '19/4/17'},
 {'Library_code': 'PV189', 'Date': '31/3/16'},
 {'Library_code': 'PV189', 'Date': '19/4/17'},
 {'Library_code': 'PV190', 'Date': '31/3/16'},
 {'Library_code': 'PV190', 'Date': '19/4/17'},
 {'Library_code': 'PV028', 'Date': '16/7/15'},
 {'Library_code': 'PV028', 'Date': '20/7/16'},
 {'Library_code': 'PV029', 'Date': '16/7/15'},
 {'Library_code': 'PV029', 'Date': '20/7/16'},
 {'Library_code': 'PV030', 'Date': '16/7/15'},
 {'Library_code': 'PV030', 'Date': '20/7/16'},
 {'Library_code': 'PV159', 'Date': '16/7/15'},
 {'Library_code': 'PV159', 'Date': '20/7/16'},
 {'Library_code': 'PV160', 'Date': '16/7/15'},
 {'Library_code': 'PV160', 'Date': '20/7/16'},
 {'Library_code': 'PV161', 'Date': '16/7/15'},
 {'Library_code': 'PV161', 'Date': '20/7/16'},
 {'Library_code': 'PV162', 'Date': '16/7/15'},
 {'Library_code': 'PV162', 'Date': '20/7/16'},
 {'Library_code': 'PV163', 'Date': '16/7/15'},
 {'Library_code': 'PV163', 'Date': '20/7/16'},
 {'Library_code': 'PV164', 'Date': '16/7/15'},
 {'Library_code': 'PV164', 'Date': '20/7/16'},
 {'Library_code': 'PV031', 'Date': '19/11/15'},
 {'Library_code': 'PV031', 'Date': '10/11/16'},
 {'Library_code': 'PV032', 'Date': '19/11/15'},
 {'Library_code': 'PV032', 'Date': '10/11/16'},
 {'Library_code': 'PV033', 'Date': '19/11/15'},
 {'Library_code': 'PV033', 'Date': '10/11/16'},
 {'Library_code': 'PV210', 'Date': '19/11/15'},
 {'Library_code': 'PV210', 'Date': '10/11/16'},
 {'Library_code': 'PV211', 'Date': '19/11/15'},
 {'Library_code': 'PV211', 'Date': '10/11/16'},
 {'Library_code': 'PV129', 'Date': '31/3/16'},
 {'Library_code': 'PV130', 'Date': '31/3/16'},
 {'Library_code': 'PV131', 'Date': '31/3/16'},
 {'Library_code': 'PV132', 'Date': '31/3/16'},
 {'Library_code': 'PV133', 'Date': '31/3/16'},
 {'Library_code': 'PV134', 'Date': '31/3/16'},
 {'Library_code': 'PV135', 'Date': '31/3/16'},
 {'Library_code': 'PV136', 'Date': '31/3/16'},
 {'Library_code': 'PV137', 'Date': '31/3/16'},
 {'Library_code': 'PV138', 'Date': '31/3/16'},
 {'Library_code': 'PV139', 'Date': '31/3/16'},
 {'Library_code': 'PV140', 'Date': '31/3/16'},
 {'Library_code': 'PV191', 'Date': '31/3/16'},
 {'Library_code': 'PV192', 'Date': '31/3/16'},
 {'Library_code': 'PV193', 'Date': '31/3/16'},
 {'Library_code': 'PV194', 'Date': '31/3/16'},
 {'Library_code': 'PV195', 'Date': '31/3/16'},
 {'Library_code': 'PV096', 'Date': '16/7/15'},
 {'Library_code': 'PV096', 'Date': '20/7/16'},
 {'Library_code': 'PV097', 'Date': '16/7/15'},
 {'Library_code': 'PV097', 'Date': '20/7/16'},
 {'Library_code': 'PV165', 'Date': '16/7/15'},
 {'Library_code': 'PV165', 'Date': '20/7/16'},
 {'Library_code': 'PV166', 'Date': '16/7/15'},
 {'Library_code': 'PV166', 'Date': '20/7/16'},
 {'Library_code': 'PV167', 'Date': '16/7/15'},
 {'Library_code': 'PV167', 'Date': '20/7/16'},
 {'Library_code': 'PV168', 'Date': '16/7/15'},
 {'Library_code': 'PV168', 'Date': '20/7/16'},
 {'Library_code': 'PV169', 'Date': '16/7/15'},
 {'Library_code': 'PV169', 'Date': '20/7/16'},
 {'Library_code': 'PV170', 'Date': '16/7/15'},
 {'Library_code': 'PV170', 'Date': '20/7/16'},
 {'Library_code': 'PV171', 'Date': '16/7/15'},
 {'Library_code': 'PV171', 'Date': '20/7/16'},
 {'Library_code': 'PV172', 'Date': '16/7/15'},
 {'Library_code': 'PV172', 'Date': '20/7/16'},
 {'Library_code': 'PV173', 'Date': '16/7/15'},
 {'Library_code': 'PV173', 'Date': '20/7/16'},
 {'Library_code': 'PV174', 'Date': '16/7/15'},
 {'Library_code': 'PV174', 'Date': '20/7/16'},
 {'Library_code': 'PV187', 'Date': '16/7/15'},
 {'Library_code': 'PV187', 'Date': '20/7/16'},
 {'Library_code': 'PV212', 'Date': '19/11/15'},
 {'Library_code': 'PV212', 'Date': '10/11/16'},
 {'Library_code': 'PV213', 'Date': '19/11/15'},
 {'Library_code': 'PV213', 'Date': '10/11/16'},
 {'Library_code': 'PV214', 'Date': '19/11/15'},
 {'Library_code': 'PV214', 'Date': '10/11/16'},
 {'Library_code': 'PV215', 'Date': '19/11/15'},
 {'Library_code': 'PV215', 'Date': '10/11/16'},
 {'Library_code': 'PV216', 'Date': '19/11/15'},
 {'Library_code': 'PV216', 'Date': '10/11/16'},
 {'Library_code': 'PV217', 'Date': '19/11/15'},
 {'Library_code': 'PV217', 'Date': '10/11/16'},
 {'Library_code': 'PV218', 'Date': '19/11/15'},
 {'Library_code': 'PV218', 'Date': '10/11/16'},
 {'Library_code': 'PV219', 'Date': '19/11/15'},
 {'Library_code': 'PV219', 'Date': '10/11/16'},
 {'Library_code': 'PV220', 'Date': '19/11/15'},
 {'Library_code': 'PV220', 'Date': '10/11/16'},
 {'Library_code': 'PV221', 'Date': '19/11/15'},
 {'Library_code': 'PV221', 'Date': '10/11/16'},
 {'Library_code': 'PV223', 'Date': '19/11/15'},
 {'Library_code': 'PV223', 'Date': '10/11/16'},
 {'Library_code': 'PV224', 'Date': '19/11/15'},
 {'Library_code': 'PV224', 'Date': '10/11/16'},
 {'Library_code': 'PV141', 'Date': '31/3/16'},
 {'Library_code': 'PV141', 'Date': '19/4/17'},
 {'Library_code': 'PV142', 'Date': '31/3/16'},
 {'Library_code': 'PV142', 'Date': '19/4/17'},
 {'Library_code': 'PV143', 'Date': '31/3/16'},
 {'Library_code': 'PV143', 'Date': '19/4/17'},
 {'Library_code': 'PV144', 'Date': '31/3/16'},
 {'Library_code': 'PV144', 'Date': '19/4/17'},
 {'Library_code': 'PV145', 'Date': '31/3/16'},
 {'Library_code': 'PV145', 'Date': '19/4/17'},
 {'Library_code': 'PV146', 'Date': '31/3/16'},
 {'Library_code': 'PV146', 'Date': '19/4/17'},
 {'Library_code': 'PV147', 'Date': '31/3/16'},
 {'Library_code': 'PV147', 'Date': '19/4/17'},
 {'Library_code': 'PV148', 'Date': '31/3/16'},
 {'Library_code': 'PV148', 'Date': '19/4/17'},
 {'Library_code': 'PV149', 'Date': '31/3/16'},
 {'Library_code': 'PV149', 'Date': '19/4/17'},
 {'Library_code': 'PV081', 'Date': '24/7/15'},
 {'Library_code': 'PV081', 'Date': '15/7/16'},
 {'Library_code': 'PV175', 'Date': '24/7/15'},
 {'Library_code': 'PV175', 'Date': '15/7/16'},
 {'Library_code': 'PV176', 'Date': '24/7/15'},
 {'Library_code': 'PV176', 'Date': '15/7/16'},
 {'Library_code': 'PV177', 'Date': '24/7/15'},
 {'Library_code': 'PV177', 'Date': '15/7/16'},
 {'Library_code': 'PV178', 'Date': '24/7/15'},
 {'Library_code': 'PV178', 'Date': '15/7/16'},
 {'Library_code': 'PV179', 'Date': '24/7/15'},
 {'Library_code': 'PV179', 'Date': '15/7/16'},
 {'Library_code': 'PV180', 'Date': '24/7/15'},
 {'Library_code': 'PV180', 'Date': '15/7/16'},
 {'Library_code': 'PV181', 'Date': '24/7/15'},
 {'Library_code': 'PV181', 'Date': '15/7/16'},
 {'Library_code': 'PV182', 'Date': '24/7/15'},
 {'Library_code': 'PV182', 'Date': '15/7/16'},
 {'Library_code': 'PV183', 'Date': '24/7/15'},
 {'Library_code': 'PV183', 'Date': '15/7/16'},
 {'Library_code': 'PV184', 'Date': '24/7/15'},
 {'Library_code': 'PV184', 'Date': '15/7/16'},
 {'Library_code': 'PV185', 'Date': '24/7/15'},
 {'Library_code': 'PV185', 'Date': '15/7/16'},
 {'Library_code': 'PV186', 'Date': '24/7/15'},
 {'Library_code': 'PV186', 'Date': '15/7/16'},
 {'Library_code': 'PV188', 'Date': '24/7/15'},
 {'Library_code': 'PV188', 'Date': '15/7/16'},
 {'Library_code': 'PV034', 'Date': '4/11/15'},
 {'Library_code': 'PV034', 'Date': '27/10/16'},
 {'Library_code': 'PV225', 'Date': '4/11/15'},
 {'Library_code': 'PV225', 'Date': '27/10/16'},
 {'Library_code': 'PV226', 'Date': '4/11/15'},
 {'Library_code': 'PV226', 'Date': '27/10/16'},
 {'Library_code': 'PV227', 'Date': '4/11/15'},
 {'Library_code': 'PV227', 'Date': '27/10/16'},
 {'Library_code': 'PV228', 'Date': '4/11/15'},
 {'Library_code': 'PV228', 'Date': '27/10/16'},
 {'Library_code': 'PV229', 'Date': '4/11/15'},
 {'Library_code': 'PV229', 'Date': '27/10/16'},
 {'Library_code': 'PV230', 'Date': '4/11/15'},
 {'Library_code': 'PV230', 'Date': '27/10/16'},
 {'Library_code': 'PV231', 'Date': '4/11/15'},
 {'Library_code': 'PV231', 'Date': '27/10/16'},
 {'Library_code': 'PV232', 'Date': '4/11/15'},
 {'Library_code': 'PV232', 'Date': '27/10/16'},
 {'Library_code': 'PV233', 'Date': '4/11/15'},
 {'Library_code': 'PV233', 'Date': '27/10/16'},
 {'Library_code': 'PV234', 'Date': '4/11/15'},
 {'Library_code': 'PV234', 'Date': '27/10/16'},
 {'Library_code': 'PV235', 'Date': '4/11/15'},
 {'Library_code': 'PV235', 'Date': '27/10/16'},
 {'Library_code': 'PV236', 'Date': '4/11/15'},
 {'Library_code': 'PV236', 'Date': '27/10/16'},
 {'Library_code': 'PV237', 'Date': '4/11/15'},
 {'Library_code': 'PV237', 'Date': '27/10/16'},
 {'Library_code': 'PV150', 'Date': '21/4/16'},
 {'Library_code': 'PV150', 'Date': '16/4/17'},
 {'Library_code': 'PV151', 'Date': '21/4/16'},
 {'Library_code': 'PV151', 'Date': '16/4/17'},
 {'Library_code': 'PV152', 'Date': '21/4/16'},
 {'Library_code': 'PV152', 'Date': '16/4/17'},
 {'Library_code': 'PV153', 'Date': '21/4/16'},
 {'Library_code': 'PV153', 'Date': '16/4/17'},
 {'Library_code': 'PV154', 'Date': '21/4/16'},
 {'Library_code': 'PV154', 'Date': '16/4/17'},
 {'Library_code': 'PV155', 'Date': '21/4/16'},
 {'Library_code': 'PV155', 'Date': '16/4/17'},
 {'Library_code': 'PV156', 'Date': '21/4/16'},
 {'Library_code': 'PV156', 'Date': '16/4/17'},
 {'Library_code': 'PV157', 'Date': '21/4/16'},
 {'Library_code': 'PV157', 'Date': '16/4/17'},
 {'Library_code': 'PV158', 'Date': '21/4/16'},
 {'Library_code': 'PV158', 'Date': '16/4/17'},
 {'Library_code': 'PV001', 'Date': '16/7/15'},
 {'Library_code': 'PV002', 'Date': '16/7/15'},
 {'Library_code': 'PV003', 'Date': '16/7/15'},
 {'Library_code': 'PV003bgi', 'Date': '16/7/15'},
 {'Library_code': 'PV004bgi', 'Date': '16/7/15'},
 {'Library_code': 'PV011', 'Date': '16/7/15'},
 {'Library_code': 'PV021bgi', 'Date': '16/7/15'},
 {'Library_code': 'PV061', 'Date': '20/7/16'},
 {'Library_code': 'PV012bgi', 'Date': '16/7/15'},
 {'Library_code': 'PV013bgi', 'Date': '16/7/15'},
 {'Library_code': 'PV014', 'Date': '16/7/15'},
 {'Library_code': 'PV015bgi', 'Date': '16/7/15'},
 {'Library_code': 'PV016', 'Date': '24/7/15'},
 {'Library_code': 'PV017bgi', 'Date': '24/7/15'},
 {'Library_code': 'PV514', 'Date': '24/7/15'},
 {'Library_code': 'PV516', 'Date': '24/7/15'},
 {'Library_code': 'PV062', 'Date': '15/7/16'},
 {'Library_code': 'PV018bgi', 'Date': '24/7/15'},
 {'Library_code': 'PV020bgi', 'Date': '24/7/15'},
 {'Library_code': 'PV519', 'Date': '24/7/15'},
 {'Library_code': 'PV063', 'Date': '15/7/16'},
 {'Library_code': 'PV005bgi', 'Date': '8/9/15'},

In [11]:
sites_to_type = {
    "Crop": "CO_020:0000051",
    "Edge": "CO_020:0000054",
    "Wasteland": "CO_020:0000046",
    "Oak": "CO_020:0000045"
}

In [12]:
sampling

,Site_code,Collection_code,Location,Longitude,Latitude,Date
0,C1,C1F,Aranjuez,-3.593308,40.051302,[1/2/16]
1,C1,C3F,Aranjuez,-3.593308,40.051302,[30/1/17]
2,C2,C2F,Aranjuez,-3.599064,40.043193,[1/2/16]
3,C2,C4F,Aranjuez,-3.599064,40.043193,[30/1/17]
4,E1,E1F,Aranjuez,-3.500323,40.059138,"[19/11/15, 10/11/16]"
5,E1,E1P,Aranjuez,-3.500323,40.059138,"[23/5/16, 3/5/17]"
6,E2,E2F,San Martín de la Vega,-3.536191,40.234966,"[19/11/15, 10/11/16]"
7,E2,E2P,San Martín de la Vega,-3.536191,40.234966,"[23/5/16, 10/5/17]"
8,E3,E3F,Ambite,-3.196057,40.089637,"[1/2/16, 10/11/16]"
9,E3,E3P,Ambite,-3.196057,40.089637,"[31/5/16, 3/5/17]"
10,E4,E4F,Mondéjar,-3.131139,40.494167,"[4/11/15, 27/10/16]"
11,E4,E4P,Mondéjar,-3.131139,40.494167,"[31/5/16, 3/5/17]"
12,H1,H1P,Villaconejos,-3.477574,40.049330,[21/4/16]
13,H1,H4P,Villaconejos,-3.477574,40.049330,[19/4/17]
14,H2,H2P,Villamanrique de Tajo,-3.214026,40.085899,[21/4/16]
15,H2,H5P,Villamanrique de Tajo,-3.214026,40.085899,[19/4/17]
16,H3,H3P,Tielmes,-3.253943,40.245852,[21/4/16]
17,H3,H6P,Tielmes,-3.253943,40.245852,[19/4/17]
18,L1,L1F,Aranjuez,-3.345220,40.031840,"[19/11/15, 10/11/16]"
19,L1,L1P,Aranjuez,-3.345220,40.031840,"[31/3/16, 19/4/17]"
20,L1,L1V,Aranjuez,-3.345220,40.031840,"[16/7/15, 20/7/16]"
21,L2,L2F,Villaconejos,-3.476462,40.048758,"[19/11/15, 10/11/16]"
22,L2,L2P,Villaconejos,-3.476462,40.048758,[31/3/16]
23,L2,L2V,Villaconejos,-3.476462,40.048758,"[16/7/15, 20/7/16]"
24,L3,L3F,Villamanrique de Tajo,-3.125794,40.050352,"[19/11/15, 10/11/16]"
25,L3,L3P,Villamanrique de Tajo,-3.125794,40.050352,"[31/3/16, 19/4/17]"
26,L3,L3V,Villamanrique de Tajo,-3.125794,40.050352,"[24/7/15, 15/7/16]"
27,L4,L4F,Tielmes,-3.252617,40.245459,"[4/11/15, 27/10/16]"
28,L4,L4P,Tielmes,-3.252617,40.245459,"[21/4/16, 16/4/17]"
29,L4,L4V,Tielmes,-3.252617,40.245459,[15/7/16]
30,M1,M1V,Aranjuez,-3.345220,40.031840,[16/7/15]
31,M1,M5V,Aranjuez,-3.345220,40.031840,[20/7/16]
32,M1,M9V,Aranjuez,-3.345220,40.031840,[28/6/17]
33,M2,M2V,Villaconejos,-3.503040,40.050578,[16/7/15]
34,M3,M11V,Villamanrique de Tajo,-3.125000,40.045900,[28/6/17]
35,M3,M3V,Villamanrique de Tajo,-3.125000,40.045900,[24/7/15]
36,M3,M7V,Villamanrique de Tajo,-3.125000,40.045900,[15/7/16]
37,M4,M12V,Villamanrique de Tajo,-3.182801,40.032298,[28/6/17]
38,M4,M4V,Villamanrique de Tajo,-3.182801,40.032298,[24/7/15]
39,M4,M8V,Villamanrique de Tajo,-3.182801,40.032298,[15/7/16]
40,Q1,Q1F,Aranjuez,-3.391830,39.595520,"[8/9/15, 12/9/16]"
41,Q1,Q1P,Aranjuez,-3.391830,39.595520,"[23/5/16, 10/5/17]"
42,Q2,Q2F,San Martín de la Vega,-3.530613,40.225155,"[21/9/15, 20/10/16]"
43,Q2,Q2P,San Martín de la Vega,-3.530613,40.225155,"[23/5/16, 10/5/17]"
44,Q3,Q3F,Ambite,-3.205903,40.320294,"[21/9/15, 27/10/16]"
45,Q3,Q3P,Ambite,-3.205903,40.320294,"[31/5/16, 3/5/17]"
46,Q4,Q4F,Mondéjar,-3.137145,40.345348,"[21/9/15, 27/10/16]"
47,Q4,Q4P,Mondéjar,-3.137145,40.345348,"[31/5/16, 3/5/17]"
48,Z1,Z1V,Villaconejos,-3.476076,40.050052,[16/7/15]
49,Z1,Z3V,Villaconejos,-3.476076,40.050052,[20/7/16]
50,Z2,Z2V,Villamanrique de Tajo,-3.131000,40.044720,[24/7/15]
51,Z2,Z4V,Villamanrique de Tajo,-3.131000,40.044720,[15/7/16]

In [13]:
sites = pd.merge(
    pd.merge(sampling, library_collection_code, on='Collection_code'),
    libraries[['Library_code', 'Habitat']], on='Library_code'
)
sites['Habitat_type'] = sites['Habitat'].map(sites_to_type)
sites = sites.drop_duplicates(subset=['Site_code'])[['Site_code', 'Longitude', 'Latitude', 'Location', 'Habitat', 'Habitat_type']].to_dict(orient='records')
sites

[{'Site_code': 'C1',
  'Longitude': -3.593308,
  'Latitude': 40.051302,
  'Location': 'Aranjuez',
  'Habitat': 'Crop',
  'Habitat_type': 'CO_020:0000051'},
 {'Site_code': 'C2',
  'Longitude': -3.599064,
  'Latitude': 40.043193,
  'Location': 'Aranjuez',
  'Habitat': 'Crop',
  'Habitat_type': 'CO_020:0000051'},
 {'Site_code': 'E1',
  'Longitude': -3.500323,
  'Latitude': 40.059138,
  'Location': 'Aranjuez',
  'Habitat': 'Wasteland',
  'Habitat_type': 'CO_020:0000046'},
 {'Site_code': 'E2',
  'Longitude': -3.536191,
  'Latitude': 40.234966,
  'Location': 'San Martín de la Vega',
  'Habitat': 'Wasteland',
  'Habitat_type': 'CO_020:0000046'},
 {'Site_code': 'E3',
  'Longitude': -3.196057,
  'Latitude': 40.089637,
  'Location': 'Ambite',
  'Habitat': 'Wasteland',
  'Habitat_type': 'CO_020:0000046'},
 {'Site_code': 'E4',
  'Longitude': -3.131139,
  'Latitude': 40.494167,
  'Location': 'Mondéjar',
  'Habitat': 'Wasteland',
  'Habitat_type': 'CO_020:0000046'},
 {'Site_code': 'H1',
  'Longitude': -3.477574,
  'Latitude': 40.04933,
  'Location': 'Villaconejos',
  'Habitat': 'Crop',
  'Habitat_type': 'CO_020:0000051'},
 {'Site_code': 'H2',
  'Longitude': -3.214026,
  'Latitude': 40.085899,
  'Location': 'Villamanrique de Tajo',
  'Habitat': 'Crop',
  'Habitat_type': 'CO_020:0000051'},
 {'Site_code': 'H3',
  'Longitude': -3.253943,
  'Latitude': 40.245852,
  'Location': 'Tielmes',
  'Habitat': 'Crop',
  'Habitat_type': 'CO_020:0000051'},
 {'Site_code': 'L1',
  'Longitude': -3.34522,
  'Latitude': 40.03184,
  'Location': 'Aranjuez',
  'Habitat': 'Edge',
  'Habitat_type': 'CO_020:0000054'},
 {'Site_code': 'L2',
  'Longitude': -3.476462,
  'Latitude': 40.048758,
  'Location': 'Villaconejos',
  'Habitat': 'Edge',
  'Habitat_type': 'CO_020:0000054'},
 {'Site_code': 'L3',
  'Longitude': -3.125794,
  'Latitude': 40.050352,
  'Location': 'Villamanrique de Tajo',
  'Habitat': 'Edge',
  'Habitat_type': 'CO_020:0000054'},
 {'Site_code': 'L4',
  'Longitude': -3.252617,
  'Latitude': 40.245459,
  'Location': 'Tielmes',
  'Habitat': 'Edge',
  'Habitat_type': 'CO_020:0000054'},
 {'Site_code': 'M1',
  'Longitude': -3.34522,
  'Latitude': 40.03184,
  'Location': 'Aranjuez',
  'Habitat': 'Crop',
  'Habitat_type': 'CO_020:0000051'},
 {'Site_code': 'M2',
  'Longitude': -3.50304,
  'Latitude': 40.050578,
  'Location': 'Villaconejos',
  'Habitat': 'Crop',
  'Habitat_type': 'CO_020:0000051'},
 {'Site_code': 'M3',
  'Longitude': -3.125,
  'Latitude': 40.0459,
  'Location': 'Villamanrique de Tajo',
  'Habitat': 'Crop',
  'Habitat_type': 'CO_020:0000051'},
 {'Site_code': 'M4',
  'Longitude': -3.182801,
  'Latitude': 40.032298,
  'Location': 'Villamanrique de Tajo',
  'Habitat': 'Crop',
  'Habitat_type': 'CO_020:0000051'},
 {'Site_code': 'Q1',
  'Longitude': -3.39183,
  'Latitude': 39.59552,
  'Location': 'Aranjuez',
  'Habitat': 'Oak',
  'Habitat_type': 'CO_020:0000045'},
 {'Site_code': 'Q2',
  'Longitude': -3.530613,
  'Latitude': 40.225155,
  'Location': 'San Martín de la Vega',
  'Habitat': 'Oak',
  'Habitat_type': 'CO_020:0000045'},
 {'Site_code': 'Q3',
  'Longitude': -3.205903,
  'Latitude': 40.320294,
  'Location': 'Ambite',
  'Habitat': 'Oak',
  'Habitat_type': 'CO_020:0000045'},
 {'Site_code': 'Q4',
  'Longitude': -3.137145,
  'Latitude': 40.345348,
  'Location': 'Mondéjar',
  'Habitat': 'Oak',
  'Habitat_type': 'CO_020:0000045'},
 {'Site_code': 'Z1',
  'Longitude': -3.476076,
  'Latitude': 40.050052,
  'Location': 'Villaconejos',
  'Habitat': 'Crop',
  'Habitat_type': 'CO_020:0000051'},
 {'Site_code': 'Z2',
  'Longitude': -3.131,
  'Latitude': 40.04472,
  'Location': 'Villamanrique de Tajo',
  'Habitat': 'Crop',
  'Habitat_type': 'CO_020:0000051'}]

In [14]:
libraries = libraries.drop_duplicates(subset=['Library_code'])[['Library_code', 'No_extracts']].to_dict(orient='records')
libraries

[{'Library_code': 'PV001', 'No_extracts': 8},
 {'Library_code': 'PV002', 'No_extracts': 11},
 {'Library_code': 'PV003', 'No_extracts': 13},
 {'Library_code': 'PV003bgi', 'No_extracts': 13},
 {'Library_code': 'PV004bgi', 'No_extracts': 7},
 {'Library_code': 'PV005bgi', 'No_extracts': 12},
 {'Library_code': 'PV006bgi', 'No_extracts': 19},
 {'Library_code': 'PV007bgi', 'No_extracts': 17},
 {'Library_code': 'PV008bgi', 'No_extracts': 11},
 {'Library_code': 'PV009', 'No_extracts': 13},
 {'Library_code': 'PV009bgi', 'No_extracts': 13},
 {'Library_code': 'PV010bgi', 'No_extracts': 10},
 {'Library_code': 'PV011', 'No_extracts': 7},
 {'Library_code': 'PV012bgi', 'No_extracts': 7},
 {'Library_code': 'PV013bgi', 'No_extracts': 9},
 {'Library_code': 'PV014', 'No_extracts': 8},
 {'Library_code': 'PV015bgi', 'No_extracts': 11},
 {'Library_code': 'PV016', 'No_extracts': 16},
 {'Library_code': 'PV017bgi', 'No_extracts': 12},
 {'Library_code': 'PV018bgi', 'No_extracts': 16},
 {'Library_code': 'PV020bgi', 'No_extracts': 10},
 {'Library_code': 'PV021bgi', 'No_extracts': 13},
 {'Library_code': 'PV022', 'No_extracts': 23},
 {'Library_code': 'PV023', 'No_extracts': 24},
 {'Library_code': 'PV024', 'No_extracts': 15},
 {'Library_code': 'PV025', 'No_extracts': 8},
 {'Library_code': 'PV026', 'No_extracts': 7},
 {'Library_code': 'PV027', 'No_extracts': 14},
 {'Library_code': 'PV028', 'No_extracts': 6},
 {'Library_code': 'PV029', 'No_extracts': 8},
 {'Library_code': 'PV030', 'No_extracts': 7},
 {'Library_code': 'PV031', 'No_extracts': 9},
 {'Library_code': 'PV032', 'No_extracts': 10},
 {'Library_code': 'PV033', 'No_extracts': 10},
 {'Library_code': 'PV034', 'No_extracts': 8},
 {'Library_code': 'PV035', 'No_extracts': 17},
 {'Library_code': 'PV036', 'No_extracts': 31},
 {'Library_code': 'PV037', 'No_extracts': 27},
 {'Library_code': 'PV041', 'No_extracts': 20},
 {'Library_code': 'PV042', 'No_extracts': 14},
 {'Library_code': 'PV046', 'No_extracts': 7},
 {'Library_code': 'PV047', 'No_extracts': 13},
 {'Library_code': 'PV048', 'No_extracts': 9},
 {'Library_code': 'PV049', 'No_extracts': 11},
 {'Library_code': 'PV050', 'No_extracts': 18},
 {'Library_code': 'PV051', 'No_extracts': 13},
 {'Library_code': 'PV052', 'No_extracts': 10},
 {'Library_code': 'PV053', 'No_extracts': 7},
 {'Library_code': 'PV054', 'No_extracts': 8},
 {'Library_code': 'PV055', 'No_extracts': 8},
 {'Library_code': 'PV056', 'No_extracts': 5},
 {'Library_code': 'PV057', 'No_extracts': 16},
 {'Library_code': 'PV058', 'No_extracts': 11},
 {'Library_code': 'PV059', 'No_extracts': 10},
 {'Library_code': 'PV060', 'No_extracts': 5},
 {'Library_code': 'PV061', 'No_extracts': 26},
 {'Library_code': 'PV062', 'No_extracts': 46},
 {'Library_code': 'PV063', 'No_extracts': 27},
 {'Library_code': 'PV064', 'No_extracts': 21},
 {'Library_code': 'PV065', 'No_extracts': 19},
 {'Library_code': 'PV066', 'No_extracts': 8},
 {'Library_code': 'PV068', 'No_extracts': 8},
 {'Library_code': 'PV069', 'No_extracts': 11},
 {'Library_code': 'PV070', 'No_extracts': 6},
 {'Library_code': 'PV071', 'No_extracts': 10},
 {'Library_code': 'PV072', 'No_extracts': 8},
 {'Library_code': 'PV074', 'No_extracts': 11},
 {'Library_code': 'PV075', 'No_extracts': 6},
 {'Library_code': 'PV076', 'No_extracts': 11},
 {'Library_code': 'PV078', 'No_extracts': 8},
 {'Library_code': 'PV079', 'No_extracts': 8},
 {'Library_code': 'PV080', 'No_extracts': 6},
 {'Library_code': 'PV081', 'No_extracts': 1},
 {'Library_code': 'PV082', 'No_extracts': 14},
 {'Library_code': 'PV083', 'No_extracts': 11},
 {'Library_code': 'PV084', 'No_extracts': 10},
 {'Library_code': 'PV085', 'No_extracts': 27},
 {'Library_code': 'PV086', 'No_extracts': 19},
 {'Library_code': 'PV087', 'No_extracts': 7},
 {'Library_code': 'PV088', 'No_extracts': 9},
 {'Library_code': 'PV089', 'No_extracts': 9},
 {'Library_code': 'PV090', 'No_extracts': 13},
 {'Library_code': 'PV091', 'No_extracts': 8},
 {'Library_code': 'PV092', 'No_extracts': 8},
 {'Library_code': 'PV093', 'No_extracts': 8},
 {'Library_code': 'PV094', 'No_extracts': 6},
 {'Library_code': 'PV095', 'No_extracts': 5},
 {'Library_code': 'PV096', 'No_extracts': 7},
 {'Library_code': 'PV097', 'No_extracts': 5},
 {'Library_code': 'PV098', 'No_extracts': 11},
 {'Library_code': 'PV099', 'No_extracts': 13},
 {'Library_code': 'PV100', 'No_extracts': 10},
 {'Library_code': 'PV101', 'No_extracts': 8},
 {'Library_code': 'PV102', 'No_extracts': 9},
 {'Library_code': 'PV103', 'No_extracts': 7},
 {'Library_code': 'PV104', 'No_extracts': 8},
 {'Library_code': 'PV105', 'No_extracts': 5},
 {'Library_code': 'PV106', 'No_extracts': 5},
 {'Library_code': 'PV107', 'No_extracts': 4},
 {'Library_code': 'PV108', 'No_extracts': 14},
 {'Library_code': 'PV109', 'No_extracts': 1},
 {'Library_code': 'PV110', 'No_extracts': 7},
 {'Library_code': 'PV111', 'No_extracts': 1},
 {'Library_code': 'PV112', 'No_extracts': 8},
 {'Library_code': 'PV113', 'No_extracts': 4},
 {'Library_code': 'PV114', 'No_extracts': 7},
 {'Library_code': 'PV115', 'No_extracts': 3},
 {'Library_code': 'PV116', 'No_extracts': 3},
 {'Library_code': 'PV117', 'No_extracts': 4},
 {'Library_code': 'PV118', 'No_extracts': 5},
 {'Library_code': 'PV119', 'No_extracts': 2},
 {'Library_code': 'PV120', 'No_extracts': 1},
 {'Library_code': 'PV121', 'No_extracts': 3},
 {'Library_code': 'PV122', 'No_extracts': 2},
 {'Library_code': 'PV123', 'No_extracts': 4},
 {'Library_code': 'PV124', 'No_extracts': 3},
 {'Library_code': 'PV125', 'No_extracts': 5},
 {'Library_code': 'PV126', 'No_extracts': 2},
 {'Library_code': 'PV127', 'No_extracts': 6},
 {'Library_code': 'PV128', 'No_extracts': 2},
 {'Library_code': 'PV129', 'No_extracts': 3},
 {'Library_code': 'PV130', 'No_extracts': 3},
 {'Library_code': 'PV131', 'No_extracts': 4},
 {'Library_code': 'PV132', 'No_extracts': 2},
 {'Library_code': 'PV133', 'No_extracts': 6},
 {'Library_code': 'PV134', 'No_extracts': 2},
 {'Library_code': 'PV135', 'No_extracts': 4},
 {'Library_code': 'PV136', 'No_extracts': 1},
 {'Library_code': 'PV137', 'No_extracts': 3},
 {'Library_code': 'PV138', 'No_extracts': 2},
 {'Library_code': 'PV139', 'No_extracts': 2},
 {'Library_code': 'PV140', 'No_extracts': 3},
 {'Library_code': 'PV141', 'No_extracts': 2},
 {'Library_code': 'PV142', 'No_extracts': 6},
 {'Library_code': 'PV143', 'No_extracts': 13},
 {'Library_code': 'PV144', 'No_extracts': 9},
 {'Library_code': 'PV145', 'No_extracts': 1},
 {'Library_code': 'PV146', 'No_extracts': 1},
 {'Library_code': 'PV147', 'No_extracts': 1},
 {'Library_code': 'PV148', 'No_extracts': 1},
 {'Library_code': 'PV149', 'No_extracts': 2},
 {'Library_code': 'PV150', 'No_extracts': 7},
 {'Library_code': 'PV151', 'No_extracts': 3},
 {'Library_code': 'PV152', 'No_extracts': 10},
 {'Library_code': 'PV153', 'No_extracts': 6},
 {'Library_code': 'PV154', 'No_extracts': 5},
 {'Library_code': 'PV155', 'No_extracts': 1},
 {'Library_code': 'PV156', 'No_extracts': 1},
 {'Library_code': 'PV157', 'No_extracts': 9},
 {'Library_code': 'PV158', 'No_extracts': 1},
 {'Library_code': 'PV159', 'No_extracts': 2},
 {'Library_code': 'PV160', 'No_extracts': 2},
 {'Library_code': 'PV161', 'No_extracts': 4},
 {'Library_code': 'PV162', 'No_extracts': 2},
 {'Library_code': 'PV163', 'No_extracts': 3},
 {'Library_code': 'PV164', 'No_extracts': 2},
 {'Library_code': 'PV165', 'No_extracts': 5},
 {'Library_code': 'PV166', 'No_extracts': 1},
 {'Library_code': 'PV167', 'No_extracts': 2},
 {'Library_code': 'PV168', 'No_extracts': 2},
 {'Library_code': 'PV169', 'No_extracts': 1},
 {'Library_code': 'PV170', 'No_extracts': 2},
 {'Library_code': 'PV171', 'No_extracts': 2},
 {'Library_code': 'PV172', 'No_extracts': 2},
 {'Library_code': 'PV173', 'No_extracts': 3},
 {'Library_code': 'PV174', 'No_extracts': 1},
 {'Library_code': 'PV175', 'No_extracts': 2},
 {'Library_code': 'PV176', 'No_extracts': 2},
 {'Library_code': 'PV177', 'No_extracts': 2},
 {'Library_code': 'PV178', 'No_extracts': 6},
 {'Library_code': 'PV179', 'No_extracts': 1},
 {'Library_code': 'PV180', 'No_extracts': 2},
 {'Library_code': 'PV181', 'No_extracts': 2},
 {'Library_code': 'PV182', 'No_extracts': 10},
 {'Library_code': 'PV183', 'No_extracts': 1},
 {'Library_code': 'PV184', 'No_extracts': 2},
 {'Library_code': 'PV185', 'No_extracts': 2},
 {'Library_code': 'PV186', 'No_extracts': 1},
 {'Library_code': 'PV187', 'No_extracts': 2},
 {'Library_code': 'PV188', 'No_extracts': 6},
 {'Library_code': 'PV189', 'No_extracts': 1},
 {'Library_code': 'PV190', 'No_extracts': 1},
 {'Library_code': 'PV191', 'No_extracts': 1},
 {'Library_code': 'PV192', 'No_extracts': 1},
 {'Library_code': 'PV193', 'No_extracts': 1},
 {'Library_code': 'PV194', 'No_extracts': 1},
 {'Library_code': 'PV195', 'No_extracts': 1},
 {'Library_code': 'PV196', 'No_extracts': 2},
 {'Library_code': 'PV197', 'No_extracts': 2},
 {'Library_code': 'PV198', 'No_extracts': 2},
 {'Library_code': 'PV199', 'No_extracts': 2},
 {'Library_code': 'PV200', 'No_extracts': 2},
 {'Library_code': 'PV201', 'No_extracts': 8},
 {'Library_code': 'PV202', 'No_extracts': 6},
 {'Library_code': 'PV203', 'No_extracts': 4},
 {'Library_code': 'PV204', 'No_extracts': 3},
 {'Library_code': 'PV205', 'No_extracts': 1},
 {'Library_code': 'PV206', 'No_extracts': 2},
 {'Library_code': 'PV207', 'No_extracts': 8},
 {'Library_code': 'PV208', 'No_extracts': 2},
 {'Library_code': 'PV209', 'No_extracts': 4},
 {'Library_code': 'PV210', 'No_extracts': 2},
 {'Library_code': 'PV211', 'No_extracts': 1},
 {'Library_code': 'PV212', 'No_extracts': 5},
 {'Library_code': 'PV213', 'No_extracts': 2},
 {'Library_code': 'PV214', 'No_extracts': 10},
 {'Library_code': 'PV215', 'No_extracts': 3},
 {'Library_code': 'PV216', 'No_extracts': 7},
 {'Library_code': 'PV217', 'No_extracts': 1},
 {'Library_code': 'PV218', 'No_extracts': 3},
 {'Library_code': 'PV219', 'No_extracts': 8},
 {'Library_code': 'PV220', 'No_extracts': 3},
 {'Library_code': 'PV221', 'No_extracts': 2},
 {'Library_code': 'PV222', 'No_extracts': 2},
 {'Library_code': 'PV223', 'No_extracts': 4},
 {'Library_code': 'PV224', 'No_extracts': 1},
 {'Library_code': 'PV225', 'No_extracts': 4},
 {'Library_code': 'PV226', 'No_extracts': 1},
 {'Library_code': 'PV227', 'No_extracts': 4},
 {'Library_code': 'PV228', 'No_extracts': 1},
 {'Library_code': 'PV229', 'No_extracts': 2},
 {'Library_code': 'PV230', 'No_extracts': 1},
 {'Library_code': 'PV231', 'No_extracts': 6},
 {'Library_code': 'PV232', 'No_extracts': 1},
 {'Library_code': 'PV233', 'No_extracts': 2},
 {'Library_code': 'PV234', 'No_extracts': 2},
 {'Library_code': 'PV235', 'No_extracts': 3},
 {'Library_code': 'PV236', 'No_extracts': 1},
 {'Library_code': 'PV237', 'No_extracts': 2},
 {'Library_code': 'PV252', 'No_extracts': 1},
 {'Library_code': 'PV257', 'No_extracts': 9},
 {'Library_code': 'PV262', 'No_extracts': 9},
 {'Library_code': 'PV268', 'No_extracts': 1},
 {'Library_code': 'PV269', 'No_extracts': 3},
 {'Library_code': 'PV270', 'No_extracts': 1},
 {'Library_code': 'PV277', 'No_extracts': 5},
 {'Library_code': 'PV296', 'No_extracts': 6},
 {'Library_code': 'PV298', 'No_extracts': 15},
 {'Library_code': 'PV306', 'No_extracts': 3},
 {'Library_code': 'PV312', 'No_extracts': 7},
 {'Library_code': 'PV313', 'No_extracts': 1},
 {'Library_code': 'PV330', 'No_extracts': 1},
 {'Library_code': 'PV350', 'No_extracts': 3},
 {'Library_code': 'PV352', 'No_extracts': 7},
 {'Library_code': 'PV356', 'No_extracts': 13},
 {'Library_code': 'PV359', 'No_extracts': 6},
 {'Library_code': 'PV369', 'No_extracts': 3},
 {'Library_code': 'PV380', 'No_extracts': 6},
 {'Library_code': 'PV386', 'No_extracts': 7},
 {'Library_code': 'PV390', 'No_extracts': 4},
 {'Library_code': 'PV418', 'No_extracts': 1},
 {'Library_code': 'PV421', 'No_extracts': 4},
 {'Library_code': 'PV423', 'No_extracts': 6},
 {'Library_code': 'PV426', 'No_extracts': 3},
 {'Library_code': 'PV428', 'No_extracts': 2},
 {'Library_code': 'PV430', 'No_extracts': 1},
 {'Library_code': 'PV437', 'No_extracts': 11},
 {'Library_code': 'PV440', 'No_extracts': 3},
 {'Library_code': 'PV441', 'No_extracts': 5},
 {'Library_code': 'PV454', 'No_extracts': 11},
 {'Library_code': 'PV457', 'No_extracts': 1},
 {'Library_code': 'PV464', 'No_extracts': 5},
 {'Library_code': 'PV473', 'No_extracts': 3},
 {'Library_code': 'PV489', 'No_extracts': 40},
 {'Library_code': 'PV491', 'No_extracts': 1},
 {'Library_code': 'PV495', 'No_extracts': 4},
 {'Library_code': 'PV496', 'No_extracts': 3},
 {'Library_code': 'PV498', 'No_extracts': 9},
 {'Library_code': 'PV500', 'No_extracts': 4},
 {'Library_code': 'PV501', 'No_extracts': 1},
 {'Library_code': 'PV503', 'No_extracts': 24},
 {'Library_code': 'PV505', 'No_extracts': 1},
 {'Library_code': 'PV514', 'No_extracts': 3},
 {'Library_code': 'PV516', 'No_extracts': 1},
 {'Library_code': 'PV519', 'No_extracts': 4},
 {'Library_code': 'PV525', 'No_extracts': 1},
 {'Library_code': 'PV526', 'No_extracts': 1},
 {'Library_code': 'PV527', 'No_extracts': 4},
 {'Library_code': 'PV529', 'No_extracts': 1},
 {'Library_code': 'PV534', 'No_extracts': 3},
 {'Library_code': 'PV535', 'No_extracts': 17},
 {'Library_code': 'PV538', 'No_extracts': 8},
 {'Library_code': 'PV540', 'No_extracts': 1},
 {'Library_code': 'PV544', 'No_extracts': 4},
 {'Library_code': 'PV546', 'No_extracts': 1},
 {'Library_code': 'PV551', 'No_extracts': 1},
 {'Library_code': 'PV553', 'No_extracts': 1},
 {'Library_code': 'PV554', 'No_extracts': 17},
 {'Library_code': 'PV556', 'No_extracts': 3},
 {'Library_code': 'PV557', 'No_extracts': 1},
 {'Library_code': 'PV558', 'No_extracts': 1},
 {'Library_code': 'PV559', 'No_extracts': 1},
 {'Library_code': 'PV560', 'No_extracts': 1},
 {'Library_code': 'PV561', 'No_extracts': 8},
 {'Library_code': 'PV562', 'No_extracts': 8},
 {'Library_code': 'PV563', 'No_extracts': 6},
 {'Library_code': 'PV564', 'No_extracts': 8},
 {'Library_code': 'PV565', 'No_extracts': 4},
 {'Library_code': 'PV566', 'No_extracts': 7},
 {'Library_code': 'PV567', 'No_extracts': 4},
 {'Library_code': 'PV568', 'No_extracts': 5},
 {'Library_code': 'PV569', 'No_extracts': 8},
 {'Library_code': 'PV570', 'No_extracts': 3},
 {'Library_code': 'PV571', 'No_extracts': 8},
 {'Library_code': 'PV572', 'No_extracts': 3},
 {'Library_code': 'PV573', 'No_extracts': 4},
 {'Library_code': 'PV574', 'No_extracts': 8},
 {'Library_code': 'PV575', 'No_extracts': 3},
 {'Library_code': 'PV576', 'No_extracts': 3},
 {'Library_code': 'PV577', 'No_extracts': 3},
 {'Library_code': 'PV578', 'No_extracts': 4},
 {'Library_code': 'PV579', 'No_extracts': 8},
 {'Library_code': 'PV580', 'No_extracts': 5},
 {'Library_code': 'PV581', 'No_extracts': 5},
 {'Library_code': 'PV582', 'No_extracts': 6},
 {'Library_code': 'PV583', 'No_extracts': 6},
 {'Library_code': 'PV584', 'No_extracts': 5},
 {'Library_code': 'PV585', 'No_extracts': 6},
 {'Library_code': 'PV586', 'No_extracts': 8},
 {'Library_code': 'PV587', 'No_extracts': 8},
 {'Library_code': 'PV588', 'No_extracts': 8},
 {'Library_code': 'PV589', 'No_extracts': 8},
 {'Library_code': 'PV590', 'No_extracts': 11}]

In [15]:
site_library = dict(
    library=libraries,
    library_dates=dates,
    site=sites, 
    library_site=library_site
)
with open("scratch/semantic-model/library.json", "w") as f:
    json.dump(site_library, f, indent=4, sort_keys=True)

## Step 2 - Hosts

In [16]:
libraries = pd.read_csv("data/mcleish24-TableS2.csv", sep=';')
libraries

    Library_code            Host_taxon Habitat Collection_code  No_extracts
0          PV001         Amaranthus sp    Crop             M1V            8
1          PV002  Convolvulus arvensis    Crop             M1V           11
2          PV003          Cucumis melo    Crop             M1V           13
3       PV003bgi          Cucumis melo    Crop             M1V           13
4       PV004bgi        Cyperus longus    Crop             M1V            7
..           ...                   ...     ...             ...          ...
318        PV586    Fumaria parviflora    Crop             H1P            8
319        PV587   Hirschfeldia incana    Crop             H1P            8
320        PV588       Hordeum vulgare    Crop             H1P            8
321        PV589       Hordeum vulgare    Crop             H1P            8
322        PV590              Zea mays    Crop             Z1V           11

[323 rows x 5 columns]

In [17]:
libraries[['Host_taxon', 'Library_code']]

               Host_taxon Library_code
0           Amaranthus sp        PV001
1    Convolvulus arvensis        PV002
2            Cucumis melo        PV003
3            Cucumis melo     PV003bgi
4          Cyperus longus     PV004bgi
..                    ...          ...
318    Fumaria parviflora        PV586
319   Hirschfeldia incana        PV587
320       Hordeum vulgare        PV588
321       Hordeum vulgare        PV589
322              Zea mays        PV590

[323 rows x 2 columns]

In [18]:
def search_taxonomy(host_name):
    url = "https://api.ncbi.nlm.nih.gov/datasets/v2"
    url = f'{url}/taxonomy/taxon/{host_name}'.replace(' ', '%20')

    r = requests.get(url)
    try: 
        r.raise_for_status()
    except requests.HTTPError:
        return pd.NA
    try:
        u = str(r.json()['taxonomy_nodes'][0]['taxonomy']['tax_id'])
    except KeyError:
        return pd.NA
    except IndexError:
        return pd.NA
    return u

In [19]:
hosts = libraries.drop_duplicates(subset=['Host_taxon'])[['Host_taxon']]
hosts['Host_curated'] = hosts['Host_taxon'].apply(lambda x: x.replace(' sp', ' sp.'))
hosts['Host_curated'] = hosts['Host_curated'].apply(lambda x: " ".join(x.split(" ")[:2]))
species_taxid_map = []
for item in hosts['Host_curated'].unique().tolist():
    species_taxid_map.append(
        dict(species_name=item, taxid=search_taxonomy(item))
    )
hosts = pd.merge(hosts, pd.DataFrame.from_records(species_taxid_map), left_on='Host_curated', right_on='species_name')
hosts = hosts[['Host_taxon', 'taxid']]
hosts['Taxon_code'] = [hostids() for _ in range(len(hosts))]
hosts

               Host_taxon    taxid    Taxon_code
0           Amaranthus sp  3076757  000000000000
1    Convolvulus arvensis     4123  000000000001
2            Cucumis melo     3656  000000000002
3          Cyperus longus    76433  000000000003
4    Artemisia herba alba     <NA>  000000000004
..                    ...      ...           ...
114   Lithodora fruticosa   475890  000000000114
115      Origanum vulgare    39352  000000000115
116     Rhamnus lycioides    72169  000000000116
117   Astragalus sesameus  2014722  000000000117
118    Borago officinalis    13363  000000000118

[119 rows x 3 columns]

In [20]:
hosts_library = pd.merge(hosts, libraries, on=['Host_taxon']).drop_duplicates(['Taxon_code', 'Library_code'], keep='first')[['Taxon_code', 'Library_code']].to_dict(orient='records')
hosts_library

[{'Taxon_code': '000000000000', 'Library_code': 'PV001'},
 {'Taxon_code': '000000000000', 'Library_code': 'PV033'},
 {'Taxon_code': '000000000000', 'Library_code': 'PV175'},
 {'Taxon_code': '000000000000', 'Library_code': 'PV196'},
 {'Taxon_code': '000000000000', 'Library_code': 'PV212'},
 {'Taxon_code': '000000000001', 'Library_code': 'PV002'},
 {'Taxon_code': '000000000001', 'Library_code': 'PV031'},
 {'Taxon_code': '000000000001', 'Library_code': 'PV079'},
 {'Taxon_code': '000000000001', 'Library_code': 'PV097'},
 {'Taxon_code': '000000000001', 'Library_code': 'PV132'},
 {'Taxon_code': '000000000001', 'Library_code': 'PV142'},
 {'Taxon_code': '000000000001', 'Library_code': 'PV154'},
 {'Taxon_code': '000000000001', 'Library_code': 'PV161'},
 {'Taxon_code': '000000000001', 'Library_code': 'PV188'},
 {'Taxon_code': '000000000001', 'Library_code': 'PV201'},
 {'Taxon_code': '000000000001', 'Library_code': 'PV214'},
 {'Taxon_code': '000000000001', 'Library_code': 'PV226'},
 {'Taxon_code': '000000000001', 'Library_code': 'PV496'},
 {'Taxon_code': '000000000001', 'Library_code': 'PV527'},
 {'Taxon_code': '000000000002', 'Library_code': 'PV003'},
 {'Taxon_code': '000000000002', 'Library_code': 'PV003bgi'},
 {'Taxon_code': '000000000002', 'Library_code': 'PV015bgi'},
 {'Taxon_code': '000000000002', 'Library_code': 'PV016'},
 {'Taxon_code': '000000000002', 'Library_code': 'PV018bgi'},
 {'Taxon_code': '000000000002', 'Library_code': 'PV021bgi'},
 {'Taxon_code': '000000000002', 'Library_code': 'PV061'},
 {'Taxon_code': '000000000002', 'Library_code': 'PV062'},
 {'Taxon_code': '000000000002', 'Library_code': 'PV063'},
 {'Taxon_code': '000000000003', 'Library_code': 'PV004bgi'},
 {'Taxon_code': '000000000004', 'Library_code': 'PV005bgi'},
 {'Taxon_code': '000000000004', 'Library_code': 'PV006bgi'},
 {'Taxon_code': '000000000004', 'Library_code': 'PV064'},
 {'Taxon_code': '000000000005', 'Library_code': 'PV007bgi'},
 {'Taxon_code': '000000000005', 'Library_code': 'PV083'},
 {'Taxon_code': '000000000005', 'Library_code': 'PV111'},
 {'Taxon_code': '000000000005', 'Library_code': 'PV369'},
 {'Taxon_code': '000000000006', 'Library_code': 'PV008bgi'},
 {'Taxon_code': '000000000006', 'Library_code': 'PV093'},
 {'Taxon_code': '000000000007', 'Library_code': 'PV009'},
 {'Taxon_code': '000000000007', 'Library_code': 'PV009bgi'},
 {'Taxon_code': '000000000007', 'Library_code': 'PV035'},
 {'Taxon_code': '000000000007', 'Library_code': 'PV042'},
 {'Taxon_code': '000000000007', 'Library_code': 'PV107'},
 {'Taxon_code': '000000000008', 'Library_code': 'PV010bgi'},
 {'Taxon_code': '000000000008', 'Library_code': 'PV036'},
 {'Taxon_code': '000000000008', 'Library_code': 'PV108'},
 {'Taxon_code': '000000000009', 'Library_code': 'PV011'},
 {'Taxon_code': '000000000010', 'Library_code': 'PV012bgi'},
 {'Taxon_code': '000000000010', 'Library_code': 'PV131'},
 {'Taxon_code': '000000000010', 'Library_code': 'PV160'},
 {'Taxon_code': '000000000010', 'Library_code': 'PV167'},
 {'Taxon_code': '000000000010', 'Library_code': 'PV178'},
 {'Taxon_code': '000000000010', 'Library_code': 'PV200'},
 {'Taxon_code': '000000000011', 'Library_code': 'PV013bgi'},
 {'Taxon_code': '000000000011', 'Library_code': 'PV185'},
 {'Taxon_code': '000000000011', 'Library_code': 'PV211'},
 {'Taxon_code': '000000000012', 'Library_code': 'PV014'},
 {'Taxon_code': '000000000012', 'Library_code': 'PV049'},
 {'Taxon_code': '000000000012', 'Library_code': 'PV217'},
 {'Taxon_code': '000000000013', 'Library_code': 'PV017bgi'},
 {'Taxon_code': '000000000013', 'Library_code': 'PV020bgi'},
 {'Taxon_code': '000000000013', 'Library_code': 'PV081'},
 {'Taxon_code': '000000000014', 'Library_code': 'PV022'},
 {'Taxon_code': '000000000014', 'Library_code': 'PV072'},
 {'Taxon_code': '000000000014', 'Library_code': 'PV075'},
 {'Taxon_code': '000000000015', 'Library_code': 'PV023'},
 {'Taxon_code': '000000000015', 'Library_code': 'PV068'},
 {'Taxon_code': '000000000015', 'Library_code': 'PV074'},
 {'Taxon_code': '000000000015', 'Library_code': 'PV120'},
 {'Taxon_code': '000000000015', 'Library_code': 'PV441'},
 {'Taxon_code': '000000000016', 'Library_code': 'PV024'},
 {'Taxon_code': '000000000016', 'Library_code': 'PV076'},
 {'Taxon_code': '000000000016', 'Library_code': 'PV086'},
 {'Taxon_code': '000000000017', 'Library_code': 'PV025'},
 {'Taxon_code': '000000000017', 'Library_code': 'PV189'},
 {'Taxon_code': '000000000017', 'Library_code': 'PV205'},
 {'Taxon_code': '000000000017', 'Library_code': 'PV437'},
 {'Taxon_code': '000000000018', 'Library_code': 'PV026'},
 {'Taxon_code': '000000000019', 'Library_code': 'PV027'},
 {'Taxon_code': '000000000020', 'Library_code': 'PV028'},
 {'Taxon_code': '000000000020', 'Library_code': 'PV139'},
 {'Taxon_code': '000000000020', 'Library_code': 'PV158'},
 {'Taxon_code': '000000000020', 'Library_code': 'PV173'},
 {'Taxon_code': '000000000020', 'Library_code': 'PV190'},
 {'Taxon_code': '000000000020', 'Library_code': 'PV208'},
 {'Taxon_code': '000000000020', 'Library_code': 'PV252'},
 {'Taxon_code': '000000000020', 'Library_code': 'PV464'},
 {'Taxon_code': '000000000020', 'Library_code': 'PV498'},
 {'Taxon_code': '000000000021', 'Library_code': 'PV029'},
 {'Taxon_code': '000000000021', 'Library_code': 'PV098'},
 {'Taxon_code': '000000000021', 'Library_code': 'PV122'},
 {'Taxon_code': '000000000021', 'Library_code': 'PV172'},
 {'Taxon_code': '000000000021', 'Library_code': 'PV183'},
 {'Taxon_code': '000000000021', 'Library_code': 'PV195'},
 {'Taxon_code': '000000000021', 'Library_code': 'PV207'},
 {'Taxon_code': '000000000021', 'Library_code': 'PV516'},
 {'Taxon_code': '000000000021', 'Library_code': 'PV529'},
 {'Taxon_code': '000000000021', 'Library_code': 'PV540'},
 {'Taxon_code': '000000000022', 'Library_code': 'PV030'},
 {'Taxon_code': '000000000022', 'Library_code': 'PV096'},
 {'Taxon_code': '000000000023', 'Library_code': 'PV032'},
 {'Taxon_code': '000000000023', 'Library_code': 'PV034'},
 {'Taxon_code': '000000000023', 'Library_code': 'PV198'},
 {'Taxon_code': '000000000024', 'Library_code': 'PV037'},
 {'Taxon_code': '000000000024', 'Library_code': 'PV101'},
 {'Taxon_code': '000000000024', 'Library_code': 'PV270'},
 {'Taxon_code': '000000000025', 'Library_code': 'PV041'},
 {'Taxon_code': '000000000026', 'Library_code': 'PV046'},
 {'Taxon_code': '000000000026', 'Library_code': 'PV066'},
 {'Taxon_code': '000000000026', 'Library_code': 'PV113'},
 {'Taxon_code': '000000000026', 'Library_code': 'PV130'},
 {'Taxon_code': '000000000026', 'Library_code': 'PV153'},
 {'Taxon_code': '000000000026', 'Library_code': 'PV159'},
 {'Taxon_code': '000000000026', 'Library_code': 'PV166'},
 {'Taxon_code': '000000000026', 'Library_code': 'PV199'},
 {'Taxon_code': '000000000026', 'Library_code': 'PV213'},
 {'Taxon_code': '000000000027', 'Library_code': 'PV047'},
 {'Taxon_code': '000000000027', 'Library_code': 'PV590'},
 {'Taxon_code': '000000000028', 'Library_code': 'PV048'},
 {'Taxon_code': '000000000028', 'Library_code': 'PV228'},
 {'Taxon_code': '000000000028', 'Library_code': 'PV519'},
 {'Taxon_code': '000000000029', 'Library_code': 'PV050'},
 {'Taxon_code': '000000000030', 'Library_code': 'PV051'},
 {'Taxon_code': '000000000031', 'Library_code': 'PV052'},
 {'Taxon_code': '000000000031', 'Library_code': 'PV053'},
 {'Taxon_code': '000000000032', 'Library_code': 'PV054'},
 {'Taxon_code': '000000000032', 'Library_code': 'PV055'},
 {'Taxon_code': '000000000033', 'Library_code': 'PV056'},
 {'Taxon_code': '000000000034', 'Library_code': 'PV057'},
 {'Taxon_code': '000000000035', 'Library_code': 'PV058'},
 {'Taxon_code': '000000000035', 'Library_code': 'PV128'},
 {'Taxon_code': '000000000035', 'Library_code': 'PV224'},
 {'Taxon_code': '000000000036', 'Library_code': 'PV059'},
 {'Taxon_code': '000000000037', 'Library_code': 'PV060'},
 {'Taxon_code': '000000000037', 'Library_code': 'PV109'},
 {'Taxon_code': '000000000038', 'Library_code': 'PV065'},
 {'Taxon_code': '000000000038', 'Library_code': 'PV117'},
 {'Taxon_code': '000000000038', 'Library_code': 'PV143'},
 {'Taxon_code': '000000000038', 'Library_code': 'PV181'},
 {'Taxon_code': '000000000038', 'Library_code': 'PV204'},
 {'Taxon_code': '000000000038', 'Library_code': 'PV219'},
 {'Taxon_code': '000000000038', 'Library_code': 'PV229'},
 {'Taxon_code': '000000000038', 'Library_code': 'PV514'},
 {'Taxon_code': '000000000038', 'Library_code': 'PV525'},
 {'Taxon_code': '000000000038', 'Library_code': 'PV534'},
 {'Taxon_code': '000000000038', 'Library_code': 'PV551'},
 {'Taxon_code': '000000000039', 'Library_code': 'PV069'},
 {'Taxon_code': '000000000040', 'Library_code': 'PV070'},
 {'Taxon_code': '000000000040', 'Library_code': 'PV134'},
 {'Taxon_code': '000000000041', 'Library_code': 'PV071'},
 {'Taxon_code': '000000000042', 'Library_code': 'PV078'},
 {'Taxon_code': '000000000042', 'Library_code': 'PV115'},
 {'Taxon_code': '000000000042', 'Library_code': 'PV129'},
 {'Taxon_code': '000000000042', 'Library_code': 'PV141'},
 {'Taxon_code': '000000000042', 'Library_code': 'PV423'},
 {'Taxon_code': '000000000042', 'Library_code': 'PV501'},
 {'Taxon_code': '000000000043', 'Library_code': 'PV080'},
 {'Taxon_code': '000000000044', 'Library_code': 'PV082'},
 {'Taxon_code': '000000000044', 'Library_code': 'PV089'},
 {'Taxon_code': '000000000045', 'Library_code': 'PV084'},
 {'Taxon_code': '000000000045', 'Library_code': 'PV298'},
 {'Taxon_code': '000000000046', 'Library_code': 'PV085'},
 {'Taxon_code': '000000000047', 'Library_code': 'PV087'},
 {'Taxon_code': '000000000047', 'Library_code': 'PV230'},
 {'Taxon_code': '000000000048', 'Library_code': 'PV088'},
 {'Taxon_code': '000000000049', 'Library_code': 'PV090'},
 {'Taxon_code': '000000000049', 'Library_code': 'PV104'},
 {'Taxon_code': '000000000049', 'Library_code': 'PV380'},
 {'Taxon_code': '000000000050', 'Library_code': 'PV091'},
 {'Taxon_code': '000000000050', 'Library_code': 'PV105'},
 {'Taxon_code': '000000000050', 'Library_code': 'PV169'},
 {'Taxon_code': '000000000050', 'Library_code': 'PV193'},
 {'Taxon_code': '000000000050', 'Library_code': 'PV262'},
 {'Taxon_code': '000000000051', 'Library_code': 'PV092'},
 {'Taxon_code': '000000000051', 'Library_code': 'PV099'},
 {'Taxon_code': '000000000051', 'Library_code': 'PV165'},
 {'Taxon_code': '000000000051', 'Library_code': 'PV192'},
 {'Taxon_code': '000000000052', 'Library_code': 'PV094'},
 {'Taxon_code': '000000000053', 'Library_code': 'PV095'},
 {'Taxon_code': '000000000054', 'Library_code': 'PV100'},
 {'Taxon_code': '000000000055', 'Library_code': 'PV102'},
 {'Taxon_code': '000000000056', 'Library_code': 'PV103'},
 {'Taxon_code': '000000000056', 'Library_code': 'PV312'},
 {'Taxon_code': '000000000057', 'Library_code': 'PV106'},
 {'Taxon_code': '000000000058', 'Library_code': 'PV110'},
 {'Taxon_code': '000000000059', 'Library_code': 'PV112'},
 {'Taxon_code': '000000000059', 'Library_code': 'PV313'},
 {'Taxon_code': '000000000060', 'Library_code': 'PV114'},
 {'Taxon_code': '000000000061', 'Library_code': 'PV116'},
 {'Taxon_code': '000000000061', 'Library_code': 'PV218'},
 {'Taxon_code': '000000000061', 'Library_code': 'PV227'},
 {'Taxon_code': '000000000062', 'Library_code': 'PV118'},
 {'Taxon_code': '000000000063', 'Library_code': 'PV119'},
 {'Taxon_code': '000000000063', 'Library_code': 'PV136'},
 {'Taxon_code': '000000000063', 'Library_code': 'PV170'},
 {'Taxon_code': '000000000063', 'Library_code': 'PV182'},
 {'Taxon_code': '000000000063', 'Library_code': 'PV206'},
 {'Taxon_code': '000000000063', 'Library_code': 'PV221'},
 {'Taxon_code': '000000000064', 'Library_code': 'PV121'},
 {'Taxon_code': '000000000064', 'Library_code': 'PV145'},
 {'Taxon_code': '000000000064', 'Library_code': 'PV157'},
 {'Taxon_code': '000000000064', 'Library_code': 'PV231'},
 {'Taxon_code': '000000000065', 'Library_code': 'PV123'},
 {'Taxon_code': '000000000065', 'Library_code': 'PV209'},
 {'Taxon_code': '000000000065', 'Library_code': 'PV234'},
 {'Taxon_code': '000000000065', 'Library_code': 'PV553'},
 {'Taxon_code': '000000000065', 'Library_code': 'PV567'},
 {'Taxon_code': '000000000065', 'Library_code': 'PV568'},
 {'Taxon_code': '000000000066', 'Library_code': 'PV124'},
 {'Taxon_code': '000000000066', 'Library_code': 'PV146'},
 {'Taxon_code': '000000000066', 'Library_code': 'PV222'},
 {'Taxon_code': '000000000067', 'Library_code': 'PV125'},
 {'Taxon_code': '000000000068', 'Library_code': 'PV126'},
 {'Taxon_code': '000000000068', 'Library_code': 'PV140'},
 {'Taxon_code': '000000000068', 'Library_code': 'PV149'},
 {'Taxon_code': '000000000068', 'Library_code': 'PV174'},
 {'Taxon_code': '000000000068', 'Library_code': 'PV184'},
 {'Taxon_code': '000000000068', 'Library_code': 'PV223'},
 {'Taxon_code': '000000000068', 'Library_code': 'PV235'},
 {'Taxon_code': '000000000068', 'Library_code': 'PV569'},
 {'Taxon_code': '000000000069', 'Library_code': 'PV127'},
 {'Taxon_code': '000000000070', 'Library_code': 'PV133'},
 {'Taxon_code': '000000000071', 'Library_code': 'PV135'},
 {'Taxon_code': '000000000071', 'Library_code': 'PV144'},
 {'Taxon_code': '000000000071', 'Library_code': 'PV155'},
 {'Taxon_code': '000000000071', 'Library_code': 'PV586'},
 {'Taxon_code': '000000000072', 'Library_code': 'PV137'},
 {'Taxon_code': '000000000072', 'Library_code': 'PV163'},
 {'Taxon_code': '000000000072', 'Library_code': 'PV171'},
 {'Taxon_code': '000000000072', 'Library_code': 'PV232'},
 {'Taxon_code': '000000000073', 'Library_code': 'PV138'},
 {'Taxon_code': '000000000074', 'Library_code': 'PV147'},
 {'Taxon_code': '000000000074', 'Library_code': 'PV194'},
 {'Taxon_code': '000000000074', 'Library_code': 'PV386'},
 {'Taxon_code': '000000000074', 'Library_code': 'PV430'},
 {'Taxon_code': '000000000075', 'Library_code': 'PV148'},
 {'Taxon_code': '000000000076', 'Library_code': 'PV150'},
 {'Taxon_code': '000000000076', 'Library_code': 'PV197'},
 {'Taxon_code': '000000000077', 'Library_code': 'PV151'},
 {'Taxon_code': '000000000077', 'Library_code': 'PV418'},
 {'Taxon_code': '000000000078', 'Library_code': 'PV152'},
 {'Taxon_code': '000000000078', 'Library_code': 'PV187'},
 {'Taxon_code': '000000000079', 'Library_code': 'PV156'},
 {'Taxon_code': '000000000079', 'Library_code': 'PV587'},
 {'Taxon_code': '000000000080', 'Library_code': 'PV162'},
 {'Taxon_code': '000000000080', 'Library_code': 'PV168'},
 {'Taxon_code': '000000000080', 'Library_code': 'PV179'},
 {'Taxon_code': '000000000081', 'Library_code': 'PV164'},
 {'Taxon_code': '000000000081', 'Library_code': 'PV186'},
 {'Taxon_code': '000000000082', 'Library_code': 'PV176'},
 {'Taxon_code': '000000000082', 'Library_code': 'PV277'},
 {'Taxon_code': '000000000082', 'Library_code': 'PV495'},
 {'Taxon_code': '000000000083', 'Library_code': 'PV177'},
 {'Taxon_code': '000000000084', 'Library_code': 'PV180'},
 {'Taxon_code': '000000000084', 'Library_code': 'PV203'},
 {'Taxon_code': '000000000084', 'Library_code': 'PV210'},
 {'Taxon_code': '000000000084', 'Library_code': 'PV216'},
 {'Taxon_code': '000000000085', 'Library_code': 'PV191'},
 {'Taxon_code': '000000000086', 'Library_code': 'PV202'},
 {'Taxon_code': '000000000086', 'Library_code': 'PV215'},
 {'Taxon_code': '000000000087', 'Library_code': 'PV220'},
 {'Taxon_code': '000000000088', 'Library_code': 'PV225'},
 {'Taxon_code': '000000000089', 'Library_code': 'PV233'},
 {'Taxon_code': '000000000089', 'Library_code': 'PV526'},
 {'Taxon_code': '000000000090', 'Library_code': 'PV236'},
 {'Taxon_code': '000000000091', 'Library_code': 'PV237'},
 {'Taxon_code': '000000000091', 'Library_code': 'PV350'},
 {'Taxon_code': '000000000091', 'Library_code': 'PV426'},
 {'Taxon_code': '000000000091', 'Library_code': 'PV557'},
 {'Taxon_code': '000000000092', 'Library_code': 'PV257'},
 {'Taxon_code': '000000000092', 'Library_code': 'PV500'},
 {'Taxon_code': '000000000093', 'Library_code': 'PV268'},
 {'Taxon_code': '000000000093', 'Library_code': 'PV544'},
 {'Taxon_code': '000000000094', 'Library_code': 'PV269'},
 {'Taxon_code': '000000000094', 'Library_code': 'PV560'},
 {'Taxon_code': '000000000095', 'Library_code': 'PV296'},
 {'Taxon_code': '000000000095', 'Library_code': 'PV559'},
 {'Taxon_code': '000000000096', 'Library_code': 'PV306'},
 {'Taxon_code': '000000000096', 'Library_code': 'PV421'},
 {'Taxon_code': '000000000097', 'Library_code': 'PV330'},
 {'Taxon_code': '000000000097', 'Library_code': 'PV558'},
 {'Taxon_code': '000000000098', 'Library_code': 'PV352'},
 {'Taxon_code': '000000000098', 'Library_code': 'PV473'},
 {'Taxon_code': '000000000099', 'Library_code': 'PV356'},
 {'Taxon_code': '000000000099', 'Library_code': 'PV428'},
 {'Taxon_code': '000000000100', 'Library_code': 'PV359'},
 {'Taxon_code': '000000000100', 'Library_code': 'PV457'},
 {'Taxon_code': '000000000101', 'Library_code': 'PV390'},
 {'Taxon_code': '000000000101', 'Library_code': 'PV440'},
 {'Taxon_code': '000000000102', 'Library_code': 'PV454'},
 {'Taxon_code': '000000000102', 'Library_code': 'PV546'},
 {'Taxon_code': '000000000103', 'Library_code': 'PV489'},
 {'Taxon_code': '000000000103', 'Library_code': 'PV491'},
 {'Taxon_code': '000000000103', 'Library_code': 'PV503'},
 {'Taxon_code': '000000000103', 'Library_code': 'PV505'},
 {'Taxon_code': '000000000103', 'Library_code': 'PV588'},
 {'Taxon_code': '000000000103', 'Library_code': 'PV589'},
 {'Taxon_code': '000000000104', 'Library_code': 'PV535'},
 {'Taxon_code': '000000000104', 'Library_code': 'PV538'},
 {'Taxon_code': '000000000104', 'Library_code': 'PV554'},
 {'Taxon_code': '000000000104', 'Library_code': 'PV556'},
 {'Taxon_code': '000000000105', 'Library_code': 'PV561'},
 {'Taxon_code': '000000000106', 'Library_code': 'PV562'},
 {'Taxon_code': '000000000106', 'Library_code': 'PV563'},
 {'Taxon_code': '000000000107', 'Library_code': 'PV564'},
 {'Taxon_code': '000000000107', 'Library_code': 'PV565'},
 {'Taxon_code': '000000000108', 'Library_code': 'PV566'},
 {'Taxon_code': '000000000109', 'Library_code': 'PV570'},
 {'Taxon_code': '000000000110', 'Library_code': 'PV571'},
 {'Taxon_code': '000000000111', 'Library_code': 'PV572'},
 {'Taxon_code': '000000000111', 'Library_code': 'PV573'},
 {'Taxon_code': '000000000112', 'Library_code': 'PV574'},
 {'Taxon_code': '000000000113', 'Library_code': 'PV575'},
 {'Taxon_code': '000000000113', 'Library_code': 'PV576'},
 {'Taxon_code': '000000000114', 'Library_code': 'PV577'},
 {'Taxon_code': '000000000115', 'Library_code': 'PV578'},
 {'Taxon_code': '000000000116', 'Library_code': 'PV579'},
 {'Taxon_code': '000000000116', 'Library_code': 'PV580'},
 {'Taxon_code': '000000000116', 'Library_code': 'PV581'},
 {'Taxon_code': '000000000116', 'Library_code': 'PV582'},
 {'Taxon_code': '000000000117', 'Library_code': 'PV583'},
 {'Taxon_code': '000000000117', 'Library_code': 'PV584'},
 {'Taxon_code': '000000000118', 'Library_code': 'PV585'}]

In [21]:
host_library = dict(
    host=hosts.to_dict(orient='records'),
    host_library=hosts_library
)
with open("scratch/semantic-model/host_library.json", "w") as f:
    json.dump(host_library, f, indent=4, sort_keys=True)

## Step 3 - Virus

The file provided by Fernando requires some actions to turn it from its matrix form into a list of Library - Otu, which will be much easier to analyze later.

In [22]:
def extract_taxonomy_from_gene_records(host_name):
    url = "https://api.ncbi.nlm.nih.gov/datasets/v2"
    url = f'{url}/gene/accession/{host_name}/dataset_report'.replace(' ', '%20')
    r = requests.get(url)
    
    try: 
        r.raise_for_status()
    except requests.HTTPError:
        return pd.NA
    try:
        u = str(r.json()['reports'][0]['gene']['tax_id'])
    except KeyError:
        return pd.NA
    except IndexError:
        return pd.NA
    return u

In [23]:
virus = pd.read_csv("data/mcleish24-TableS4.csv", sep=';')
virus['OTU_taxid'] = virus['NCBI_accession'].apply(extract_taxonomy_from_gene_records)
virus

,OTU name,Family,NCBI_title,OTU_reference,Genome,%_ID_mean,%_ID_min,%_ID_max,BLAST_matches,NCBI_accession,OTU_taxid
0,Alfamovirus 1,Bromoviridae,Alfalfa mosaic virus RNA 1,AMV1,(+)ssRNA,96.6,94.4,99.2,4,NC_001495,12321
1,Alfamovirus 1,Bromoviridae,Alfalfa mosaic virus RNA 2,AMV2,(+)ssRNA,94.1,94.1,94.1,2,NC_002024,12321
2,Alphaendornavirus 1,Endornaviridae,Cucumis melo endornavirus,CmEV,dsRNA,96.5,87.9,100.0,4174,NC_029064,1776177
3,Alphaendornavirus 2,Endornaviridae,Bell pepper endornavirus,BPEV,dsRNA,100.0,100.0,100.0,2,NC_015781,<NA>
4,Alphaendornavirus 3,Endornaviridae,Hordeum vulgare endornavirus,HvEV,dsRNA,96.6,87.2,100.0,4002,NC_028949,1774276
...,...,...,...,...,...,...,...,...,...,...,...
172,Comovirus,Secoviridae,Arabidopsis latent virus-1 RNA1,ALaV1,(+)ssRNA,99.5,97.3,100.0,52,MH899120,<NA>
173,Comovirus,Secoviridae,Arabidopsis latent virus-1 RNA2,ALaV2,(+)ssRNA,97.6,94.0,100.0,30,MH899121,<NA>
174,Varicosavirus 1,Rhabdoviridae,Lettuce big-vein associated virus RNA 1,LBVaV1,(-)ssRNA,95.3,93.3,97.3,12,NC_011558,1985698
175,Varicosavirus 1,Rhabdoviridae,Lettuce big-vein associated virus RNA 2,LBVaV2,(-)ssRNA,94.9,90.6,98.0,32,NC_011568,1985698
176,Varicosavirus 2,Rhabdoviridae,Lettuce yellow mottle virus,LYMoV,(-)ssRNA,96.2,85.3,100.0,2702,NC_011532,471285

In [24]:
virus_subset = virus[['OTU_taxid', 'NCBI_title', 'OTU_reference', 'NCBI_accession']].rename(columns={'OTU_taxid': 'taxid', 'NCBI_title': 'Scientific_name', 'OTU_reference': 'label'})
virus_subset['Taxon_code'] = [taxonids() for _ in range(len(virus_subset))]

virus_subset

,taxid,Scientific_name,label,NCBI_accession,Taxon_code
0,12321,Alfalfa mosaic virus RNA 1,AMV1,NC_001495,000000000000
1,12321,Alfalfa mosaic virus RNA 2,AMV2,NC_002024,000000000001
2,1776177,Cucumis melo endornavirus,CmEV,NC_029064,000000000002
3,<NA>,Bell pepper endornavirus,BPEV,NC_015781,000000000003
4,1774276,Hordeum vulgare endornavirus,HvEV,NC_028949,000000000004
...,...,...,...,...,...
172,<NA>,Arabidopsis latent virus-1 RNA1,ALaV1,MH899120,000000000172
173,<NA>,Arabidopsis latent virus-1 RNA2,ALaV2,MH899121,000000000173
174,1985698,Lettuce big-vein associated virus RNA 1,LBVaV1,NC_011558,000000000174
175,1985698,Lettuce big-vein associated virus RNA 2,LBVaV2,NC_011568,000000000175
176,471285,Lettuce yellow mottle virus,LYMoV,NC_011532,000000000176

In [25]:
hits = pd.read_csv("data/val_158_otu_host_df.csv", sep=';')
hits = hits.melt(
    id_vars=['Library', 'Host', 'Host_family', 'Habitat', 'Site', 'Collection'],
    value_vars=hits.columns[6:], 
).rename(columns={'variable': "OTU", 'value': "hit"}).query('hit == 1').copy()
hits['Collection'] = hits['Collection'].apply(lambda x: x.split("_")[0])
hits[['Library', 'Host', 'Host_family', 'Habitat', 'Site', 'Collection', 'OTU']]

,Library,Host,Host_family,Habitat,Site,Collection,OTU
74,PV091,Galium verum,Rubiaceae,Oak,Q4,Q4P,AEV1
332,PV059,Tragopogon sp,Asteraceae,Wasteland,E4,E4P,AEYV
425,PV159,Carduus bourgeanus,Asteraceae,Edge,L1,L1V,AEYV
448,PV182,Lactuca serriola,Asteraceae,Edge,L3,L3V,AEYV
537,PV498,Rubia peregrina,Rubiaceae,Crop,H3,H3P,AEYV
...,...,...,...,...,...,...,...
44458,PV172,Picris echioides,Asteraceae,Edge,L2,L2V,YSV
44487,PV201,Convolvulus arvensis,Convolvulaceae,Edge,L1,L1F,YSV
44625,PV047,Zea mays,Poaceae,Crop,Z2,Z2V,ZYMV
44638,PV061,Cucumis melo,Cucurbitaceae,Crop,M1,M5V,ZYMV
44781,PV211,Solanum nigrum,Solanaceae,Edge,L2,L2F,ZYMV

In [26]:
rename_map = pd.read_csv("scratch/mapping-otus-curated.csv", sep="\t", index_col=0)[['otu', 'hit']].set_index('otu').to_dict()['hit']
hits['OTU_rn'] = hits['OTU'].apply(lambda x: rename_map[x])
hits[hits['OTU_rn'].isna()][['OTU']].value_counts()

OTU
BrYV    33
WYDV     4
FMV      1
Name: count, dtype: int64

In [27]:
hits = pd.merge(hits.dropna(subset=['OTU_rn'])[['Library', 'OTU_rn']], virus_subset[['label', 'Taxon_code']], how='left', right_on='label', left_on='OTU_rn')[['Library', 'Taxon_code']]
# hits[hits['OTU name'].isna()][['OTU']].value_counts()

In [28]:
hits

     Library    Taxon_code
0      PV091  000000000055
1      PV059  000000000082
2      PV159  000000000082
3      PV182  000000000082
4      PV498  000000000082
...      ...           ...
1573   PV172  000000000016
1574   PV201  000000000016
1575   PV047  000000000127
1576   PV061  000000000127
1577   PV211  000000000127

[1578 rows x 2 columns]

In [29]:
hits['Hit_code'] = [hitcodes() for _ in range(len(hits))]
hits[['Hit_code', 'Library', 'Taxon_code']]

          Hit_code Library    Taxon_code
0     000000000000   PV091  000000000055
1     000000000001   PV059  000000000082
2     000000000002   PV159  000000000082
3     000000000003   PV182  000000000082
4     000000000004   PV498  000000000082
...            ...     ...           ...
1573  000000001573   PV172  000000000016
1574  000000001574   PV201  000000000016
1575  000000001575   PV047  000000000127
1576  000000001576   PV061  000000000127
1577  000000001577   PV211  000000000127

[1578 rows x 3 columns]

In [30]:
clean_dict = lambda d: {k: d[k] for k in d if not pd.isna(k)}

In [31]:
hits.query('Hit_code == "000000000111"')

    Library    Taxon_code      Hit_code
111   PV176  000000000044  000000000111

In [32]:
virus_library = dict(
    virus=list(map(clean_dict, virus_subset.to_dict(orient='records'))),
    hits=list(map(clean_dict, hits.to_dict(orient='records')))
)
with open("scratch/semantic-model/virus_library.json", "w") as f:
    json.dump(virus_library, f, indent=4, sort_keys=True)

## Step 3 - Bacteria

In [33]:
index_df = pd.read_csv("raw/motus-g1/source.csv", sep=",", header=None, index_col=0, names=['library', 'read1', 'read2'])
index_df

,library,read1,read2
1,PV001,PV1_18807_ATCACG_read1.fastq.gz,PV1_18807_ATCACG_read2.fastq.gz
2,PV002,PV2_18808_TGACCA_read1.fastq.gz,PV2_18808_TGACCA_read2.fastq.gz
3,PV003,PV3_16716_GGCTAC_read1.fastq.gz,PV3_16716_GGCTAC_read2.fastq.gz
4,PV003bgi,FCH5VT5ALXX_L5_HKRDPLAgshTAACRAAPEI-203_1.fq.zip,FCH5VT5ALXX_L5_HKRDPLAgshTAACRAAPEI-203_2.fq.zip
5,PV004bgi,FCH5VT5ALXX_L5_HKRDPLAgshTAADRAAPEI-204_1.fq.zip,FCH5VT5ALXX_L5_HKRDPLAgshTAADRAAPEI-204_2.fq.zip
...,...,...,...
320,PV586,PV586_03661AAB_AGTTGC_read1.fastq.gz,PV586_03661AAB_AGTTGC_read2.fastq.gz
321,PV587,PV587_03662AAB_ACCTTC_read1.fastq.gz,PV587_03662AAB_ACCTTC_read2.fastq.gz
322,PV588,PV588_03663AAB_TCGCAT_read1.fastq.gz,PV588_03663AAB_TCGCAT_read2.fastq.gz
323,PV589,PV589_03664AAB_AGGACT_read1.fastq.gz,PV589_03664AAB_AGGACT_read2.fastq.gz
324,PV590,PV590_03982AAC_TAGCTT_R1_001.fastq.gz,PV590_03982AAC_TAGCTT_R2_001.fastq.

In [34]:
def load_motus_classification(x, library):
    try:
        u = pd.read_csv(x, sep="\t")
    except pd.errors.EmptyDataError:
        u = pd.DataFrame(data=[], columns=['mOTU', 'taxonomy', 'taxid', 'abundance'])
    u.columns = ['mOTU', 'taxonomy', 'taxid', 'abundance']
    u = u.dropna(subset=['taxid'])
    u['library'] = library
    return u

In [35]:
bacteria = dict()
hits = []
for _, row in index_df.iterrows():
    
    u = load_motus_classification("raw/motus-g1/{:s}.classification.csv".format(row['library']), row['library'])
    
    if len(u) > 0:
        for _, item in u.iterrows():
            if item.taxid not in bacteria.keys():
                
                bacteria[item.taxid] = taxonids()
            taxon_code = bacteria[item.taxid]
            hits.append(
                {
                    'Hit_code': hitcodes(),
                    'Library': item.library,
                    'Taxon_code': taxon_code
                    
                }
            )

In [36]:
pd.DataFrame.from_records(hits)

          Hit_code Library    Taxon_code
0     000000001578   PV001  000000000177
1     000000001579   PV002  000000000178
2     000000001580   PV002  000000000177
3     000000001581   PV002  000000000179
4     000000001582   PV003  000000000180
...            ...     ...           ...
1499  000000003077   PV587  000000000317
1500  000000003078   PV588  000000000178
1501  000000003079   PV588  000000000699
1502  000000003080   PV589  000000000389
1503  000000003081   PV589  000000000178

[1504 rows x 3 columns]

In [37]:
bacteria = pd.DataFrame(list(bacteria.items()), columns=['taxonid', 'Taxon_code'])
bacteria['taxonid'] = bacteria['taxonid'].astype(int)

In [38]:
import taxoniq

def fault_tolerant_name(x):
    try:
        return taxoniq.Taxon(x).scientific_name
    except KeyError:
        return ""

In [39]:
bacteria['scientific_name'] = bacteria['taxonid'].apply(lambda x: fault_tolerant_name(x))

In [40]:
bacteria

     taxonid    Taxon_code                scientific_name
0       2097  000000000177      Mycoplasmoides genitalium
1      59620  000000000178     uncultured Clostridium sp.
2      69896  000000000179  Candidatus Phytoplasma solani
3     641148  000000000180   Neisseria sp. oral taxon 014
4    1236179  000000000181     Janthinobacterium sp. B9-8
..       ...           ...                            ...
518  1835723  000000000695       Arthrobacter sp. OY3WO11
519  1955620  000000000696          Hymenobacter sp. CRA2
520   679249  000000000697       Holzapfeliella floricola
521   866801  000000000698       Apilactobacillus ozensis
522    43675  000000000699            Rothia mucilaginosa

[523 rows x 3 columns]

In [41]:
from skbio.tree import TreeNode
tree = TreeNode.read("data/bac120.tree")
tree_tip_names = list(tree.subset())
tree_tip_names
gtdb_metadata = pd.read_csv("data/bac120_metadata.tsv", sep="\t")
gtdb_metadata[gtdb_metadata['gtdb_genome_representative'].apply(lambda x: x.replace("_", " ")).isin(tree_tip_names)]
gtdb_accessions = gtdb_metadata[['ncbi_taxid', 'gtdb_genome_representative']].drop_duplicates('ncbi_taxid', keep='first').copy()
gtdb_accessions['gtdb_genome_representative'] = gtdb_accessions['gtdb_genome_representative'].apply(lambda x: x.replace("_", " "))
# gtdb_accessions.to_csv('scratch/semantic-model/gtdb.csv', sep=',')
gtdb_accessions

        ncbi_taxid gtdb_genome_representative
0          1331258         RS GCF 000657795.2
1             1282         RS GCF 006742205.1
2          2135698         RS GCF 000172415.1
3            90371         RS GCF 000006945.2
4          1236944         RS GCF 029023865.1
...            ...                        ...
584333     1752224         GB GCA 001464955.1
584341     2665509         RS GCF 000006945.2
584345     2530375         RS GCF 004348725.1
584349     2169409         RS GCF 003097655.1
584366     2589941         RS GCF 006442975.2

[89701 rows x 2 columns]

In [42]:
bacteria = pd.merge(bacteria, gtdb_accessions, left_on='taxonid', right_on='ncbi_taxid', how='left')

In [44]:
sanchis21 = pd.read_csv("data/sanchis21.tableS1.csv", sep="\t").drop_duplicates('TaxId', keep='first')
sanchis21['is_pab'] = True
sanchis21['pab_type'] = sanchis21.apply(lambda x: 'pab_pathogen' if x['PAB-phyto'] == 'P' else "pab_unknown", axis=1)
sanchis21['pab_type'] = sanchis21.apply(lambda x: 'pab_symbiont' if x['PAB-symb'] == 'S' else x['pab_type'], axis=1)
sanchis21

,TaxId,Biosample,Representative species,PAB-phyto,PAB-symb,is_pab,pab_type
0,178901,SAMN02849420,Acetobacter malorum,NaN,NaN,True,pab_unknown
1,441768,SAMN02603756,Acholeplasma laidlawii PG-8A,NaN,NaN,True,pab_unknown
2,32002,SAMN06198582,Achromobacter denitrificans,NaN,NaN,True,pab_unknown
3,217204,SAMN06174288,Achromobacter insolitus,NaN,NaN,True,pab_unknown
4,72556,SAMN03941583,Achromobacter piechaudii,NaN,NaN,True,pab_unknown
...,...,...,...,...,...,...,...
955,698414,SAMN06765826,Xylella fastidiosa subsp. pauca,P,NaN,True,pab_pathogen
956,1444770,SAMN02570451,Xylella taiwanensis,P,NaN,True,pab_pathogen
957,1735686,SAMN04151686,Xylophilus sp. Leaf220,NaN,NaN,True,pab_unknown
958,1288385,SAMEA1486427,Yersinia pekkanenii,NaN,NaN,True,pab_unknown
959,1123510,SAMN02952986,Zymobacter palmae DSM 10491,NaN,NaN,True,pab_unknown

In [45]:
bacteria = pd.merge(bacteria, sanchis21[['TaxId', 'is_pab', 'pab_type']], left_on=['ncbi_taxid'], right_on=['TaxId'], how='left')

In [46]:
bacteria

,taxonid,Taxon_code,scientific_name,ncbi_taxid,gtdb_genome_representative,TaxId,is_pab,pab_type
0,2097,000000000177,Mycoplasmoides genitalium,NaN,NaN,NaN,NaN,NaN
1,59620,000000000178,uncultured Clostridium sp.,59620.0,GB GCA 900548855.1,NaN,NaN,NaN
2,69896,000000000179,Candidatus Phytoplasma solani,69896.0,RS GCF 000970375.1,NaN,NaN,NaN
3,641148,000000000180,Neisseria sp. oral taxon 014,641148.0,RS GCF 005886145.1,NaN,NaN,NaN
4,1236179,000000000181,Janthinobacterium sp. B9-8,1236179.0,RS GCF 000969645.2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
518,1835723,000000000695,Arthrobacter sp. OY3WO11,1835723.0,RS GCF 001641125.1,1835723.0,True,pab_unknown
519,1955620,000000000696,Hymenobacter sp. CRA2,1955620.0,RS GCF 002007105.1,NaN,NaN,NaN
520,679249,000000000697,Holzapfeliella floricola,NaN,NaN,NaN,NaN,NaN
521,866801,000000000698,Apilactobacillus ozensis,866801.0,RS GCF 001435995.1,NaN,NaN,NaN
522,43675,000000000699,Rothia mucilaginosa,43675.0,RS GCF 000175615.1,NaN,NaN,NaN

In [47]:
def clean_dict(x):
    new_dict = dict()
    for key, item in x.items():
        if not pd.isna(item):
            new_dict[key] = item
    return new_dict

In [48]:
bacteria_records = dict(
    taxon=list(map(clean_dict, bacteria.to_dict(orient='records'))),
    hits=hits
)




with open("scratch/semantic-model/bacteria_library.json", "w") as f:
    json.dump(bacteria_records, f, indent=4, sort_keys=True)

In [49]:
clean_dict(bacteria_records['taxon'][6])

{'taxonid': 29448,
 'Taxon_code': '000000000183',
 'scientific_name': 'Bradyrhizobium elkanii',
 'ncbi_taxid': 29448.0,
 'gtdb_genome_representative': 'RS GCF 023278185.1',
 'TaxId': 29448.0,
 'is_pab': True,
 'pab_type': 'pab_symbiont'}

In [50]:
bacteria_records['taxon']

[{'taxonid': 2097,
  'Taxon_code': '000000000177',
  'scientific_name': 'Mycoplasmoides genitalium'},
 {'taxonid': 59620,
  'Taxon_code': '000000000178',
  'scientific_name': 'uncultured Clostridium sp.',
  'ncbi_taxid': 59620.0,
  'gtdb_genome_representative': 'GB GCA 900548855.1'},
 {'taxonid': 69896,
  'Taxon_code': '000000000179',
  'scientific_name': 'Candidatus Phytoplasma solani',
  'ncbi_taxid': 69896.0,
  'gtdb_genome_representative': 'RS GCF 000970375.1'},
 {'taxonid': 641148,
  'Taxon_code': '000000000180',
  'scientific_name': 'Neisseria sp. oral taxon 014',
  'ncbi_taxid': 641148.0,
  'gtdb_genome_representative': 'RS GCF 005886145.1'},
 {'taxonid': 1236179,
  'Taxon_code': '000000000181',
  'scientific_name': 'Janthinobacterium sp. B9-8',
  'ncbi_taxid': 1236179.0,
  'gtdb_genome_representative': 'RS GCF 000969645.2'},
 {'taxonid': 1293,
  'Taxon_code': '000000000182',
  'scientific_name': 'Staphylococcus gallinarum',
  'ncbi_taxid': 1293.0,
  'gtdb_genome_representative': 'RS GCF 000875895.1'},
 {'taxonid': 29448,
  'Taxon_code': '000000000183',
  'scientific_name': 'Bradyrhizobium elkanii',
  'ncbi_taxid': 29448.0,
  'gtdb_genome_representative': 'RS GCF 023278185.1',
  'TaxId': 29448.0,
  'is_pab': True,
  'pab_type': 'pab_symbiont'},
 {'taxonid': 40324,
  'Taxon_code': '000000000184',
  'scientific_name': 'Stenotrophomonas maltophilia',
  'ncbi_taxid': 40324.0,
  'gtdb_genome_representative': 'RS GCF 024621935.1',
  'TaxId': 40324.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 948102,
  'Taxon_code': '000000000185',
  'scientific_name': 'Mycobacteroides franklinii',
  'ncbi_taxid': 948102.0,
  'gtdb_genome_representative': 'RS GCF 002013895.1'},
 {'taxonid': 93064,
  'Taxon_code': '000000000186',
  'scientific_name': 'Sphingomonas koreensis',
  'ncbi_taxid': 93064.0,
  'gtdb_genome_representative': 'RS GCF 002797435.1'},
 {'taxonid': 1797569,
  'Taxon_code': '000000000187',
  'scientific_name': 'Burkholderiales bacterium RIFCSPLOWO2_12_FULL_65_40',
  'ncbi_taxid': 1797569.0,
  'gtdb_genome_representative': 'GB GCA 001770955.1'},
 {'taxonid': 1747,
  'Taxon_code': '000000000188',
  'scientific_name': 'Cutibacterium acnes',
  'ncbi_taxid': 1747.0,
  'gtdb_genome_representative': 'RS GCF 003030305.1'},
 {'taxonid': 2702,
  'Taxon_code': '000000000189',
  'scientific_name': 'Gardnerella vaginalis',
  'ncbi_taxid': 2702.0,
  'gtdb_genome_representative': 'RS GCF 001042655.1'},
 {'taxonid': 630921,
  'Taxon_code': '000000000190',
  'scientific_name': 'Bradyrhizobium embrapense',
  'ncbi_taxid': 630921.0,
  'gtdb_genome_representative': 'RS GCF 001189235.2',
  'TaxId': 630921.0,
  'is_pab': True,
  'pab_type': 'pab_symbiont'},
 {'taxonid': 172088,
  'Taxon_code': '000000000191',
  'scientific_name': 'Bradyrhizobium sp. th.b2',
  'ncbi_taxid': 172088.0,
  'gtdb_genome_representative': 'RS GCF 011516645.4',
  'TaxId': 172088.0,
  'is_pab': True,
  'pab_type': 'pab_symbiont'},
 {'taxonid': 1230476,
  'Taxon_code': '000000000192',
  'scientific_name': 'Bradyrhizobium sp. DFCI-1',
  'ncbi_taxid': 1230476.0,
  'gtdb_genome_representative': 'GB GCA 016839165.1',
  'TaxId': 1230476.0,
  'is_pab': True,
  'pab_type': 'pab_symbiont'},
 {'taxonid': 34073,
  'Taxon_code': '000000000193',
  'scientific_name': 'Variovorax paradoxus',
  'ncbi_taxid': 34073.0,
  'gtdb_genome_representative': 'RS GCF 003965815.1',
  'TaxId': 34073.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 1463921,
  'Taxon_code': '000000000194',
  'scientific_name': 'Streptomyces sp. NRRL S-920',
  'ncbi_taxid': 1463921.0,
  'gtdb_genome_representative': 'RS GCF 008704395.1'},
 {'taxonid': 1437360,
  'Taxon_code': '000000000195',
  'scientific_name': 'Bradyrhizobium erythrophlei',
  'ncbi_taxid': 1437360.0,
  'gtdb_genome_representative': 'RS GCF 900129505.1',
  'TaxId': 1437360.0,
  'is_pab': True,
  'pab_type': 'pab_symbiont'},
 {'taxonid': 544911,
  'Taxon_code': '000000000196',
  'scientific_name': 'Massilia niastensis'},
 {'taxonid': 1881038,
  'Taxon_code': '000000000197',
  'scientific_name': 'Duganella sp. CF517',
  'ncbi_taxid': 1881038.0,
  'gtdb_genome_representative': 'RS GCF 900110275.1',
  'TaxId': 1881038.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 1735672,
  'Taxon_code': '000000000198',
  'scientific_name': 'Chryseobacterium sp. Leaf201',
  'ncbi_taxid': 1735672.0,
  'gtdb_genome_representative': 'RS GCF 001421435.1',
  'TaxId': 1735672.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 426226,
  'Taxon_code': '000000000199',
  'scientific_name': 'Flavobacterium subsaxonicum'},
 {'taxonid': 307480,
  'Taxon_code': '000000000200',
  'scientific_name': 'Chryseobacterium vrystaatense',
  'ncbi_taxid': 307480.0,
  'gtdb_genome_representative': 'RS GCF 000737765.1'},
 {'taxonid': 2035,
  'Taxon_code': '000000000201',
  'scientific_name': 'Curtobacterium flaccumfaciens',
  'ncbi_taxid': 2035.0,
  'gtdb_genome_representative': 'RS GCF 025451635.1',
  'TaxId': 2035.0,
  'is_pab': True,
  'pab_type': 'pab_pathogen'},
 {'taxonid': 1566263,
  'Taxon_code': '000000000202',
  'scientific_name': 'Rhizobium sp. NFR03',
  'ncbi_taxid': 1566263.0,
  'gtdb_genome_representative': 'RS GCF 900111275.1',
  'TaxId': 1566263.0,
  'is_pab': True,
  'pab_type': 'pab_symbiont'},
 {'taxonid': 1736355,
  'Taxon_code': '000000000203',
  'scientific_name': 'Rhizobium sp. Leaf371',
  'ncbi_taxid': 1736355.0,
  'gtdb_genome_representative': 'RS GCF 001424045.1',
  'TaxId': 1736355.0,
  'is_pab': True,
  'pab_type': 'pab_symbiont'},
 {'taxonid': 562,
  'Taxon_code': '000000000204',
  'scientific_name': 'Escherichia coli',
  'ncbi_taxid': 562.0,
  'gtdb_genome_representative': 'RS GCF 003697165.2'},
 {'taxonid': 1736286,
  'Taxon_code': '000000000205',
  'scientific_name': 'Pedobacter sp. Leaf176',
  'ncbi_taxid': 1736286.0,
  'gtdb_genome_representative': 'RS GCF 001424305.1',
  'TaxId': 1736286.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 482564,
  'Taxon_code': '000000000206',
  'scientific_name': 'Oscillatoria nigro-viridis'},
 {'taxonid': 1484116,
  'Taxon_code': '000000000207',
  'scientific_name': 'Hymenobacter psoromatis',
  'ncbi_taxid': 1484116.0,
  'gtdb_genome_representative': 'GB GCA 001596155.1'},
 {'taxonid': 1736218,
  'Taxon_code': '000000000208',
  'scientific_name': 'Pedobacter sp. Leaf41',
  'ncbi_taxid': 1736218.0,
  'gtdb_genome_representative': 'RS GCF 001422545.1',
  'TaxId': 1736218.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 1736356,
  'Taxon_code': '000000000209',
  'scientific_name': 'Modestobacter sp. Leaf380',
  'ncbi_taxid': 1736356.0,
  'gtdb_genome_representative': 'RS GCF 001424485.1',
  'TaxId': 1736356.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 391596,
  'Taxon_code': '000000000210',
  'scientific_name': 'Pedobacter sp. BAL39',
  'ncbi_taxid': 391596.0,
  'gtdb_genome_representative': 'RS GCF 000170795.1'},
 {'taxonid': 273678,
  'Taxon_code': '000000000211',
  'scientific_name': 'Microbacterium hydrocarbonoxydans',
  'ncbi_taxid': 273678.0,
  'gtdb_genome_representative': 'RS GCF 000956475.1'},
 {'taxonid': 1735684,
  'Taxon_code': '000000000212',
  'scientific_name': 'Pedobacter sp. Leaf216',
  'ncbi_taxid': 1735684.0,
  'gtdb_genome_representative': 'RS GCF 001421515.1',
  'TaxId': 1735684.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 1943632,
  'Taxon_code': '000000000213',
  'scientific_name': 'Pseudomonas sp. Bc-h',
  'ncbi_taxid': 1943632.0,
  'gtdb_genome_representative': 'RS GCF 002080045.1'},
 {'taxonid': 1736276,
  'Taxon_code': '000000000214',
  'scientific_name': 'Microbacterium sp. Leaf151',
  'ncbi_taxid': 1736276.0,
  'gtdb_genome_representative': 'RS GCF 001424225.1',
  'TaxId': 1736276.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 1736361,
  'Taxon_code': '000000000215',
  'scientific_name': 'Chryseobacterium sp. Leaf394',
  'ncbi_taxid': 1736361.0,
  'gtdb_genome_representative': 'RS GCF 001424105.1',
  'TaxId': 1736361.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 96345,
  'Taxon_code': '000000000216',
  'scientific_name': 'Flavobacterium psychrophilum',
  'ncbi_taxid': 96345.0,
  'gtdb_genome_representative': 'GB GCA 009700115.1'},
 {'taxonid': 358,
  'Taxon_code': '000000000217',
  'scientific_name': 'Agrobacterium tumefaciens',
  'ncbi_taxid': 358.0,
  'gtdb_genome_representative': 'RS GCF 015704895.1',
  'TaxId': 358.0,
  'is_pab': True,
  'pab_type': 'pab_pathogen'},
 {'taxonid': 408657,
  'Taxon_code': '000000000218',
  'scientific_name': 'Dyadobacter koreensis',
  'ncbi_taxid': 408657.0,
  'gtdb_genome_representative': 'RS GCF 900108855.1'},
 {'taxonid': 1563157,
  'Taxon_code': '000000000219',
  'scientific_name': 'Pseudomonas endophytica',
  'ncbi_taxid': 1563157.0,
  'gtdb_genome_representative': 'RS GCF 001411475.1',
  'TaxId': 1563157.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 1828,
  'Taxon_code': '000000000220',
  'scientific_name': 'Rhodococcoides fascians',
  'ncbi_taxid': 1828.0,
  'gtdb_genome_representative': 'RS GCF 002259415.1',
  'TaxId': 1828.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 1549858,
  'Taxon_code': '000000000221',
  'scientific_name': 'Sphingomonas taxi',
  'ncbi_taxid': 1549858.0,
  'gtdb_genome_representative': 'GB GCA 003240625.1',
  'TaxId': 1549858.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 243924,
  'Taxon_code': '000000000222',
  'scientific_name': 'Pseudomonas lutea',
  'ncbi_taxid': 243924.0,
  'gtdb_genome_representative': 'RS GCF 000759445.1',
  'TaxId': 243924.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 661329,
  'Taxon_code': '000000000223',
  'scientific_name': 'Herbiconiux solani'},
 {'taxonid': 964,
  'Taxon_code': '000000000224',
  'scientific_name': 'Herbaspirillum seropedicae',
  'ncbi_taxid': 964.0,
  'gtdb_genome_representative': 'RS GCF 001040945.1',
  'TaxId': 964.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 1736265,
  'Taxon_code': '000000000225',
  'scientific_name': 'Methylobacterium sp. Leaf125',
  'ncbi_taxid': 1736265.0,
  'gtdb_genome_representative': 'RS GCF 001423085.1',
  'TaxId': 1736265.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 1736254,
  'Taxon_code': '000000000226',
  'scientific_name': 'Methylobacterium sp. Leaf104',
  'ncbi_taxid': 1736254.0,
  'gtdb_genome_representative': 'RS GCF 001422885.1',
  'TaxId': 1736254.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 339,
  'Taxon_code': '000000000227',
  'scientific_name': 'Xanthomonas campestris',
  'ncbi_taxid': 339.0,
  'gtdb_genome_representative': 'RS GCF 000007145.1',
  'TaxId': 339.0,
  'is_pab': True,
  'pab_type': 'pab_pathogen'},
 {'taxonid': 1736297,
  'Taxon_code': '000000000228',
  'scientific_name': 'Pedobacter sp. Leaf194',
  'ncbi_taxid': 1736297.0,
  'gtdb_genome_representative': 'RS GCF 001423945.1',
  'TaxId': 1736297.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 407234,
  'Taxon_code': '000000000229',
  'scientific_name': 'Phaeovulum vinaykumarii',
  'ncbi_taxid': 407234.0,
  'gtdb_genome_representative': 'RS GCF 900156695.1'},
 {'taxonid': 37637,
  'Taxon_code': '000000000230',
  'scientific_name': 'Corynebacterium pseudodiphtheriticum',
  'ncbi_taxid': 37637.0,
  'gtdb_genome_representative': 'RS GCF 000688415.1'},
 {'taxonid': 1034,
  'Taxon_code': '000000000231',
  'scientific_name': 'Afipia clevelandensis'},
 {'taxonid': 492736,
  'Taxon_code': '000000000232',
  'scientific_name': 'Dyadobacter alkalitolerans'},
 {'taxonid': 1628856,
  'Taxon_code': '000000000233',
  'scientific_name': 'bacteria symbiont BFo2 of Frankliniella occidentalis',
  'ncbi_taxid': 1628856.0,
  'gtdb_genome_representative': 'RS GCF 018494055.1'},
 {'taxonid': 988801,
  'Taxon_code': '000000000234',
  'scientific_name': 'Rosenbergiella nectarea',
  'ncbi_taxid': 988801.0,
  'gtdb_genome_representative': 'RS GCF 018494085.1'},
 {'taxonid': 1304,
  'Taxon_code': '000000000235',
  'scientific_name': 'Streptococcus salivarius',
  'ncbi_taxid': 1304.0,
  'gtdb_genome_representative': 'RS GCF 000785515.1'},
 {'taxonid': 1736282,
  'Taxon_code': '000000000236',
  'scientific_name': 'Frigoribacterium sp. Leaf164',
  'ncbi_taxid': 1736282.0,
  'gtdb_genome_representative': 'RS GCF 011759585.1',
  'TaxId': 1736282.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 91844,
  'Taxon_code': '000000000237',
  'scientific_name': 'Candidatus Portiera aleyrodidarum',
  'ncbi_taxid': 91844.0,
  'gtdb_genome_representative': 'RS GCF 000300075.1'},
 {'taxonid': 1217718,
  'Taxon_code': '000000000238',
  'scientific_name': 'Cupriavidus sp. BIS7',
  'ncbi_taxid': 1217718.0,
  'gtdb_genome_representative': 'RS GCF 000292345.1'},
 {'taxonid': 28447,
  'Taxon_code': '000000000239',
  'scientific_name': 'Clavibacter michiganensis',
  'ncbi_taxid': 28447.0,
  'gtdb_genome_representative': 'GB GCA 002150995.1'},
 {'taxonid': 134676,
  'Taxon_code': '000000000240',
  'scientific_name': 'Actinoplanes sp. SE50/110',
  'ncbi_taxid': 134676.0,
  'gtdb_genome_representative': 'RS GCF 900119315.1'},
 {'taxonid': 28038,
  'Taxon_code': '000000000241',
  'scientific_name': 'Latilactobacillus curvatus',
  'ncbi_taxid': 28038.0,
  'gtdb_genome_representative': 'RS GCF 004101845.1'},
 {'taxonid': 1249,
  'Taxon_code': '000000000242',
  'scientific_name': 'Weissella paramesenteroides',
  'ncbi_taxid': 1249.0,
  'gtdb_genome_representative': 'RS GCF 000160575.1'},
 {'taxonid': 1619313,
  'Taxon_code': '000000000243',
  'scientific_name': 'Duffyella gerundensis',
  'ncbi_taxid': 1619313.0,
  'gtdb_genome_representative': 'RS GCF 001517405.1',
  'TaxId': 1619313.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 553,
  'Taxon_code': '000000000244',
  'scientific_name': 'Pantoea ananatis',
  'ncbi_taxid': 553.0,
  'gtdb_genome_representative': 'RS GCF 000710035.2',
  'TaxId': 553.0,
  'is_pab': True,
  'pab_type': 'pab_pathogen'},
 {'taxonid': 1050843, 'Taxon_code': '000000000245', 'scientific_name': ''},
 {'taxonid': 1528099,
  'Taxon_code': '000000000246',
  'scientific_name': 'Lawsonella clevelandensis',
  'ncbi_taxid': 1528099.0,
  'gtdb_genome_representative': 'RS GCF 001293125.1'},
 {'taxonid': 1290,
  'Taxon_code': '000000000247',
  'scientific_name': 'Staphylococcus hominis',
  'ncbi_taxid': 1290.0,
  'gtdb_genome_representative': 'RS GCF 002901845.1'},
 {'taxonid': 1282,
  'Taxon_code': '000000000248',
  'scientific_name': 'Staphylococcus epidermidis',
  'ncbi_taxid': 1282.0,
  'gtdb_genome_representative': 'RS GCF 006742205.1'},
 {'taxonid': 428990,
  'Taxon_code': '000000000249',
  'scientific_name': 'Novosphingobium mathurense',
  'ncbi_taxid': 428990.0,
  'gtdb_genome_representative': 'RS GCF 900168325.1'},
 {'taxonid': 1628855,
  'Taxon_code': '000000000250',
  'scientific_name': 'bacteria symbiont BFo1 of Frankliniella occidentalis',
  'ncbi_taxid': 1628855.0,
  'gtdb_genome_representative': 'RS GCF 024169515.1'},
 {'taxonid': 287,
  'Taxon_code': '000000000251',
  'scientific_name': 'Pseudomonas aeruginosa',
  'ncbi_taxid': 287.0,
  'gtdb_genome_representative': 'RS GCF 001457615.1'},
 {'taxonid': 1735679,
  'Taxon_code': '000000000252',
  'scientific_name': 'Sphingomonas sp. Leaf208',
  'ncbi_taxid': 1735679.0,
  'gtdb_genome_representative': 'RS GCF 001421415.1',
  'TaxId': 1735679.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 1545443,
  'Taxon_code': '000000000253',
  'scientific_name': 'Belnapia sp. F-4-1',
  'ncbi_taxid': 1545443.0,
  'gtdb_genome_representative': 'RS GCF 000802185.1'},
 {'taxonid': 196914,
  'Taxon_code': '000000000254',
  'scientific_name': 'Amorphoplanes friuliensis'},
 {'taxonid': 1411621,
  'Taxon_code': '000000000255',
  'scientific_name': 'Hymenobacter sedentarius',
  'ncbi_taxid': 1411621.0,
  'gtdb_genome_representative': 'RS GCF 001507645.1'},
 {'taxonid': 1736691,
  'Taxon_code': '000000000256',
  'scientific_name': 'Aeromicrobium choanae',
  'ncbi_taxid': 1736691.0,
  'gtdb_genome_representative': 'GB GCA 029265505.1'},
 {'taxonid': 314266,
  'Taxon_code': '000000000257',
  'scientific_name': 'Sphingomonas sp. SKA58',
  'ncbi_taxid': 314266.0,
  'gtdb_genome_representative': 'RS GCF 020782245.1'},
 {'taxonid': 1298862,
  'Taxon_code': '000000000258',
  'scientific_name': 'Caulobacter sp. URHA0033'},
 {'taxonid': 9,
  'Taxon_code': '000000000259',
  'scientific_name': 'Buchnera aphidicola',
  'ncbi_taxid': 9.0,
  'gtdb_genome_representative': 'RS GCF 005237295.1'},
 {'taxonid': 2052828,
  'Taxon_code': '000000000260',
  'scientific_name': 'Agrobacterium bohemicum',
  'ncbi_taxid': 2052828.0,
  'gtdb_genome_representative': 'RS GCF 002896715.1'},
 {'taxonid': 286638,
  'Taxon_code': '000000000261',
  'scientific_name': 'Massilia alkalitolerans'},
 {'taxonid': 199592,
  'Taxon_code': '000000000262',
  'scientific_name': 'Microbacterium paraoxydans',
  'ncbi_taxid': 199592.0,
  'gtdb_genome_representative': 'RS GCF 019056515.1'},
 {'taxonid': 459472,
  'Taxon_code': '000000000263',
  'scientific_name': 'Planococcus glaciei',
  'ncbi_taxid': 459472.0,
  'gtdb_genome_representative': 'RS GCF 900099655.1'},
 {'taxonid': 1502773,
  'Taxon_code': '000000000264',
  'scientific_name': 'Curtobacterium sp. UNCCL20',
  'ncbi_taxid': 1502773.0,
  'gtdb_genome_representative': 'RS GCF 900101675.1'},
 {'taxonid': 2033,
  'Taxon_code': '000000000265',
  'scientific_name': 'Microbacterium testaceum',
  'ncbi_taxid': 2033.0,
  'gtdb_genome_representative': 'RS GCF 001476285.1',
  'TaxId': 2033.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 1736291,
  'Taxon_code': '000000000266',
  'scientific_name': 'Curtobacterium sp. Leaf183',
  'ncbi_taxid': 1736291.0,
  'gtdb_genome_representative': 'RS GCF 003234655.2',
  'TaxId': 1736291.0,
  'is_pab': True,
  'pab_type': 'pab_pathogen'},
 {'taxonid': 393310,
  'Taxon_code': '000000000267',
  'scientific_name': 'Skermanella aerolata',
  'ncbi_taxid': 393310.0,
  'gtdb_genome_representative': 'RS GCF 000936425.1'},
 {'taxonid': 33876,
  'Taxon_code': '000000000268',
  'scientific_name': 'Catenuloplanes japonicus',
  'ncbi_taxid': 33876.0,
  'gtdb_genome_representative': 'RS GCF 000717135.1'},
 {'taxonid': 293890,
  'Taxon_code': '000000000269',
  'scientific_name': 'Agromyces subbeticus'},
 {'taxonid': 402650,
  'Taxon_code': '000000000270',
  'scientific_name': 'Actinomycetospora chiangmaiensis'},
 {'taxonid': 1158293,
  'Taxon_code': '000000000271',
  'scientific_name': 'Oxalobacteraceae bacterium AB_14',
  'ncbi_taxid': 1158293.0,
  'gtdb_genome_representative': 'GB GCA 000381565.1'},
 {'taxonid': 257003,
  'Taxon_code': '000000000272',
  'scientific_name': 'Sphingomonas phyllosphaerae',
  'ncbi_taxid': 257003.0,
  'gtdb_genome_representative': 'RS GCF 029623345.1'},
 {'taxonid': 69218,
  'Taxon_code': '000000000273',
  'scientific_name': 'Enterobacter cancerogenus',
  'ncbi_taxid': 69218.0,
  'gtdb_genome_representative': 'RS GCF 019047785.1',
  'TaxId': 69218.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 33968,
  'Taxon_code': '000000000274',
  'scientific_name': 'Leuconostoc pseudomesenteroides',
  'ncbi_taxid': 33968.0,
  'gtdb_genome_representative': 'RS GCF 014634745.1'},
 {'taxonid': 1121252,
  'Taxon_code': '000000000275',
  'scientific_name': 'Cucumibacter marinus'},
 {'taxonid': 1761900,
  'Taxon_code': '000000000276',
  'scientific_name': 'Rhizobium sp. 9140',
  'ncbi_taxid': 1761900.0,
  'gtdb_genome_representative': 'RS GCF 900067135.1',
  'TaxId': 1761900.0,
  'is_pab': True,
  'pab_type': 'pab_symbiont'},
 {'taxonid': 587753,
  'Taxon_code': '000000000277',
  'scientific_name': 'Pseudomonas chlororaphis',
  'ncbi_taxid': 587753.0,
  'gtdb_genome_representative': 'RS GCF 013466605.1',
  'TaxId': 587753.0,
  'is_pab': True,
  'pab_type': 'pab_unknown'},
 {'taxonid': 95300,
  'Taxon_code': '000000000278',